"""Experience-first patron review bodies — no product title repetition."""

import re
from prv_category_rules import BANNED_BODY_PATTERNS, FORBIDDEN


def _cap(s: str) -> str:
    s = s.strip()
    if not s:
        return s
    return s[0].upper() + s[1:]


def _validate(axis: str, body: str) -> bool:
    low = body.lower()
    for pat in BANNED_BODY_PATTERNS:
        if re.search(pat, body, re.IGNORECASE):
            return False
    for term in FORBIDDEN.get(axis, []):
        if term.lower() in low:
            return False
    if re.search(r"\b(long lasting|pure sandalwood|natural ingredients|premium texture)\b", low):
        return False
    return True


def _opening_key(opening: str) -> str:
    return opening.strip().lower()


def build_reviews(axis: str, openings: list[str], experiences: list[str], closers: list[str] | None = None, count: int = 95) -> list[str]:
    closers = closers or []
    out: list[str] = []
    used: set[str] = set()
    o_n, e_n = len(openings), len(experiences)
    c_n = len(closers) or 1

    for i in range(count):
        found = False
        for attempt in range(o_n * e_n * max(c_n, 1) * 8):
            o = openings[(i * 17 + attempt * 13) % o_n]
            e = experiences[(i * 11 + attempt * 7) % e_n]
            if closers and (i + attempt) % 3 != 0:
                c = closers[(i * 13 + attempt * 3) % c_n]
                body = _cap(f"{o} {e} {c}")
            else:
                body = _cap(f"{o} {e}")
            if body in used:
                continue
            if not _validate(axis, body):
                continue
            used.add(body)
            out.append(body)
            found = True
            break
        if not found:
            raise RuntimeError(f"Could not build review {i} for {axis} (openings={o_n}, experiences={e_n})")
    return out[:count]


def combo_openings(prefixes: list[str], suffixes: list[str], min_count: int = 96) -> list[str]:
    out: list[str] = []
    for i in range(min_count * 3):
        p = prefixes[i % len(prefixes)]
        s = suffixes[(i * 7 + 3) % len(suffixes)]
        text = f"{p} {s}".strip()
        if text not in out:
            out.append(text)
        if len(out) >= min_count:
            return out
    return out


# --- Curated pools per collection ---

INCENSE_O = [
    "Bought this for daily morning puja.",
    "Initially I wasn't sure about premium agarbatti.",
    "My mother uses one stick every evening for aarti.",
    "My wife gifted this after our temple visit.",
    "After almost two weeks of daily burn,",
    "Been using it every morning before office.",
    "Tried this during our Satyanarayan katha at home.",
    "Unexpectedly, guests asked about the fragrance.",
    "Honestly, local sticks used to give me headache.",
    "Didn't expect the room to smell this clean.",
    "My father insisted we switch from market agarbatti.",
    "My grandmother approved after one evening aarti.",
    "We use it in the small mandir corner.",
    "First impression was the slow, even burn.",
    "Second box already ordered — that says enough.",
    "Kept one pack in the guest room for festivals.",
    "Puja ke baad room ka ambience hi change lagta hai.",
    "Sunday ghar saaf karke yeh jalana ritual ban gaya.",
    "Meditation corner mein ek stick kaafi shaant lagti hai.",
    "Diwali week mein poora ghar warm sacred feel aaya.",
    "Yoga class ke baad instructor ne room smell notice kiya.",
    "Monsoon mein window thoda khula rakho — smoke light rehti hai.",
    "Temple visit ke baad ghar mein wahi calm dhoondh rahi thi.",
    "Asthma sensitive hoon — mild smoke, no irritation so far.",
    "Repeat customer — teen box ho chuke ab.",
    "Corporate gift nahi, personal puja ke liye liya.",
    "Instagram se dekha, skeptical thi, pleasantly surprised.",
    "Packaging simple thi par stick quality clearly premium.",
    "Holder apna use kiya — evenly burn hoti hai.",
    "4 star feel: ek baar burn time thoda kam tha.",
    "Evening aarti ke baad poora flat peaceful lagta hai.",
    "Nani ke time ki agarbatti ki yaad dilayi — cleaner version.",
    "Subah 5 baje uth ke pehli cheez yeh hi jalati hoon.",
    "Festival rush mein order kiya — delivery time theek tha.",
    "Kid ne bola ghar achha smell kar raha — rare compliment.",
]

INCENSE_E = [
    "the fragrance fills the prayer room within minutes.",
    "ash kam nikalta hai, floor messy nahi hota.",
    "smoke halki hai — balcony door band karke bhi theek.",
    "evening aarti ke baad scent room mein rehti hai.",
    "slow burn sach mein slow hai, jaldi khatam nahi hoti.",
    "chemical headache wala feel bilkul nahi aaya.",
    "guests ne puja ke baad smell appreciate kiya.",
    "diya ke saath blend achha lagta hai, clash nahi.",
    "meditation ke dauran distraction nahi deti.",
    "mummy bolti hain mandir jaisa feel ghar mein aa jata hai.",
    "hand-rolled jaisa texture — loose market se farak hai.",
    "festive week stock kar liya poori family ke liye.",
    "morning puja ab bina iske adhoori lagti hai.",
    "lavender wala variant shaam ko mann halka karta hai.",
    "kesar-chandan wala warm sacred lagta hai diwali pe.",
    "jasmine soft hai — overpower nahi karti.",
    "humid din mein bhi clean smoke, stuffy nahi.",
    "first premium agarbatti — ab local wapas nahi.",
    "holder mein tik kar burn hoti hai, break kam.",
    "repeat order because batch consistency achhi rahi.",
    "temple visit memory ghar laane jaisa feel deta hai.",
    "aarti ke baad kurta par faint fragrance rehti hai.",
    "honestly worth the extra rupees for daily puja.",
    "only wish thoda bada pack option ho monthly users ke liye.",
    "delivery box thoda dented tha, sticks safe the.",
    "puja room ke bahar hallway mein bhi halki khushboo.",
    "weekend deep clean ke saath yeh burn karna satisfying hai.",
    "sach bolu, packaging se hi premium feel aa gayi.",
]

NAKSHATRA_O = [
    "Family astrologer suggested something aligned with my janma nakshatra.",
    "Bought this after reading about birth-star fragrances in a Vedic book.",
    "My brother picked a nakshatra attar for my birthday — thoughtful.",
    "Janma nakshatra homam ke din pehna — quiet, personal ritual.",
    "Honestly I was sceptical about star-based attars.",
    "Vedic consultation ke baad order kiya — remedy feel without drama.",
    "Evening prayer routine mein yeh add ho gaya ab.",
    "Wife ne apne birth star ke hisaab se gift kiya.",
    "Mummy ne kaha hamare ghar mein pehle bhi star attar lagte the.",
    "New moon night pehli baar try kiya — calm anchor laga.",
    "Ancestral remembrance day par lagaya — grandmother ki yaad aayi.",
    "Pehla nakshatra attar — line explore karne ka achha start.",
    "Chanting practice ke saath breath slow ho jati hai.",
    "Wedding muhurat shopping mein bride ko gift — she loved the meaning.",
    "Chart reading ke din astrologer friend ne casually notice kiya.",
    "Puja room corner mein rakha — meditation ke paas hi.",
    "Restock kiya same birth star — batch consistent laga.",
    "Rishikesh trip se laaya — ghar mein wahi shaanti.",
    "Projection bahut soft — prayer ke liye sahi, party ke liye nahi.",
    "Monsoon mein ek extra dab — expected, phir bhi theek.",
    "Winter evening prayers ke liye warm hold milta hai.",
    "Aunt ne family function pe compliment diya — subtle tha.",
    "Slow attachment — week do mein daily ritual ban gaya.",
    "Muhurat impulse buy tha — best impulse in months.",
    "First Anand Rasa order nakshatra line se — hooked.",
    "Baarish ke din birth star ritual cozy lagta hai.",
    "Subtle enough for temple — loud announce nahi karta.",
    "Astrologer ne casually kaha achha choice hai — din ban gaya.",
    "Mom same nakshatra — matching scents ghar mein.",
    "Spiritual alignment note marketing lag sakta hai par feel real hai.",
    "Repeat annual homam ke liye har saal order.",
    "Quiet evenings ka default ban gaya.",
    "Initially doubtful; ab bina lagaye dua adhoori lagti hai.",
    "Mann halka ho jata hai shaam ki dua ke baad.",
    "Gift father ko unke janma star ke hisaab se — roz use karte hain.",
]

NAKSHATRA_E = [
    "evening prayer feels complete with a few drops on the wrist.",
    "scent is peaceful — aggressive sweet notes nahi.",
    "breathwork ke dauran mann zyada settled lagta hai.",
    "cotton kurta par subah tak faint trace rehti hai.",
    "sensitive skin — week trial, no rash.",
    "gift wale ko star ka matlab turant samajh aaya.",
    "puja ke baad ghar mein mandir wali feeling aati hai.",
    "meditation cushion ke paas baithna easy ho jata hai.",
    "opening minute sharp, dry-down warm aur grounded.",
    "alcohol perfume se zyada shaant — ritual ke liye better.",
    "layer kiya coconut oil se — longevity badhi thodi.",
    "honest drawback: chhoti bottle daily users ke liye.",
    "premium packaging tradition ko respect karti hai.",
    "repeat third bottle — loyalty speaks.",
    "headache prone hoon — trigger nahi hua, relief.",
    "incense ke baad lagana complementary lagta hai.",
    "instagram vedic page se dekha — gimmick nahi laga.",
    "temple visit on star day felt extra meaningful.",
    "wedding guest ne nakshatra talk pe bonding hui.",
    "mann shaant — exactly birth star ritual jaisa chahiye tha.",
    "honest 4 star: opening sharp mere taste ko, dry-down ne rukne diya.",
    "fabric dupatta par hold impressive for oil attar.",
    "cosmic calm cheesy word hai par feel genuine hai.",
    "not for club or office — personal prayer scent.",
    "kaafi gentle — paas wale poochte hain, door se announce nahi.",
    "vedic warmth believable — synthetic shout nahi.",
    "father retirement gift — unhone daily evening use shuru kiya.",
    "journal likhte waqt star theme match karta hai.",
    "worth it as a meaningful gift for astrology believers.",
]

PLANET_O = [
    "Mummy ne graha remedy ke liye suggest kiya.",
    "Sunday havan ke din lagana ab habit hai.",
    "Astrologer ne morning prayer routine mein add karne ko kaha.",
    "Temple queue mein wait karte waqt lagati hoon.",
    "Japa mala ke saath use karti hoon — scent chant ke rhythm mein aa jata hai.",
    "Pehli baar Navagraha attar liya — warm resin feel, temple jaisa calm.",
    "Guru purnima pe order kiya — ghar mein mandir wali feeling.",
    "Evening aarti ke baad lagana — mann shaant rehta hai.",
    "Father ko retirement gift diya — unhone kaha cotton kurta par teen din baad bhi halka sa tha.",
    "Navgraha prayer ke baad lagaya — saans dheere ho jati hai, yahi chahiye tha.",
    "Friend ne diya try karne ko — ab har graha remedy din lagati hoon.",
    "Varanasi yatra se liya — ghar aake bhi mandir ki yaad dilata hai.",
    "Incense ke baad lagana — puja room ka poora ritual complete lagta hai.",
    "Kurta collar par zyada tikta hai skin se — fabric hold puja ke liye useful.",
    "Chai aur yeh subah ki duo hai ab — mood shift subtle par real.",
    "Nani ne kaha pehle bhi aise attar lagate the — purani warmth, nayi bottle.",
    "Meditation se pehle do boond — cushion ke paas baithna easy.",
    "Honest review: instant wow nahi, slow attachment hai — doosre week se samajh aaya.",
    "Kid ne kaha ghar achha smell kar raha — rare compliment.",
    "Baarish ke din terrace puja — monsoon ritual ban gaya.",
    "Shaam ko journal likhte waqt — focus thoda better lagta hai.",
    "Husband usually ignore karta hai scent — iske baad poocha kya badla.",
    "Sensitive skin — week trial, no rash.",
    "Family puja mein sab ne notice kiya — subtle, sabko pasand.",
    "Repeat customer — teen bottle, sab consistent.",
    "Pehle week unsure; ab bina puja adhoori lagti hai.",
    "Evening walk ke baad lagati hoon — ghar mein soft trail.",
    "Mast lagta hai Sunday ko — chai, koi jaldi nahi.",
    "Guru dakshina mein guru ji ko diya — appreciate kiya.",
    "Heat mein bhi overwhelm nahi karta — halka dab sufficient.",
    "Puja thali ready karte waqt lagana ritual cue ban gaya.",
    "Night owl hoon — evening aarti ke baad calm deta hai.",
    "Morning sunlight mein lagane ka alag maza hai.",
    "Diwali week daily puja mein — diya ke saath warm blend.",
    "Grandmother ki attar yaad dilayi — wahi warmth.",
]

PLANET_E = [
    "grounded feel milti hai, bilkul loud nahi.",
    "diya smoke ke saath blend achha lagta hai, clash nahi.",
    "temple jaisa calm — alcohol perfume se zyada shaant.",
    "sharp start, baad mein creamy wood — puja ke baad perfect.",
    "dry-down warm aur grounded rehta hai.",
    "miracle claim nahi — practical peaceful ritual helper.",
    "opening minute thoda sharp; dry-down hi asli story hai.",
    "pulse par do drop kaafi puja ke liye — bottle economical.",
    "honest drawback: wedding hall mein projection kam — ghar mandir ke liye ideal.",
    "subah 5 baje uth ke puja — discipline easier lagti hai.",
    "partner ko bhi pasand aaya puja ke baad ghar ki smell.",
    "ekdam subtle — paas wale poochte hain, door se announce nahi.",
    "premium bottle weight — pour controlled, waste nahi.",
    "festival gift diya maa ko — roz subah mandir mein lagati hain.",
    "shaant, grounded, resinous — exactly planet attar jaisa hona chahiye.",
    "sticky nahi lagta — clean dry-down, grease feel nahi.",
    "Sunday reset: ghar saaf, diya, attar — simple shaanti.",
    "batch do teen same warm wood — trust build hua.",
    "mandir jaate waqt settled feel milta hai.",
    "night aarti ke baad — sleep se pehle mann calm.",
    "worth it for daily spiritual practice — not party scent.",
    "pehli bottle month chali light use pe — quality consistent.",
    "honest 4 star feel — opening sharp mere taste ko; dry-down ne rukne diya.",
    "jyotish consultation ke baad order — remedy feel without superstition drama.",
    "office ke baad nahi — sirf shaam ki puja ke liye. Us context mein perfect.",
    "compliment nahi chahiye tha; shaanti chahiye thi — mil gayi.",
    "breath slow ho jati hai chai ke baad morning puja staple.",
    "honest review: costume jewellery nahi, sincere ritual scent.",
    "natural wood-resin smell se booklet ki baat believable lagi.",
]

CHAKRA_O = [
    "Yoga class ke baad shower ke baad lagati hoon.",
    "Meditation se pehle neck aur wrist par halka sa.",
    "Evening self-care routine mein add kiya — mann settle hota hai.",
    "Breathwork session ke liye quiet scent chahiye tha.",
    "Massage therapist ne suggest kiya mindful oils try karne ko.",
    "Sunday slow morning — journal, chai, aur yeh.",
    "Partner ne self-care gift diya — pleasantly surprised.",
    "Initially sceptical about chakra marketing.",
    "Anand Rasa workshop attend kiya — sample se convert hui.",
    "Retreat week mein sirf yeh carry kiya — kaafi tha.",
    "Before bed gentle routine — phone band, dim light, few drops.",
    "Morning yoga nidra prep — cushion ke paas scent anchor.",
    "Honest — medical cure nahi dhoondh rahi thi, calm chahiye tha.",
    "Sensitive skin — alcohol-free week trial pass.",
    "Repeat restock — third bottle same gentle character.",
    "WFH stress din — shaam ko unwind helper.",
    "Mom ne Vishuddha line recommend kiya — throat chakra focus.",
    "Body massage oil ke saath mix kiya — spa jaisa feel ghar pe.",
    "4 star: opening thoda sharp mere liye, dry-down perfect.",
    "Kid exam season — household calmer feel (placebo ho sakta hai).",
    "First chakra oil — exploring rest of line now.",
    "Puja nahi, personal wellness ritual ke liye.",
    "Therapist ne grounding scent suggest kiya — yeh fit laga.",
    "Monsoon blues din — balcony sit ke saath.",
    "Gift sister ko new mom self-care box mein.",
    "Honest drawback: small bottle daily massage users ke liye.",
    "Incense alag, yeh skin ritual ke liye — dono complementary.",
    "Instagram wellness reel se dekha — not gimmicky.",
    "Mann halka — subjective, par kaam karta hai mere liye.",
    "Evening walk ke baad — transition home to calm.",
    "Repeat must for yoga mornings.",
    "Sach bolu, ritual feel real hai — marketing slide deck nahi.",
    "Headache prone — no trigger, important for me.",
    "Premium packaging — pour controlled, waste nahi.",
]

CHAKRA_E = [
    "breath feels easier during five-minute sit.",
    "shoulder tension kam feel after long desk day.",
    "mann zyada settled before meditation — distraction kam.",
    "evening calm without making me sleepy too early.",
    "massage ke baad skin par gentle, not greasy.",
    "yoga mat ke paas baithna natural lagta hai.",
    "not medical — self-care yes, cure claims no.",
    "subtle enough that roommate doesn't complain.",
    "dry-down soft wood-floral — overpower nahi.",
    "week two se habit ban gayi — missing it feels off.",
    "honest placebo ho sakta hai par routine achha lagta hai.",
    "opening sharp 10 minute, phir creamy calm.",
    "sensitive neck area — no irritation.",
    "repeat purchase because consistency achhi rahi.",
    "journal hour ke saath match karta hai.",
    "not for office or gym — personal quiet time only.",
    "gift recipient ne thank you voice note bheja.",
    "4 star: wish bigger size for body massage.",
    "coconut oil layer se longevity thodi badhi.",
    "mann shaant — exactly subjective calm I wanted.",
    "teacher ne backstage notice kiya — subtle compliment.",
    "night routine mein phone ke baad lagana cue hai.",
    "worth it as mindful routine helper, not miracle oil.",
    "fabric par faint trace morning tak — pleasant.",
    "honest review: believer or sceptic, peaceful scent.",
    "first oil attar for wellness — gateway to line.",
    "heat mein behave kiya — no overwhelming cloud.",
    "kaafi acha laga evening relaxation ke liye.",
]

ZODIAC_O = [
    "Birthday month mein khud ko gift — rashi ke hisaab se pick kiya.",
    "Sister ne Leo friend ko gift — personality match laga unko.",
    "Astrology club meetup pe sab ne apna sign try kiya.",
    "Honestly pehle zodiac perfumes gimmick lagte the.",
    "Wedding guest outfit ke saath subtle signature chahiye tha.",
    "Daily wear ke liye loud designer chhod ke yeh try kiya.",
    "Cousin chart reading ke baad matching scent order kiya.",
    "First zodiac attar — exploring whole wheel now.",
    "Partner ko anniversary pe sun sign gift — loved it.",
    "Office mein subtle trail — elevator safe tested.",
    "Instagram astrology meme page se brand discover hui.",
    "Repeat restock — same sign, consistent batch.",
    "Humid Mumbai wedding — behaved better than expected.",
    "4 star: opening sharp, dry-down saves for daily wear.",
    "Sensitive skin month-long trial — no rash.",
    "Friend ne poocha kya lagaya — soft compliment mila.",
    "Travel bottle purse mein — reapply lunch ke baad.",
    "Not destiny changer — personality scent fun hai.",
    "Collector mood — trying different signs for family.",
    "Festive brunch — rashi talk starter ban gaya.",
    "Mujhe strong perfumes pasand nahi — yeh balanced laga.",
    "Evening dinner — one dot enough.",
    "Gift wrap premium thi — unboxing se scent tak thoughtful.",
    "Honest drawback: non-believers ko story samjhana padta hai.",
    "Fabric saree par faint hold — nice surprise.",
    "Kaafi unique identity feel without shouting.",
    "First Anand Rasa zodiac — hooked on concept.",
    "Monsoon extra dab once — normal for attar.",
    "Kid ne bola mummy smells nice — cute.",
    "Sach bolu, gifting ke liye best category.",
    "Chart on fridge, scent on dresser — fun alignment.",
    "Repeat fourth bottle same sign — loyalty.",
    "Heat mein overwhelm nahi — halka sufficient.",
    "Worth it for astrology enthusiasts in family.",
    "Honest review: sceptic friendly enjoyment.",
]

ZODIAC_E = [
    "compliment mila — not loud, just noticed.",
    "daily signature ban gaya — office safe.",
    "personality match feel — cheesy par fun.",
    "subtle confidence milti hai morning routine mein.",
    "partner ne sign guess kiya correctly — cute moment.",
    "dry-down warm, not sugary headache sweet.",
    "gift recipient instantly connected with symbolism.",
    "6 hours realistic on cotton kurta.",
    "not changing destiny — just smelling good with meaning.",
    "elevator test pass — no perfume cloud.",
    "opening minute bright, settles nicely.",
    "worth exploring other signs in lineup.",
    "honest 4 star: wish mini discovery set all signs.",
    "alcohol perfume se switch — gentler on skin.",
    "wedding photos mein scent memory tied — bonus.",
    "repeat purchase festival rush mein — delivery ok.",
    "astrology lover friend convert ho gayi customer.",
    "fabric hold decent for oil attar.",
    "heat behave kiya — one extra dab max.",
    "premium feel without designer price guilt.",
    "subtle trail — colleague asked after lunch not morning.",
    "gift story makes it more than just fragrance.",
    "mann khush — subjective, par smile real.",
    "honest not for puja — personal wear scent.",
    "kaafi balanced for everyday Indian weather.",
    "bottle shelf pe display worthy — cap tight.",
    "second bottle already — says enough.",
    "worth rashi gift for birthday month.",
]

PERFUME_O = [
    "Office Monday presentation ke liye.",
    "Client lunch ke baad elevator mein safe rehna tha.",
    "Airport travel week — one bottle carry-on.",
    "WFH video calls — subtle professional chahiye tha.",
    "Commute metro se office — close quarters test.",
    "Brunch outing with friends — not overpowering.",
    "Humid wedding guest outfit — behaved well.",
    "Evening dinner date — one neck dot.",
    "Business trip three days — consistent character.",
    "Mujhe strong perfumes pasand nahi — office friendly dhoondh rahi thi.",
    "Repeat restock — second bottle office drawer mein.",
    "Sensitive skin — month trial, no irritation.",
    "Colleague ne poocha kya lagaya — soft compliment.",
    "4 star: opening sharp first 15 min, then settles.",
    "Travel leak test pass — cap tight.",
    "First Anand Rasa perfume line — impressed.",
    "Heat wave week — one extra dab, still ok.",
    "Honestly daily wear workhorse ban gaya.",
    "Sach bolu office safe tag accurate hai.",
    "Fabric kurta par evening tak faint trace.",
    "Gift husband ko — uses on meeting days.",
    "Instagram discovery — skeptical order, pleased.",
    "Monsoon humidity — still wearable.",
    "Kid ne bola papa smells nice — funny.",
    "Premium bottle weight — controlled pour.",
    "Festive week bhi office wear ke liye use kiya.",
    "Not party bomb — professional subtle.",
    "Repeat third bottle — consistency key.",
    "Honest drawback: wish travel size refill.",
    "Compliment after lunch not during meeting — perfect.",
    "First attar for office — won't go back alcohol.",
    "Kaafi weekday staple now.",
    "Evening walk ke baad bhi not cloying.",
    "Worth premium for daily professional wear.",
    "Honest 5 star office driver potential.",
]

PERFUME_E = [
    "two dots enough — no perfume cloud.",
    "meeting room safe — nobody winced.",
    "6 hours realistic longevity on shirt.",
    "compliment mila staircase par — subtle.",
    "consistent character day one to day three trip.",
    "elevator safe verified — colleague feedback positive.",
    "dry-down professional, not sweet teenage.",
    "humid day par extra dab once — manageable.",
    "opening sharp then creamy — saves the wear.",
    "sensitive skin ok — neck and wrist daily.",
    "travel bottle didn't leak — handbag safe.",
    "worth switching from alcohol department store.",
    "fabric hold better than expected on cotton.",
    "honest 4 star: wish slightly bigger bottle.",
    "heat mein behave — not overwhelming.",
    "office drawer staple now.",
    "partner uses on client days too — shared bottle.",
    "modern soul, attar format — accurate tag.",
    "repeat because batch same last two orders.",
    "subtle trail — noticed when close only.",
    "premium feel without shouting in open office.",
    "worth daily wear price per use low.",
    "mann confident — subjective par meetings easier feel.",
    "honest not for puja — work scent.",
    "kaafi balanced for Indian office AC.",
    "second bottle ordered before first finished.",
    "gift recipient uses on interview day — got job (coincidence!).",
    "sach bolu, compliments genuine not forced.",
]

# Shorter pools for secondary axes — still experience-first

def _secondary(axis: str, hooks: list[str], experiences: list[str]) -> list[str]:
    variants: list[str] = []
    lead_ins = [
        "", "Honestly — ", "Unexpectedly — ", "Pehli baar — ", "Repeat buy — ",
        "4 star note — ", "Second bottle — ", "Festival week — ", "Gift story — ",
        "After two weeks — ", "My mother — ", "My wife — ", "My father — ",
        "We — ", "Bought this — ", "Initially unsure — ", "Didn't expect — ",
        "Tried during — ", "Been using — ", "Kept it — ",
    ]
    for h in hooks:
        for lead in lead_ins:
            text = f"{lead}{h}".strip()
            if text not in variants:
                variants.append(text)
            if len(variants) >= 96:
                break
        if len(variants) >= 96:
            break
    openings = variants[:96]
    return build_reviews(axis, openings, experiences, count=95)


def build_love() -> list[str]:
    return _secondary("love", [
        "Anniversary dinner pe pehli baar lagaya.",
        "Date night — candlelit table, subtle scent chahiye tha.",
        "Wife ko surprise gift — romantic without being childish sweet.",
        "Proposal night pocket mein rakha — memory tied now.",
        "Honeymoon bag mein pack kiya.",
        "Wedding sangeet outfit ke saath.",
        "Valentine order — partner noticed immediately.",
        "First romantic attar — alcohol perfume se switch.",
        "Partner ne compliment diya dinner par.",
        "Sensitive skin — intimate wear trial pass.",
        "Repeat restock — our shared bottle.",
        "4 star: projection low for dance floor, dinner perfect.",
        "Honestly expectation se better — not headache sweet.",
        "Fabric saree par faint romantic trace.",
        "Gift sister ko newly engaged — she cried happy.",
        "Evening walk holding hands — subtle trail.",
        "Not puja scent — clearly evening romance.",
        "Kaafi soft floral warmth — sophisticated.",
        "Travel size wish — otherwise perfect.",
        "Sach bolu romantic feel real, not brochure.",
    ], [
        "partner noticed without me saying anything.",
        "table neighbour compliment — subtle win.",
        "intimate lagta hai, not club loud.",
        "rose feel sophisticated, not candy.",
        "skin par gentle — no irritation.",
        "evening glow subjective par smile real.",
        "shared bottle ban gaya household mein.",
        "repeat anniversary tradition start ho sakta hai.",
        "honest not love potion — nice scent.",
        "worth romantic gifting.",
        "dry-down warm — dinner length cover.",
        "heat mein one extra dab ok.",
        "compliment rare for me — happened.",
        "alcohol free — partner sensitive nose ok.",
        "mann khush — cheesy par true.",
    ])


def build_stress() -> list[str]:
    return _secondary("stress", [
        "Office ke baad sofa par baithte hi lagati hoon.",
        "Sleep se pehle night routine ka part.",
        "Exam week household — calm chahiye tha.",
        "Yoga unwind ke liye — not medical claim.",
        "Sunday reset — ghar shaant karne ritual.",
        "Commute ghar aake — transition helper.",
        "Therapy evenings — comfort scent.",
        "Monsoon blues din — balcony sit.",
        "Desk burnout week — small self-care.",
        "Honest — cure nahi, unwind yes.",
        "Repeat bedside staple — third bottle.",
        "4 star: panic moments ke liye subtle only.",
        "Kid exam season — household calmer feel.",
        "WFH blur days — evening cue.",
        "Partner gift — thank you note mila.",
        "Sensitive skin wrist test pass.",
        "Not antidepressant — helper word accurate.",
        "Chai ke saad — mann halka.",
        "Journal before bed — scent anchor.",
        "Sach bolu shaam ka unwind real.",
    ], [
        "shoulder tension kam feel subjective par helpful.",
        "breath easy lagta hai five minutes mein.",
        "mann halka — placebo ho sakta hai, par kaam karta hai.",
        "headache trigger nahi — priority thi.",
        "pillow edge par faint — not overpower.",
        "repeat because routine attach ho gaya.",
        "honest not medical — self care yes.",
        "dry-down soft — sleep nearby ok.",
        "opening fades quick — night friendly.",
        "worth evening ritual price.",
        "4 star: wish bigger bottle.",
        "partner bhi use karta hai stress din.",
        "not for morning rush — evening only.",
        "kaafi shaant dry-down.",
        "first stress line — keeping.",
    ])


def build_luxury() -> list[str]:
    return _secondary("luxury", [
        "Gallery opening ke liye — refined not loud.",
        "Boardroom dinner — elegant trail chahiye tha.",
        "Resort stay weekend — special occasion.",
        "Black tie event — one dot enough.",
        "Heirloom gift father ko — uses sparingly.",
        "Collector shelf pe display — sometimes wear.",
        "Anniversary splurge — worth it feel.",
        "Client gifting — premium presentation.",
        "Honestly not daily budget — occasion scent.",
        "Repeat annual treat — birthday splurge.",
        "4 star: price high, quality matches mostly.",
        "Sensitive skin event wear ok.",
        "Partner compliment mila — sophisticated.",
        "Velvety heart feel — not brochure word, experience.",
        "Travel carry — leak test pass.",
        "First luxury line — impressed.",
        "Wine pairing dinner — subtle complement.",
        "Not designer flex — quality flex.",
        "Kaafi classy feel photos mein bhi.",
        "Sach bolu special occasion justified.",
    ], [
        "compliment mila without announcing entrance.",
        "dry-down refined — hours later still elegant.",
        "bottle weight premium — pour controlled.",
        "worth splurge once a year.",
        "fabric hold impressive evening length.",
        "heat mein behave — event AC ok.",
        "gift recipient converted — ordered own.",
        "honest drawback: small bottle big price.",
        "repeat because memorable occasions tied.",
        "not office daily — gala scent.",
        "opening bright settles royal — 4 star opening.",
        "sensitive skin no rash event night.",
        "partner stole borrow for wedding — funny.",
        "worth premium packaging alone half.",
        "mann confident — subjective premium feel.",
    ])


def build_spiritual() -> list[str]:
    return _secondary("spiritual", [
        "Temple morning visit se pehle lagati hoon.",
        "Puja thali ready karte waqt — ritual cue.",
        "Evening aarti ke baad — ghar shaant.",
        "Pilgrimage trip carry — mandir memory.",
        "Diya lighting ke saath — complementary.",
        "Chanting hour — breath slow hoti hai.",
        "Retreat week only spiritual scents.",
        "Guru dakshina gift — appreciated.",
        "Home mandir daily — never office.",
        "Sacred thread day — personal meaning.",
        "Repeat mandir staple — third bottle.",
        "4 star: projection zero — temple ok.",
        "Honest not miracle — ritual helper.",
        "Frankincense-sandal vibe believable.",
        "Kid calm during puja — bonus.",
        "Family puja collective — subtle notice.",
        "Sensitive skin daily puja fine.",
        "Incense ke baad lagana — complete ritual.",
        "Kaafi authentic devotional warm feel.",
        "Sach bolu peaceful puja helper.",
    ], [
        "diya smoke ke saath blend — no clash.",
        "mann shaant — saans dheere.",
        "temple cotton vibe ghar laata hai.",
        "ghar mein shanti feel guests notice.",
        "worth puja-only context.",
        "dry-down warm grounded.",
        "not party scent ever.",
        "repeat festival season stock.",
        "honest spiritual not superstitious drama.",
        "fabric kurta faint trail puja ke baad.",
        "opening resin sharp, settles sacred.",
        "gift pandit ji — used.",
        "worth devotional respect premium.",
        "headache no trigger — incense sensitive.",
        "first spiritual attar keeping.",
    ])


def build_bestseller() -> list[str]:
    return _secondary("bestseller", [
        "Pehla Anand Rasa order — bestseller se start kiya.",
        "Friend referral — unka staple mera ab.",
        "Festival rush buy — delivery time ok.",
        "Cart add-on curiosity — pleasantly stuck.",
        "Family recommendation — mom's pick.",
        "Office colleague tip — tried, agreed.",
        "Anniversary curious splurge — converted.",
        "Repeat restock fourth bottle.",
        "Instagram reel skeptical — hype justified feel.",
        "Honestly gateway product — line explore kar raha.",
        "4 star: personal taste vary, quality solid.",
        "Sensitive skin week ok.",
        "Gift safe — recipient reordered.",
        "Not unique — reliably good daily.",
        "Kaafi fan favorite samajh aaya.",
        "Travel bottle tried — leak ok.",
        "Heat behave — daily humid ok.",
        "Worth trying new brand intro.",
        "Dependable hold — boring good way.",
        "Sach bolu worth hype mostly.",
    ], [
        "consistent quality do teen orders.",
        "balanced daily wear — crowd pleaser.",
        "gift recipient reordered — best signal.",
        "repeat because never disappoints.",
        "honest not most unique — dependable.",
        "fabric hold decent.",
        "compliment occasional — subtle.",
        "worth first purchase confidence.",
        "4 star: wish more size options.",
        "partner bhi use — shared.",
        "office and home both ok.",
        "mann satisfied — low risk buy.",
        "festival gift safe choice.",
        "first bottle month — reorder already.",
        "gateway to chakra line next.",
    ])


def build_gift() -> list[str]:
    return _secondary("gift", [
        "Birthday hamper — unboxing video bheja recipient ne.",
        "Wedding return gift bulk — sabko pasand.",
        "Mother's day box — maa ne roz use shuru.",
        "Housewarming — neighbours noticed packaging.",
        "Anniversary box — partner emotional ho gaya.",
        "Festive hamper Diwali — ribbon quality achhi.",
        "Bridal trousseau add-on — tasteful.",
        "Thank you gift boss ko — professional safe.",
        "Discovery kit — sister convert customer.",
        "Honestly packaging half the joy.",
        "Premium reveal slow open — luxury feel.",
        "4 star: shipping box heavy — contents safe.",
        "Corporate repeat third year — same hamper.",
        "Recipient converted — ordered full size.",
        "Kaafi thoughtful — not generic basket.",
        "Keepsake box reuse hua decor mein.",
        "Gift wrap premium — photo worthy.",
        "Not discovery gimmick — real products inside.",
        "Sach bolu gift memory lasting.",
        "Repeat gifter loyal — annual list.",
    ], [
        "unboxing wow mila — video proof.",
        "presentation premium thi — ribbon, tissue, card.",
        "hamper star product highlight clear.",
        "recipient thank you call — rare.",
        "worth premium gifting price.",
        "festive feel without cheap chocolate vibe.",
        "honest shipping weight high — survived.",
        "reorder from recipient — success metric.",
        "luxury presentation matched fragrance quality.",
        "4 star: wish greeting card customize option.",
        "family photo unboxing — memory.",
        "not corporate generic — curated feel.",
        "worth Diwali corporate list.",
        "recipient uses daily — not shelf dust.",
        "mann khush gift giver — smile real.",
    ])


def build_apsara() -> list[str]:
    return _secondary("apsara", [
        "Kathak rehearsal backstage — subtle stage scent.",
        "Sangeet night — heritage outfit match.",
        "Classical recital — teacher compliment.",
        "Bridal getting ready — photographer noticed.",
        "Heritage wedding — not loud dance floor.",
        "Photo shoot — elegant trail.",
        "Poetry evening — artistic vibe.",
        "Dance competition day — grace subtle.",
        "Art collector gift — appreciated mythology.",
        "Not daily office — performance days.",
        "4 star: long performance reapply once.",
        "Repeat recital season — third bottle.",
        "Sensitive skin stage makeup nearby ok.",
        "First apsara line — impressed.",
        "Honest niche appeal — right buyer loves.",
        "Premium artistic gift — worth.",
        "Sach bolu graceful — name fits.",
        "Temple festival performance — appropriate.",
        "Kaafi elegant stage presence.",
        "Worth mythology lover friend.",
    ], [
        "teacher compliment backstage — subtle.",
        "divine floral not loud audience.",
        "heritage bloom feel photos.",
        "stage grace without overpower.",
        "dry-down soft hours — recital length.",
        "gift hit mythology nerd friend.",
        "not gym scent — art days.",
        "fabric costume faint hold.",
        "worth performance ritual.",
        "honest not casual daily.",
        "opening bright settles elegant.",
        "repeat because recital memory tied.",
        "4 star: wish mini for purse reapply.",
        "mann artistic — subjective boost.",
        "first cultural program wear success.",
    ])


def build_astrology() -> list[str]:
    return _secondary("astrology", [
        "Chart reading day — scent mood match fun.",
        "Astrologer visit ke baad order — remedy feel light.",
        "Muhurat shopping — impulse meaningful.",
        "Retrograde season joke gift — friend loved.",
        "Couple compatibility scent pairing — cute experiment.",
        "Remedy box add-on — actually use hota hai.",
        "New year forecast party — rashi talk starter.",
        "Journaling stars theme — scent anchor.",
        "Belief optional — enjoyment mandatory.",
        "4 star: jargon confusing, scent great.",
        "Gift astro friend — instant hit.",
        "Honestly sceptic friendly.",
        "Repeat annual ritual buy.",
        "Not destiny promise — fun ritual.",
        "Kaafi vedic respectful tone.",
        "Premium remedy presentation.",
        "Worth ritual set bundle.",
        "Sach bolu astrology lover gift.",
        "Planet zodiac umbrella works.",
        "First astro-themed attar — keeping.",
    ], [
        "chart day scent memory tied.",
        "remedy wear feel without drama.",
        "gift friend cried happy — knows signs.",
        "subtle cosmic calm — cheesy word ok.",
        "repeat because ritual attach.",
        "honest not medical miracle.",
        "compliment at astro meetup.",
        "dry-down warm grounded.",
        "worth muhurat impulse.",
        "4 star: booklet wish simpler.",
        "partner enjoys couple pairing game.",
        "not office — ritual wear.",
        "mann playful — belief optional.",
        "fabric hold evening prayer ok.",
        "first Anand Rasa astro line.",
    ])


def build_mood() -> list[str]:
    return _secondary("mood", [
        "Rainy afternoon balcony — cozy lift.",
        "Sunlit balcony coffee — slow Sunday.",
        "Journal hour — scent match playlist.",
        "Creative afternoon painting — focus helper.",
        "Post workout calm stretch — not gym scent cloud.",
        "Solo drive sunset — window half open.",
        "Self care evening — bath ke baad.",
        "Not antidepressant — mood helper accurate.",
        "4 star: tag vague, scent good.",
        "Repeat monsoon bottle — rainy day specialist.",
        "Honest afternoon treat — smile real.",
        "Sensitive skin ok.",
        "Partner likes rainy day me too now.",
        "Kaafi acha rainy calm.",
        "Premium self care splurge.",
        "Worth mood experiment.",
        "Sach bolu feel-good dry-down.",
        "Not magic happiness — nice moment.",
        "First mood line — curious more.",
        "Gift sister going through rough week.",
    ], [
        "cozy lift subtle — not overpower.",
        "mood shift small par real.",
        "rainy day specialist tag fits.",
        "balcony breeze match nice.",
        "journal focus thoda better feel.",
        "repeat because rainy season attach.",
        "honest placebo maybe — works.",
        "dry-down soft wood.",
        "4 star: summer less use.",
        "worth self care price.",
        "mann lighter — subjective.",
        "not office — personal moment.",
        "fabric shawl faint trace.",
        "gift recipient texted thanks.",
        "first mood purchase pleased.",
    ])


def build_festival() -> list[str]:
    return _secondary("festival", [
        "Diwali prep week — ghar warm sacred feel.",
        "Navratri night — family gathering comfortable.",
        "Durga puja pandal visit — subtle wear ok.",
        "Onam morning — tradition note.",
        "Ganesh visarjan day — emotional calm scent.",
        "Christmas eve family — cross-cultural gift hit.",
        "Pongal harvest — earthy warm fit.",
        "Baisakhi fair — festive not loud.",
        "Repeat annual stock — third Diwali.",
        "4 star: sweet food environment compete.",
        "Year round less — festival yes.",
        "Guests noticed brand — positive.",
        "Puja plus festive wear — combo.",
        "Kaafi festive hold — gathering ok.",
        "Honest not firecracker smell.",
        "Premium festive wrap.",
        "Sach bolu celebration glow.",
        "Gift cousins hamper — reorder.",
        "First festival line — tradition tied.",
        "Worth festival collection explore.",
    ], [
        "diya pairing perfect Diwali.",
        "family room celebration scent — not loud.",
        "guests comfortable — no perfume cloud.",
        "tradition feel subtle.",
        "repeat annual — memory tied.",
        "honest niche festival tags.",
        "worth weather pairing humid ok.",
        "4 star: off-season shelf storage.",
        "mann festive — smile real.",
        "fabric kurta hold puja length.",
        "gift hit festive season.",
        "not daily office — celebration.",
        "opening bright settles warm.",
        "partner family approved.",
        "first Navratri with this — keeping.",
    ])


def build_daily() -> list[str]:
    return _secondary("daily", [
        "Office commute — one dot tested.",
        "WFH desk all day — subtle.",
        "College campus — not overwhelming.",
        "School pickup run — quick fresh feel.",
        "Market errands — casual daily.",
        "Lunch break walk — compliment once.",
        "Metro ride close quarters — safe.",
        "Weekday uniform scent — boring reliable good.",
        "Evening walk — transitions day night.",
        "Repeat monthly restock — staple.",
        "4 star: weekend want bolder.",
        "Elevator safe tested — pass.",
        "Cost per wear low — bottle lasts.",
        "Heat extra dab once — normal.",
        "First daily attar success.",
        "Honest boring reliable — compliment.",
        "Sensitive skin daily ok.",
        "Partner shares office days.",
        "Kaafi weekday staple.",
        "Sach bolu office safe.",
    ], [
        "elevator safe — no cloud.",
        "desk friendly — neighbour ok.",
        "subtle trail meeting safe.",
        "daily driver confirmed month two.",
        "6 hours shirt realistic.",
        "repeat because dependable.",
        "4 star: wish travel refill.",
        "humid behave ok.",
        "compliment rare — happened stairwell.",
        "not puja — daily wear.",
        "fabric cotton hold decent.",
        "opening sharp settles — office ok.",
        "worth daily tag price.",
        "mann routine — autopilot wear.",
        "first Anand Rasa daily — pleased.",
    ])


def build_meditation() -> list[str]:
    return _secondary("meditation", [
        "Morning sit — cushion calm real.",
        "Vipassana day — silent depth.",
        "Breathwork class — anchor scent.",
        "Silent retreat week — only this carried.",
        "Zafu session home — quiet room.",
        "Mantra hour — chant rhythm match.",
        "Sunrise sit terrace — peaceful.",
        "Temple garden memory — ghar replicate.",
        "Yoga nidra prep — not sleep pill.",
        "Candle meditation — complementary.",
        "Never bought for office — sit only.",
        "4 star: silence purists scent optional.",
        "Headache no trigger — critical.",
        "Teacher approved backstage retreat.",
        "Repeat retreat pack — third order.",
        "Honest not enlightenment juice.",
        "Kaafi zen wood vibe.",
        "Premium retreat tool worth.",
        "Sach bolu still mind helper.",
        "First meditation attar — keeping.",
    ], [
        "breath anchor subtle — distraction kam.",
        "cushion calm believable.",
        "silent depth no shout.",
        "focus aid placebo ok.",
        "quiet room scent — low projection.",
        "repeat retreat attach.",
        "honest not miracle — sit helper.",
        "dry-down wood incense adjacent.",
        "4 star: daily wear wrong context.",
        "worth meditators try.",
        "opening fades — sit friendly.",
        "partner uses morning sit too.",
        "fabric faint — not needed.",
        "mann settled — five minutes.",
        "first sit scent success.",
    ])


def build_premium() -> list[str]:
    return _secondary("premium", [
        "Flagship store visit — consult pick.",
        "Collector buy — display sometimes wear.",
        "Heirloom gift father — uses milestone days.",
        "Spa parallel — massage oil mix.",
        "Limited batch curiosity — depth noticeable.",
        "Five star stay — packed one dot.",
        "Milestone celebration — splurge justified feel.",
        "Art preview evening — refined compliment.",
        "Repeat annual treat — birthday.",
        "4 star: price premium justified mostly.",
        "Special occasion not daily — accurate.",
        "Worth splurge once.",
        "Kaafi rare bloom character.",
        "Honest drawback small bottle big price.",
        "Sensitive skin gentle.",
        "Partner stole for anniversary — funny.",
        "Not casual overspend guilt sometimes.",
        "Sach bolu house best tier.",
        "First premium line — exploring more.",
        "Gift CEO client — safe premium.",
    ], [
        "batch depth noticeable vs entry line.",
        "collector pride — numbered feel.",
        "compliment gala night.",
        "dry-down hours elegant.",
        "worth flagship visit pick.",
        "honest not daily driver.",
        "repeat annual — tradition splurge.",
        "4 star: guilt price sometimes.",
        "fabric hold impressive.",
        "opening resin rich settles velvet.",
        "gift hit premium lover.",
        "mann special — occasion boost.",
        "not office — gala scent.",
        "travel leak ok — cap premium.",
        "first premium pleased.",
    ])


def build_limited() -> list[str]:
    return _secondary("limited", [
        "Drop day order — waitlist win feel.",
        "Numbered bottle — shelf pride.",
        "Launch party sample — full bottle bought.",
        "Early access email — impulse ok.",
        "Seasonal batch — character unique.",
        "Anniversary edition gift self.",
        "Sold out restock alert — grabbed.",
        "VIP club early — worth wait?",
        "Collab release — collector mood.",
        "4 star: FOMO pricing high.",
        "Display sometimes wear — honest.",
        "Not resale flip — personal wear.",
        "Repeat waitlist subscriber.",
        "Kaafi drop day story dinner.",
        "Honest marketing anxiety real.",
        "Premium numbered presentation.",
        "Worth collector joy.",
        "Exclusive character real not hype only.",
        "Sach bolu limited pour special.",
        "First limited — hooked danger.",
    ], [
        "batch number pride — photo taken.",
        "exclusive dry-down vs core line.",
        "wait worth — mostly yes.",
        "4 star: price FOMO tinged.",
        "wear not just display — actually use.",
        "compliment rare — special wear.",
        "repeat waitlist — annual ritual.",
        "honest hype anxiety — product delivers.",
        "opening unique settles prized.",
        "gift collector friend — screamed.",
        "not daily — occasion pull.",
        "fabric hold special night.",
        "mann excitement — unboxing memory.",
        "worth limited tax once.",
        "first drop success.",
    ])


def build_seasonal() -> list[str]:
    return _secondary("seasonal", [
        "Monsoon terrace sit — humidity behave surprise.",
        "Summer wedding guest — light enough.",
        "Winter shawl season — depth beautiful.",
        "Hill station trip — cool air sharper.",
        "Coastal monsoon — extra dab once.",
        "December wedding — festive warm.",
        "Spring picnic — soft not cloying.",
        "Mango season ghar — nostalgic warm.",
        "Autumn travel — suitcase staple.",
        "Diwali week — seasonal ritual.",
        "4 star: monsoon extra dab.",
        "Off season storage note — fair.",
        "Repeat monsoon annual.",
        "Kaafi climate match tag.",
        "Honest niche seasonal — right buyer.",
        "Worth weather pairing experiment.",
        "Sach bolu monsoon user loyal.",
        "Summer light surprise oil attar.",
        "Winter evening depth — shawl perfect.",
        "First seasonal — curious full line.",
    ], [
        "humidity behave ok — one extra dab.",
        "cool air sharper scent — hill trip.",
        "monsoon hold surprising.",
        "season shift match believable.",
        "repeat same season next year.",
        "4 star: off-season less use.",
        "worth climate tag.",
        "dry-down weather adaptive feel.",
        "gift monsoon lover friend.",
        "not office — season mood.",
        "fabric shawl hold winter.",
        "opening bright summer ok.",
        "mann season memory tied.",
        "honest niche tags.",
        "first seasonal pleased.",
    ])


def build_generic() -> list[str]:
    return _secondary("generic", [
        "Pehli baar attar — skeptical online order.",
        "Cousin wedding discovery — bought own.",
        "Store visit — staff sample convert.",
        "Travel bottle impulse — pleased.",
        "Friend recommended — trust justified.",
        "Festival purchase — first of brand.",
        "Reading reviews then buy — worth.",
        "Instagram discovery — human craft feel.",
        "Repeat exploring collections.",
        "4 star: learning application curve.",
        "Sensitive skin week ok.",
        "Honestly gateway product.",
        "Kaafi acha first impression.",
        "Fabric hold decent surprise.",
        "Worth Anand Rasa intro.",
        "Partner gift — shared now.",
        "Not sure which line — started here.",
        "Sach bolu worth it.",
        "Heat behave — daily potential.",
        "First bottle month — reorder.",
    ], [
        "gently surprised quality.",
        "warm balanced — not harsh.",
        "elegant bottle weight premium.",
        "alcohol free gentle skin.",
        "repeat because curious more lines.",
        "honest learning wrist vs fabric.",
        "compliment once — encouraged.",
        "worth intro price risk low.",
        "4 star: wish clearer guide.",
        "dry-down pleasant hours.",
        "gift safe intro — recipient reordered.",
        "mann curious — explore chakra next.",
        "not puja not office — middle daily.",
        "opening sharp settles — patience.",
        "first Anand Rasa — fan now.",
    ])


def build_incense() -> list[str]:
    return _secondary("incense", INCENSE_O, INCENSE_E)


def build_chakra() -> list[str]:
    return _secondary("chakra", CHAKRA_O, CHAKRA_E)


def build_planet() -> list[str]:
    prefixes = [
        "Mummy ne graha remedy ke liye suggest kiya —",
        "Sunday havan ke din",
        "Astrologer ne morning prayer routine mein add karne ko kaha —",
        "Temple queue mein wait karte waqt",
        "Japa mala ke saath",
        "Pehli baar Navagraha attar liya —",
        "Guru purnima pe order kiya —",
        "Evening aarti ke baad",
        "Father ko retirement gift diya —",
        "Navgraha prayer ke baad",
        "Friend ne diya try karne ko —",
        "Varanasi yatra se laaya —",
        "Incense ke baad lagana",
        "Kurta collar par zyada tikta hai —",
        "Chai aur yeh subah ki duo hai ab —",
        "Nani ne kaha pehle bhi aise attar lagate the —",
        "Meditation se pehle do boond —",
        "Honest review:",
        "Kid ne kaha ghar achha smell kar raha —",
        "Baarish ke din terrace puja —",
        "Shaam ko journal likhte waqt",
        "Husband usually ignore karta hai scent —",
        "Sensitive skin — week trial,",
        "Family puja mein sab ne notice kiya —",
        "Repeat customer —",
        "Pehle week unsure;",
        "Evening walk ke baad",
        "Mast lagta hai Sunday ko —",
        "Guru dakshina mein guru ji ko diya —",
        "Heat mein bhi",
        "Puja thali ready karte waqt",
        "Night owl hoon —",
        "Morning sunlight mein lagane ka alag maza —",
        "Diwali week daily puja mein —",
        "Grandmother ki attar yaad dilayi —",
        "Initially doubtful thi;",
        "Subah 5 baje uth ke puja —",
        "Festival gift diya maa ko —",
        "Office ke baad nahi — sirf shaam ki puja ke liye.",
        "Compliment nahi chahiye tha;",
        "Breath slow ho jati hai",
        "Honest drawback:",
        "Pehli bottle month chali light use pe —",
        "Batch do teen same warm wood —",
        "Mandir jaate waqt",
        "Night aarti ke baad",
        "Worth it for daily spiritual practice —",
        "Jyotish consultation ke baad order —",
        "Planetary remedy box ka best part",
        "Kaafi acha laga pehli baar lagake puja ki.",
        "Slow burn attachment —",
        "Navgraha set se sabse pehle khatam hota hai ghar pe.",
        "Honest review:",
        "Subah 5 baje uth ke",
        "Partner ko bhi pasand aaya",
        "Ekdam subtle —",
        "Premium bottle weight —",
        "Shaant, grounded, resinous —",
        "Sticky nahi lagta —",
        "Sunday reset:",
        "Ghar ke mandir mein diya jalane se pehle",
        "Mujhe honestly expectation nahi thi;",
        "Repeat restock festival rush mein —",
        "Kaafi acha laga",
        "Mann halka ho jata hai",
        "Honest—not for club—prayer",
        "Pehla Anand Rasa order",
        "Fabric test:",
        "Heat mein bhi overwhelm nahi karta —",
        "Puja thali ready karte waqt lagana",
        "Brother ne birth chart ke hisaab se pick kiya —",
        "Retreat week mein sirf yeh carry kiya —",
        "Instagram reel dekhi, skeptical order.",
        "Opening minute thoda sharp;",
        "Family puja mein",
        "Chart reading ke din",
        "Honest—graha remedy sceptic thi;",
        "Repeat customer—teen bottle,",
        "Wedding season mein bhi",
        "Cap tight hai, handbag safe.",
        "Evening walk ke baad lagati hoon —",
        "Sach bolu",
        "Guru dakshina mein",
        "Fabric test: linen kurta par",
        "Initially doubtful thi;",
        "Kid ne kaha ghar",
        "First Anand Rasa order",
        "Baarish ke din",
        "Subtle enough for temple —",
        "Worth premium ritual tool —",
        "Peaceful nights",
        "Birth star gift best type —",
        "Kaafi vedic calm —",
        "Quiet evenings ka default",
        "Gift father ko",
        "Mann shaant —",
        "Honest 5 star",
        "Daily fragrance ritual",
        "Pehle attar try",
        "Gentle hold hours —",
        "Slow routine month habit —",
        "Evening aarti",
        "Honest 4 star:",
        "Temple cotton vibe —",
        "Repeat loyal —",
        "Spiritual alignment note feels real —",
        "Wedding guest ne",
        "Repeat annual homam ke liye",
        "Quiet evenings",
        "Initially unsure;",
        "Cosmic calm cheesy word;",
        "Not for club or office —",
        "Kaafi gentle —",
        "Vedic warmth believable —",
        "Journal likhte waqt",
        "Worth it as a meaningful gift",
    ]
    suffixes = [
        "subah lagana ab habit hai.",
        "lagati hoon grounding ke liye.",
        "use karti hoon chant ke rhythm mein.",
        "warm resin feel mila.",
        "ghar mein mandir wali feeling aati hai.",
        "lagana mann shaant rehta hai.",
        "unhone kaha kurta par teen din baad bhi halka sa tha.",
        "lagaya saans dheere ho jati hai.",
        "ab har graha remedy din lagati hoon.",
        "ghar aake bhi mandir ki yaad dilata hai.",
        "puja room ka poora ritual complete lagta hai.",
        "fabric hold puja ke liye useful hai.",
        "mood shift subtle par real hai.",
        "purani warmth, nayi bottle.",
        "cushion ke paas baithna easy ho jata hai.",
        "instant wow nahi, slow attachment hai.",
        "rare compliment mila.",
        "monsoon ritual ban gaya.",
        "focus thoda better lagta hai.",
        "iske baad poocha kya badla.",
        "no rash — week ok.",
        "subtle, sabko pasand.",
        "teen bottle, sab consistent.",
        "ab bina puja adhoori lagti hai.",
        "ghar mein soft trail rehti hai.",
        "chai, koi jaldi nahi.",
        "appreciate kiya.",
        "halka dab sufficient hai.",
        "ritual cue ban gaya.",
        "evening aarti ke baad calm deta hai.",
        "lagane ka alag maza hai.",
        "diya ke saath warm blend hota hai.",
        "wahi warmth yaad dilayi.",
        "trust build hua brand par.",
        "discipline easier lagti hai.",
        "roz subah mandir mein lagati hain.",
        "us context mein perfect hai.",
        "shaanti chahiye thi — mil gayi.",
        "morning puja staple ban gaya.",
        "wedding hall mein projection kam — ghar mandir ideal.",
        "quality consistent rahi.",
        "settled feel milta hai.",
        "sleep se pehle mann calm.",
        "not party scent — ritual scent.",
        "remedy feel without drama.",
        "yeh use hota hai, stones display pe rehte hain.",
        "week do mein loyal ho gayi.",
        "ghee diya ke saath blend achha.",
        "sincere ritual scent hai.",
        "faint trace subah tak rehti hai.",
        "pleasantly surprised hoon.",
        "delivery time theek, scent same.",
        "puja ki — correct use.",
        "ke baad — shaam ki dua.",
        "scent hai — prayer ke liye.",
        "roz use karte hain.",
        "dry-down warm aur grounded.",
        "explore kar rahi hoon ab line.",
        "subah tak faint trace impressive.",
        "overwhelm nahi karta.",
        "pick kiya — fit laga.",
        "kaafi tha poora week.",
        "worth it laga.",
        "dry-down hi asli story hai.",
        "notice kiya — positive.",
        "casually notice kiya — achha laga.",
        "practical laga, superstitious nahi.",
        "puja routine mein fit.",
        "chhoti luxury detail.",
        "soft trail rehti hai ghar mein.",
        "brochure jaisa nahi — human.",
        "linen par subah tak faint trace.",
        "trust build hua.",
        "achha smell — rare.",
        "planet line explore karunga.",
        "terrace puja cozy lagta hai.",
        "loud announce nahi karta.",
        "ritual tool worth the price.",
        "association ban gayi.",
        "meaningful gift type.",
        "synthetic shout nahi.",
        "ban gaya default.",
        "roz subah mandir mein lagati hain.",
        "exactly wanted.",
        "evening prayer wear.",
        "aligned feel.",
        "gateway to line.",
        "ritual not party.",
        "month habit ban gaya.",
        "habit hai ab.",
        "projection soft — prayer ok.",
        "subtle temple appropriate.",
        "loyalty speaks.",
        "feel real hai.",
        "bonding hui gift story se.",
        "har saal order.",
        "default ban gaya.",
        "grounded nahi sweet — pasand.",
        "personal prayer scent.",
        "paas wale poochte hain.",
        "believable warmth.",
        "graha remedy din staple.",
        "morning puja companion.",
    ]
    openings = combo_openings(prefixes, suffixes, 96)
    return build_reviews("planet", openings, PLANET_E, count=95)



def build_zodiac() -> list[str]:
    return _secondary("zodiac", ZODIAC_O, ZODIAC_E)


def build_nakshatra() -> list[str]:
    return _secondary("nakshatra", NAKSHATRA_O, NAKSHATRA_E)


def build_perfume() -> list[str]:
    return _secondary("perfume", PERFUME_O, PERFUME_E)


GENERATORS = {
    "planet": build_planet,
    "incense": build_incense,
    "chakra": build_chakra,
    "zodiac": build_zodiac,
    "nakshatra": build_nakshatra,
    "love": build_love,
    "stress": build_stress,
    "perfume": build_perfume,
    "luxury": build_luxury,
    "spiritual": build_spiritual,
    "bestseller": build_bestseller,
    "gift": build_gift,
    "apsara": build_apsara,
    "astrology": build_astrology,
    "mood": build_mood,
    "festival": build_festival,
    "daily": build_daily,
    "meditation": build_meditation,
    "premium": build_premium,
    "limited": build_limited,
    "seasonal": build_seasonal,
    "generic": build_generic,
}
