"""Audited, category-compliant review body generators. Every review uses {{ prv_short }}."""

from prv_category_rules import SHORT

S = SHORT


def _compose(parts: list[str]) -> list[str]:
    out = []
    for p in parts:
        p = p.strip()
        if not p:
            continue
        if S not in p:
            p = f"{S} — {p[0].lower()}{p[1:]}" if p else p
        out.append(p)
    return out


def build_planet() -> list[str]:
    return _compose([
        f"Mummy ne graha remedy ke liye {S} suggest kiya. Subah puja se pehle lagati hoon—mann halka rehta hai, bilkul loud nahi.",
        f"Honestly pehle Navagraha attars gimmick lagte the. {S} try kiya toh samajh aaya—warm resin feel, temple jaisa calm.",
        f"Sunday havan ke din {S} lagana ab habit hai. Diya smoke ke saad blend achha lagta hai, clash nahi.",
        f"Astrologer ne {S} recommend kiya graha shanti ke liye. Wrist par chhoti si matra, puja ke dauran kaafi.",
        f"Temple queue mein wait karte waqt {S} lagati hoon. Grounding milti hai, garmi mein bhi overwhelm nahi.",
        f"Japa mala ke saath {S} use karti hoon. Scent chant ke rhythm mein aa jata hai—alcohol perfume se zyada shaant.",
        f"Pehli baar attar liya tha {S} ke roop mein. Sharp start, baad mein creamy wood—puja ke baad perfect.",
        f"Guru purnima pe order kiya. {S} lagane ke baad ghar mein mandir wali feeling aati hai.",
        f"Evening aarti ke baad {S}—mann shaant, dry-down warm aur grounded.",
        f"Father ko retirement gift diya {S}. Unhone kaha cotton kurta par teen din baad bhi halka sa tha.",
        f"Navgraha prayer ke baad lagaya. Miracle nahi, par saans dheere ho jati hai—yahi chahiye tha.",
        f"Friend ne diya try karne ko. Ab har graha remedy din {S} lagati hoon.",
        f"Varanasi yatra se {S} liya. Ghar aake bhi mandir ki yaad dilata hai.",
        f"Incense ke baad {S}—puja room ka poora ritual complete lagta hai.",
        f"Kurta collar par {S} zyada tikta hai skin se. Fabric hold puja ke liye useful.",
        f"Monsoon mein ek extra dab—expected. Phir bhi {S} humid din mein grounded rehta hai.",
        f"Headache prone hoon; {S} se trigger nahi hua. Pehli priority yahi thi.",
        f"Restock kiya doosra bottle—batch same warm dry-down, consistency achhi.",
        f"Chai aur {S} subah ki duo hai ab. Mood shift subtle par real.",
        f"Gift wrap premium tha. {S} unboxing se scent tak thoughtful laga.",
        f"Nani ne kaha pehle bhi aise attar lagate the. {S} purani warmth, nayi bottle.",
        f"Graha shanti path ke din pandit ji ne casually notice kiya—achha laga.",
        f"Honest review: instant wow nahi, slow attachment hai {S} se. Doosre week se samajh aaya.",
        f"Meditation se pehle do boond {S}. Cushion ke paas baithna easy ho jata hai.",
        f"Corporate diwali list mein {S} add kiya—spiritual gift ke liye safe.",
        f"Only wish: thoda bada size ho daily puja users ke liye. Scent bilkul theek.",
        f"Delivery box dented tha; bottle safe. {S} par koi asar nahi.",
        f"Projection soft hai—mandir ke liye sahi, hall ke liye nahi. Ghar puja perfect.",
        f"Layer kiya tha coconut oil se—longevity badhi. {S} solo bhi achha hai.",
        f"Kid ne kaha ghar achha smell kar raha—rare compliment.",
        f"First Anand Rasa order {S} tha. Ab planet line explore kar rahi hoon.",
        f"Baarish ke din terrace puja + {S}—monsoon ritual ban gaya.",
        f"Travel pouch mein rakha, leak nahi. Scent intact after flight.",
        f"Rishikesh retreat mein {S} use kiya. Wapas ghar pe bhi wahi calm.",
        f"Instagram reel dekhi, skeptical order. {S} worth it for morning ritual.",
        f"Shaam ko journal likhte waqt {S}—focus thoda better lagta hai.",
        f"Pulse par do drop kaafi puja ke liye. Bottle economical chal raha hai.",
        f"Husband usually ignore karta hai scent. {S} ke baad poocha kya badla.",
        f"Sensitive skin—week trial, no rash. Alcohol-free believable laga.",
        f"Opening minute thoda sharp; dry-down hi asli story hai {S} ki.",
        f"Family puja mein sab ne notice kiya—subtle, sabko pasand.",
        f"Chart reading ke din pehna {S}—astrologer friend ne nod kiya.",
        f"Honest—graha dosha poora nahi samajhti, par {S} peaceful hai.",
        f"Navgraha yantra ke paas rakh ke lagaya—cheesy par mood achha.",
        f"Repeat customer—teen bottle {S}, sab consistent.",
        f"Wedding season mein bhi {S} puja routine mein fit—guest scent nahi, ritual scent.",
        f"Cap tight hai, handbag safe. Chhoti luxury detail.",
        f"Pehle week unsure; ab {S} bina puja adhoori lagti hai.",
        f"Evening walk ke baad lagati hoon. Ghar mein soft trail rehti hai.",
        f"Mast lagta hai Sunday ko—{S}, chai, koi jaldi nahi.",
        f"Sach bolu {S} brochure jaisa nahi—human, resinous.",
        f"Guru dakshina mein guru ji ko diya {S}—appreciate kiya.",
        f"Fabric test: linen kurta par subah tak faint trace.",
        f"Initially doubtful thi; {S} ne trust build kiya brand par.",
        f"Heat mein bhi {S} overwhelm nahi karta—halka dab sufficient.",
        f"Puja thali ready karte waqt {S} lagana ritual cue ban gaya.",
        f"Brother ne birth chart ke hisaab se {S} pick kiya—fit laga.",
        f"Night owl hoon—{S} evening aarti ke baad calm deta hai.",
        f"Honest drawback: wedding hall mein projection kam. Ghar mandir ke liye ideal.",
        f"Anand Rasa ka pehla {S}—ab aur graha explore karunga.",
        f"Morning sunlight mein lagane ka alag maza {S} ka.",
        f"Retreat week mein sirf {S} carry kiya—kaafi tha.",
        f"Mann halka ho jata hai {S} ke baad—placebo ho sakta hai, par kaam karta hai.",
        f"Diwali week daily puja mein {S}—diya ke saath warm blend.",
        f"Pehli bottle month chali light use pe. Quality consistent.",
        f"Temple visit se pehle shower skip days pe bhi {S} fresh feel deta hai.",
        f"Honest 4 star feel—opening sharp mere taste ko; dry-down ne rukne diya.",
        f"Grandmother ki attar yaad dilayi—{S} wahi warmth.",
        f"Jyotish consultation ke baad order—remedy feel without drama.",
        f"Ghar ke mandir mein diya jalane se pehle {S}—natural sandal-resin.",
        f"Mujhe honestly expectation nahi thi; {S} pleasantly surprised.",
        f"Repeat restock festival rush mein—delivery time theek, scent same.",
        f"Office ke baad nahi—sirf shaam ki puja ke liye {S}. Us context mein perfect.",
        f"Compliment nahi chahiye tha; shaanti chahiye thi—{S} ne di.",
        f"Planetary remedy box ka best part {S} nikla. Stones display pe, yeh use hota hai.",
        f"Kaafi acha laga pehli baar {S} lagake puja ki.",
        f"Slow burn attachment—{S} se week do mein loyal ho gayi.",
        f"Natural ingredients ki baat booklet mein thi—{S} smell se believable laga.",
        f"Navgraha set se sabse pehle {S} khatam hota hai ghar pe.",
        f"Breath slow ho jati hai {S} ke saath—chai ke baad morning puja staple.",
        f"Honest review: costume jewellery nahi, sincere ritual scent.",
        f"Travel memory scent ban gaya {S}—Haridwar trip.",
        f"Wrist se zyada kurta par {S} hold karta hai—personal trick.",
        f"Subah 5 baje uth ke {S} + puja—discipline easier lagti hai.",
        f"Partner ko bhi {S} pasand aaya puja ke baad ghar ki smell.",
        f"Ekdam subtle—paas wale poochte hain, door se announce nahi.",
        f"Premium bottle weight—pour controlled, waste nahi.",
        f"Festival gift diya maa ko {S}—roz subah mandir mein lagati hain.",
        f"Honestly {S} ke bina graha remedy adhoori feel hoti thi ab.",
        f"Shaant, grounded, resinous—exactly planet attar jaisa hona chahiye.",
        f"Pehle attar sticky samajhta tha; {S} clean dry-down, grease nahi.",
        f"Sunday reset: ghar saaf, diya, {S}—simple shaanti.",
        f"Batch do teen same warm wood—trust build hua.",
        f"Mandir jaate waqt settled feel {S} deta hai—crowd mein kaam aata hai.",
        f"Graha remedy sceptic thi; {S} practical laga, superstitious nahi.",
        f"Night aarti ke baad {S}—sleep se pehle mann calm.",
        f"Worth it for daily spiritual practice—not party scent.",
    ])


def build_incense() -> list[str]:
    return _compose([
        f"Subah puja ke liye {S} perfect—clean smoke, ash kam nikalta hai.",
        f"Ghar ke mandir mein {S} daily. Evening aarti ke baad poora ghar shaant lagta hai.",
        f"Mummy ne suggest kiya {S}. Pehle local agarbatti se shift—farak clearly hai.",
        f"Honestly {S} ki dhooni natural lagti hai, chemical headache nahi.",
        f"Satyanarayan katha mein {S} use kiya—guests ne smell notice kiya positively.",
        f"Diwali week {S} stock kar liya. Diya ke saath room warm sacred feel.",
        f"Meditation corner mein {S} slow burn—1.5 hour claim roughly sahi hai.",
        f"Yoga studio mein {S}—students bolte hain room peaceful lagti hai.",
        f"Pehli premium agarbatti {S} thi. Ab dusra box order.",
        f"Monsoon indoor puja—window thoda khula rakho, {S} cozy lagta hai.",
        f"Guest room mein welcome {S}—hospitality ke liye subtle.",
        f"Sunday ghar saaf + {S}—ritual ban gaya.",
        f"Nag champa fan thi; {S} cleaner variant jaisa feel.",
        f"Lavender wala {S} shaam ko—mann halka before sleep routine.",
        f"Kesar chandan {S} festive puja ke liye—warm sacred aroma.",
        f"Jasmine {S} meditation deepen karta hai—soft floral, overpower nahi.",
        f"Hand-rolled feel {S} ka—loose market se quality jump.",
        f"Holder apna use kiya; {S} evenly burn hota hai.",
        f"4 star observation: ek baar burn time thoda kam tha. Overall satisfied.",
        f"Temple visit ke baad {S} order kiya—ghar mein wahi feel lite.",
        f"Asthma sensitive hoon—mild {S} door rakho, theek rehta hai.",
        f"Mother ko monthly {S} bhejti hoon—puja staple unka.",
        f"Repeat third box—batch consistent clean smoke.",
        f"Incense ke baad attar alag cheez—{S} sirf room ke liye, aur sahi hai.",
        f"Corporate diwali {S} gift—clients ne thank you bola.",
        f"Instagram puja reel se dekha {S}—cautious buy, pleased.",
        f"Packaging simple par sticks premium—{S} worth.",
        f"Baarish ke din indoor {S}—ventilation ke saath best.",
        f"First Anand Rasa {S}—attar bhi try karungi.",
        f"Evening wind-down {S} stick—TV band, bas dhooni.",
        f"Kid homework room mein mild {S}—calm atmosphere.",
        f"Priest ne puja day notice kiya {S}—embarrassing proud moment.",
        f"Travel nahi le jaate par ghar pe {S} must stock.",
        f"Natural ingredients claim {S} se believable—synthetic sting nahi.",
        f"Honest drawback: plastic wrap zyada tha. Sticks achhe.",
        f"Home shrine staple {S}—bina iske puja incomplete feel.",
        f"Family puja sab milke {S} jalate hain—shared ritual.",
        f"Festive pandal ghar pe replicate—{S} + diya.",
        f"Pehle cheap agarbatti—{S} se shift kiya, regret nahi.",
        f"Slow burn, minimal ash—{S} description match karta hai.",
        f"Winter closed room mein careful raho; {S} mild enough.",
        f"Summer morning door open—{S} fresh lagta hai.",
        f"Humidity mein {S} store dry jagah pe—important tip.",
        f"Book reading nook + {S}—cozy tradition.",
        f"Meditation app timer ek {S} stick—fit perfect.",
        f"Wedding house puja ke liye {S} box gift—hit.",
        f"Honest review: perfume nahi, room fragrance—role clear rakho.",
        f"Kaafi acha laga {S} ka natural temple note.",
        f"Repeat subscription chahiye—kabhi khatam na ho.",
        f"Shaam ki aarti ab {S} ke bina adhoori.",
        f"Yoga class donation box mein {S}—popular.",
        f"Initially doubtful thi smoke se; {S} gentle enough.",
        f"Chhoti box try ki, ab full {S} restock.",
        f"Honest 4 star—kabhi kabhi stick break hoti hai. Scent great.",
        f"Pooja room ki hawa badal di {S} ne—subtle trail hours.",
        f"Neighbour puja day compliment—funny but nice.",
        f"Gift mother-in-law {S}—daily use confirm mila.",
        f"Not for wearing—{S} ke liye ghar hi sahi jagah.",
        f"Festival rush delivery ok; {S} dry inside box.",
        f"Sach bolu {S} pooja staple ban gaya.",
        f"Clean smoke description accurate—{S} eyes burn nahi karta.",
        f"First box month chala daily ek stick se.",
        f"Retreat centre mein {S} use dekha—wahi order kiya.",
        f"Honest drawback: holder include karo toh better.",
        f"Dhoop se pehle {S} prefer—less harsh.",
        f"Morning 6am puja {S}—din achha start.",
        f"Premium over loose {S}—worth for mandir respect.",
        f"Repeat customer sirf {S} brand incense.",
        f"Calming atmosphere genuinely—{S} marketing nahi, feel hai.",
        f"Onam sadya se pehle ghar {S}—tradition.",
        f"Navratri nine nights {S} stock—enough.",
        f"Honest review: skin pe mat lagana—room ke liye hai.",
        f"Gurudwara visit memory—{S} ghar laayi.",
        f"Slow ritual build hua {S} se—ab daily.",
        f"Kaafi natural aroma—{S} synthetic sweet nahi.",
        f"Box lasted longer than expected—{S} value achhi.",
        f"Evening tea + {S}—mann shaant.",
        f"First order hooked—{S} ke saath attar bhi cart mein.",
        f"Honest 5 star puja user—{S} consistent.",
        f"Temple feeling ghar mein—{S} ka main point yahi.",
        f"Family function se pehle poora ghar {S}—mehman notice.",
        f"Smoke sensitive guest ko mild {S} door rakha—ok bola.",
        f"Restock alert on—{S} khatam hone nahi dena.",
        f"Daily use kar rahe hain {S}—worth every rupee for puja.",
        f"Honestly expectation se better {S}—slow burn real.",
        f"Puja ke time use karte hain {S}—bas yahi sahi context.",
        f"Peaceful ghar fragrance—{S} exactly that.",
        f"Meditation group ne {S} pasand kiya—shared buy.",
        f"Heat mein bhi {S} evenly burn—holder important though.",
        f"Traditional feeling authentic—{S} market wali cheap smell nahi.",
        f"Anniversary puja mein {S}—pandit approved.",
        f"Chhoti criticism: label peel ho rahi thi. Sticks perfect.",
        f"Worth recommending mandir regulars ko {S}.",
    ])


def build_chakra() -> list[str]:
    return _compose([
        f"Morning yoga se pehle {S}—root grounding feel milta hai.",
        f"Breathwork class mein teacher ne {S} suggest kiya. Focus better lagta hai.",
        f"Meditation cushion ke paas {S} lagana ritual ban gaya—mann still.",
        f"Honestly chakra sceptic thi; {S} phir bhi yoga practice mein achha.",
        f"Reiki session ke dauran {S} subtle—room calm.",
        f"Evening journal + {S}—heart chakra wala soft warmth feel.",
        f"Sound bath mein {S}—immersive, distraction nahi.",
        f"Sacral flow ke liye {S}—creative painting sessions ke saath.",
        f"Solar plexus days pe {S}—confidence dab before practice, not meetings.",
        f"Throat chakra speaker practice—{S} clean herb note helpful lagta hai.",
        f"Third eye meditation {S}—cool spice, chanting ke saath fit.",
        f"Crown sit ke liye {S}—airy floral resin, divine calm cheesy par real.",
        f"Seven bottle try kiye—{S} mera most-used.",
        f"Yoga mat ke paas {S}—entering practice cue.",
        f"Healing circle mein sab different chakra, shared brand.",
        f"Retreat week {S} only—portable ritual.",
        f"Sensitive skin—week trial {S}, no irritation.",
        f"Unscented lotion pe {S}—hold extend hoti hai slightly.",
        f"Gift yoga teacher ko {S}—she uses in studio.",
        f"Pehla chakra attar {S} tha—line explore kar rahi hoon.",
        f"Instagram yoga reel se {S}—cautious, keeping.",
        f"Honest—not magic healing, nice mindful tool {S}.",
        f"Evening bath ke baad {S}—self-care Sunday.",
        f"Breath anchor ke liye {S} before 20 min sit.",
        f"Mantra hour {S}—rhythm ke saath blend.",
        f"Yoga nidra se pehle {S}—sleepy calm.",
        f"Studio mate ne {S} recommend—shared order.",
        f"4 star: projection bahut soft—chakra practice ke liye sahi.",
        f"Repeat root bottle third—{S} consistent batch.",
        f"Monsoon indoor yoga + {S}—cozy practice.",
        f"Winter grounding {S} essential—season match.",
        f"Summer morning practice {S}—light enough.",
        f"Wedding stress month {S} heart warmth—emotional support.",
        f"Teacher training gift {S}—students ask which chakra.",
        f"Honest drawback: bottle chhota daily yogis ke liye.",
        f"Meditation app off, {S} on—better focus maybe placebo.",
        f"Energy balance word cheesy; {S} calm real hai.",
        f"Massage therapist ne notice kiya {S}—subtle.",
        f"Peaceful feeling accurate—{S} loud party scent nahi.",
        f"First Anand Rasa {S}—planet line next.",
        f"Grounding after travel—{S} muladhara vibe.",
        f"Sacral creative block break—{S} warm flow.",
        f"Manipura before difficult conversation—inner strength cue.",
        f"Anahata breakup recovery—{S} gentle, not pity scent.",
        f"Vishuddha truth journaling—{S} clarity feel.",
        f"Ajna study meditation—{S} focus aid.",
        f"Sahasrara morning silence—{S} crown light subtle.",
        f"Kaafi acha laga {S} yoga ke baad—fresh without shower.",
        f"Honest review: daily wear ke liye nahi khareeda—yoga practice ke liye {S}.",
        f"Restock heart and root—{S} staples.",
        f"Gift set se {S} favourite nikla.",
        f"Headache prone—{S} no trigger, important.",
        f"Layering attar + {S} same line—depth interesting.",
        f"Fabric hold kurta par practice ke baad faint.",
        f"Initially doubtful; {S} week two se ritual.",
        f"Spiritual practice scent—{S} sirf yoga mat aur meditation ke liye.",
        f"Mindful routine anchor {S}—alarm ke saath.",
        f"Chakra name on bottle helps pick—{S} matched my need.",
        f"Slow inhale {S} ke saath—breathwork staple.",
        f"Honest 4 star—crown too airy for me; {S} root better.",
        f"Retreat silent day {S} optional—allowed.",
        f"Teacher approved ingredients list—{S} trust.",
        f"Peaceful morning {S}—5am yoga club.",
        f"Worth for serious yoga practitioners.",
        f"Mujhe honestly {S} bina practice adhoori lagti hai ab.",
        f"Natural oils feel—{S} synthetic alcohol blast nahi.",
        f"Repeat customer chakra line only.",
        f"Calming ritual before bed—{S} not sleep spray but helps wind down.",
        f"Honest: corporate wellness bag mein {S} gifted—colleagues yoga wale ko.",
        f"Breathing practice mein {S}—distraction zero.",
        f"Kaafi grounded {S}—earthy notes clear.",
        f"First bottle month light use—{S} lasting.",
        f"Honest review years practice—{S} loyal.",
        f"Healing ritual scent appropriate—{S} date night nahi.",
        f"Subtle on skin—{S} yoga mat aura jaisa.",
        f"Family gift sister ko {S}—she converted.",
        f"Honest drawback wish roller for after yoga.",
        f"Temple garden sit + {S}—peaceful combo.",
        f"Sach bolu {S} energy practice ke saath fit.",
        f"Premium feel bottle—{S} respect deta hai practice ko.",
        f"Repeat third {S}—batch same.",
        f"Mindful massage self—{S} drop on wrist.",
        f"Honest 5 star yoga staple {S}.",
        f"Quiet room scent literal—{S}.",
        f"Initially strong; dry-down {S} perfect for meditation.",
        f"Worth premium per peaceful practice.",
        f"Daily yoga uniform scent nahi—practice-only {S}, aur sahi.",
        f"Honest review chakra role clear—{S}.",
        f"Breath slow hoti hai {S} se—maybe association, maybe real.",
        f"Gift mother retirement yoga—{S} daily.",
        f"Honest—not replace therapy—{S} support tool.",
        f"Kaafi shaant dry-down {S} ka.",
        f"First attar chakra entry perfect {S}.",
        f"Repeat must not run out {S}.",
        f"Spiritual practice only context—{S} sirf healing ritual ke liye.",
        f"Peaceful feeling believable—{S} delivered.",
    ])


# Additional builders follow same pattern - I'll add zodiac, nakshatra, love, stress, perfume, luxury, spiritual, bestseller, gift, and others in same file

def build_zodiac() -> list[str]:
    return _compose([
        f"Birthday month mein apne rashi ke liye {S} liya—personal signature lagta hai.",
        f"Sister ko {S} gift diya uski rashi ka—ab daily wear karti hai.",
        f"Honestly pehle zodiac scents cheesy lagte the. {S} mature nikla.",
        f"Chart reading party mein {S} pehna—conversation starter among astro friends.",
        f"Daily office wear {S}—ek dot, elevator safe, colleague ne once poocha.",
        f"Wedding guest {S}—subtle compliment mila family se.",
        f"Instagram astrology page se {S}—cautious order, restock kiya.",
        f"Partner same sign—matching {S} cute ritual.",
        f"First attar {S} tha—gateway to brand.",
        f"Alcohol perfume rash—{S} oil base gentle.",
        f"Date night {S}—partner noticed, positive.",
        f"Festive season daily {S}—compliments without overkill.",
        f"Gifting rashi {S}—thoughtful for astro lover.",
        f"Horoscope notification ke baad impulse {S}—achha nikla.",
        f"Confidence boost subtle—{S} feel-good reminder.",
        f"Kurta fabric hold achha {S} ka wedding season.",
        f"Sensitive skin month trial {S}—fine.",
        f"Travel one bottle {S} ten days—consistent.",
        f"4 star: projection party ke liye kam; daily ke liye perfect {S}.",
        f"Friend referral {S}—her rashi worked, mine too.",
        f"Moisturizer pe {S}—longevity better, skin-close.",
        f"College campus subtle {S}—classmates curious.",
        f"Retrograde joke gift {S}—actually calming.",
        f"Rashi pride without cringe—{S} balance achha.",
        f"Book club astrology theme {S}—fun.",
        f"Husband skeptical, ab {S} khud order.",
        f"Night drive {S}—car cozy.",
        f"Premium bottle {S} gift worthy.",
        f"Repeat teen rashi bottles family—consistent quality.",
        f"Diwali {S} gifts—family appreciated thought.",
        f"Monsoon extra dab once {S}—ok.",
        f"Winter shawl {S} beautiful carry.",
        f"Summer wedding guest {S}—not too sweet.",
        f"Compliment cafe rare—{S} day.",
        f"Kid said nice smell—home win {S}.",
        f"Sach bolu {S} daily uniform ban sakta hai.",
        f"Wedding sangeet {S} outfit ke saath cohesive.",
        f"Layer strong oud fail—{S} solo best.",
        f"Evening aarti plus {S}—double ritual some days.",
        f"Corporate rashi gift client—personal touch.",
        f"Restock alert {S}—mid month khatam nahi.",
        f"Delivery late festival—{S} scent made up.",
        f"Pehle week unsure; doosre week love {S}.",
        f"Astrology believer nahi; {S} phir bhi achha scent.",
        f"Couple chart matching {S} gifts—sweet.",
        f"Fabric 24h faint trace {S} cotton shirt.",
        f"First Anand Rasa {S}—explore planet next.",
        f"Mast personal scent—{S} subtle.",
        f"Baarish WFH {S} cozy.",
        f"Honest drawback cap tight arthritic hands—scent 5.",
        f"Chart reader recommended {S}—fit traits.",
        f"Presentation day {S}—calm confidence.",
        f"Repeat customer zodiac loyal {S}.",
        f"Anniversary rashi gift husband—uses daily.",
        f"Initially doubtful tha {S}; ab staple.",
        f"Signature wear claim true—{S}.",
        f"Compliment dinner not entrance—{S} classy.",
        f"Self purchase treat {S} birthday month.",
        f"Honest review rashi scent realistic.",
        f"Travel pouch {S} essential.",
        f"Premium feel worth {S} price per wear.",
        f"Sibling rashi debate—{S} resolved by trying.",
        f"Daily wear office safe confirmed {S}.",
        f"Wrist dot enough {S}—no cloud.",
        f"Festive brunch {S} light.",
        f"Mother Mother's Day {S}—morning walk pe.",
        f"Honest 4 star want louder sometimes; daily perfect {S}.",
        f"Kaafi acha laga {S} pehli baar.",
        f"Astrology club compare scents—{S} held up.",
        f"Repeat wedding season guest {S}.",
        f"Modern zodiac gift not tacky—{S}.",
        f"Personal scent identity—{S} fits.",
        f"Honest—not fortune juice—wearable {S}.",
        f"Heat mein {S} behave kiya humid wedding.",
        f"Gift newly engaged friends {S}—hit.",
        f"Slow love some instant—{S} week two crowd.",
        f"Rashi chart fridge, {S} dresser—cute.",
        f"Honest review believer sceptic both ok {S}.",
        f"Daily signature honestly {S}.",
        f"Compliment colleague subtle {S}—rare.",
        f"First bottle two months light {S}.",
        f"Worth hype test {S} passed.",
        f"Mujhe {S} apni rashi jaisa feel hota hai—subjective par real.",
        f"Repeat restock must {S}.",
        f"Evening wear transition same bottle {S}.",
        f"Honest drawback small travel size wish.",
        f"Kaafi personal {S}—generic nahi lagta.",
        f"Instagram reel discovery {S}—converted.",
        f"Family rashi gifts set—{S} star.",
        f"Honest 5 star daily rashi wear {S}.",
        f"Confidence daily—not loud {S}.",
        f"Subtle compliments real {S}.",
        f"Worth exploring other signs {S} gateway.",
        f"Anniversary splurge {S}—no regret.",
        f"Honest review years—{S} loyal.",
        f"Daily use kar raha hoon {S}—signature ban gaya.",
        f"Astrology lover perfect gift {S}.",
        f"Pehla zodiac attar {S}—impressed.",
        f"Sach bolu {S} fit my rashi mood.",
        f"Office meetings {S} safe—tested.",
        f"Repeat third bottle {S} same quality.",
        f"Honest review authentic rashi buyer.",
    ])


def build_nakshatra() -> list[str]:
    return _compose([
        f"Birth star ke liye {S} astrologer ne suggest kiya—evening prayer staple.",
        f"Janma nakshatra gift brother se {S}—thoughtful beyond typical.",
        f"Honestly {S} calming hai—aggressive notes nahi.",
        f"Vedic consultation ke baad order {S}—personal alignment feel.",
        f"Nakshatra homam din pehna {S}—pandit nod kiya.",
        f"Chanting practice {S} ke saath—breath slow.",
        f"Wedding muhurat shopping {S} bride gift—she cried happy.",
        f"New moon night {S}—quiet anchor.",
        f"Ancestral remembrance day {S}—grandmother memory.",
        f"Family puja collective different stars, same brand {S}.",
        f"Pehla nakshatra attar {S}—line explore.",
        f"Evening prayers {S} bina adhoori lagti hain ab.",
        f"Fabric hold cotton saree faint morning {S}.",
        f"Sensitive skin alcohol-free {S}—week ok.",
        f"Gift astrology lover {S}—they knew star immediately.",
        f"Peaceful fragrance sach {S}—vedic calm.",
        f"Puja room corner {S}—meditation adjacent.",
        f"Wish booklet included—scent {S} great though.",
        f"Restock same star {S}—batch consistent.",
        f"Rishikesh trip purchase {S}—ghar calm.",
        f"Wife birth star {S}—daily wear.",
        f"Projection very soft—nakshatra ritual ke liye sahi {S}.",
        f"Monsoon extra dab {S} once.",
        f"Winter evening prayers {S} warm hold.",
        f"Summer light enough surprise {S} oil attar.",
        f"Aunt compliment family function {S}.",
        f"Kid calm home puja {S}—bonus.",
        f"Slow love week two {S}.",
        f"Chart on fridge {S} dresser—aligned.",
        f"Muhurat impulse best impulse {S}.",
        f"First attar nakshatra entry {S} perfect.",
        f"Evening journal star theme {S}.",
        f"Honest drawback small bottle daily users {S}.",
        f"Breathwork {S} anchor—focus maybe placebo.",
        f"Premium packaging respect tradition {S}.",
        f"Repeat third bottle {S} loyalty.",
        f"Sach bolu peaceful {S}—description match.",
        f"Headache prone no trigger {S}.",
        f"Incense then {S} attar—complementary.",
        f"First Anand Rasa {S} hooked.",
        f"Baarish birth star ritual cozy {S}.",
        f"Subtle temple appropriate {S}.",
        f"Worth birth star ritual fragrance {S}.",
        f"Mast evening calm {S}.",
        f"Astrologer casual compliment {S}—day made.",
        f"Opening sharp dry-down divine {S}—4 star feel stayed.",
        f"Birth star pride subtle {S}.",
        f"Instagram vedic page {S}—authentic not gimmick.",
        f"Layer coconut oil vedic style {S} longevity.",
        f"Temple visit star day special {S}.",
        f"Mom same nakshatra matching scents {S}.",
        f"Honest nakshatra names confusing; scent simple achha {S}.",
        f"Spiritual alignment note feels real {S}.",
        f"Wedding guest nakshatra talk bonding {S}.",
        f"Repeat annual homam {S}.",
        f"Travel memory scent {S}.",
        f"Honest review sceptic friendly {S}.",
        f"Quiet evenings {S} default.",
        f"Natural wood floral {S}—vedic warmth.",
        f"Gift set star highlight {S}.",
        f"Initially doubtful; {S} ritual staple now.",
        f"Mann halka {S} ke baad—shaam ki dua.",
        f"Honest—not costume—sincere {S}.",
        f"Kaafi acha laga {S} birth star context.",
        f"Fabric dupatta hold impressive {S}.",
        f"Repeat must {S}.",
        f"Family recommended {S}—fit star.",
        f"Honest 5 star evening prayer {S}.",
        f"Cosmic calm cheesy word; feel real {S}.",
        f"First bottle festival opened {S}.",
        f"Honest drawback guide wish—scent delivers {S}.",
        f"Star-aligned calm accurate {S}.",
        f"Meditation light support {S}.",
        f"Pehle attar try {S}—vedic entry.",
        f"Honest review believer respect {S}.",
        f"Gentle hold hours {S}—ritual not party.",
        f"Corporate gift star based client touched {S}.",
        f"Slow routine month habit {S}.",
        f"Sach bolu {S} nakshatra purpose match.",
        f"Repeat customer nakshatra only {S}.",
        f"Evening aarti {S} habit.",
        f"Honest 4 star projection soft—ok for prayer {S}.",
        f"Worth premium ritual tool {S}.",
        f"Peaceful nights {S} association.",
        f"Honest review years user {S}.",
        f"Birth star gift best type {S}.",
        f"Kaafi vedic calm {S}—no synthetic shout.",
        f"Initially unsure sweet; {S} grounded nahi sweet.",
        f"Honest review authentic star buyer {S}.",
        f"Repeat restock alert {S}.",
        f"Temple cotton vibe {S} subtle.",
        f"Mann shaant {S}—exactly wanted.",
        f"Honest 5 star birth star wear {S}.",
        f"Daily fragrance ritual aligned {S}.",
        f"First Anand Rasa star line {S}.",
        f"Worth every star believer {S}.",
        f"Honest review product-aware {S}.",
        f"Puja ke time {S}—correct use.",
        f"Peaceful dry-down {S} real.",
        f"Gift father star {S}—uses.",
        f"Honest—not for club—prayer {S}.",
        f"Kaafi gentle {S}.",
        f"Repeat loyal {S}.",
        f"Evening star prayer {S} perfect.",
    ])


# Export all builders - continue with remaining in GENERATORS dict


def _gen(axis: str, hooks: list[str], mids: list[str], ends: list[str], count: int = 90) -> list[str]:
    """Combine unique triples for category-appropriate reviews."""
    out = []
    used = set()
    hi, mi, ei = len(hooks), len(mids), len(ends)
    for i in range(count):
        for attempt in range(hi * mi * ei):
            j = (i + attempt) % hi
            k = (i * 3 + attempt) % mi
            l = (i * 7 + attempt) % ei
            text = f"{hooks[j]} {S} {mids[k]} {ends[l]}".replace("  ", " ").strip()
            if S not in text:
                text = f"{S} — {text[0].lower()}{text[1:]}" if text else text
            if text not in used:
                used.add(text)
                out.append(text)
                break
        else:
            out.append(f"{hooks[i % hi]} {S} {mids[i % mi]} {ends[i % ei]} ({i}).")
    return out[:count]


def build_love() -> list[str]:
    return _gen("love",
        ["Anniversary dinner pe", "Date night pe", "Wife ko gift", "Proposal night pe", "Honeymoon bag mein",
         "Wedding sangeet mein", "Partner surprise", "Valentine pe order", "Candlelit dinner", "First romantic attar"],
        ["soft floral warmth dikhi.", "compliment mila table par.", "pasand aaya surprisingly.", "intimate lagta hai.",
         "romantic without headache sweet.", "partner noticed positively.", "skin par gentle warmth.", "evening glow real.",
         "rose note sophisticated laga.", "shared bottle ban gaya."],
        ["Repeat restock karungi.", "Honestly expectation se better.", "Kaafi acha laga.", "Subtle premium feel.",
         "4 star: projection party kam, dinner perfect.", "Sensitive skin ok.", "Travel size chahiye ab.", "Fabric saree par faint trace.",
         "Alcohol perfume se switch.", "Sach bolu romantic feel real."],
    )


def build_stress() -> list[str]:
    return _gen("stress",
        ["Office ke baad", "Sleep se pehle", "Exam week mein", "Yoga unwind ke liye", "Sunday reset",
         "Commute ghar aake", "Therapy evenings", "Monsoon blues din", "Desk burnout week", "Night routine mein"],
        ["{s} lagake baithti hoon—shoulder tension kam feel.".replace("{s}", S),
         "{s} pillow edge pe—gentle calm.".replace("{s}", S),
         "{s} wrist pe—small comfort.".replace("{s}", S),
         "{s} se breath easy lagta hai.".replace("{s}", S),
         "{s} chai ke saath—mann halka.".replace("{s}", S)],
        ["Headache trigger nahi—important.", "Repeat bedside staple.", "Honestly placebo ho sakta hai par kaam karta hai.",
         "Kaafi shaant dry-down.", "4 star: panic moments ke liye subtle.", "Not medical—self care yes.", "Kid exam season household calmer.",
         "First stress attar keeping.", "Worth evening ritual.", "Mast shaam ka unwind."],
    )


def build_perfume() -> list[str]:
    return _gen("perfume",
        ["Office Monday", "Client lunch ke baad", "Airport travel mein", "WFH video calls", "Presentation day",
         "Commute metro", "Brunch outing", "Humid wedding guest", "Evening dinner", "Business trip"],
        ["{s} neck dot—elevator safe.".replace("{s}", S),
         "{s} subtle professional.".replace("{s}", S),
         "{s} consistent character.".replace("{s}", S),
         "{s} meeting safe.".replace("{s}", S),
         "{s} compliment after not during.".replace("{s}", S)],
        ["Repeat office bottle.", "Sensitive skin month fine.", "Modern fragrance soul attar—accurate.",
         "6 hours realistic longevity.", "4 star opening sharp office, dry-down saves.", "Travel leak test pass.",
         "Kaafi office driver potential.", "Heat mein behave kiya.", "Honestly daily wear workhorse.", "Sach bolu office safe true."],
    )


def build_luxury() -> list[str]:
    return _gen("luxury",
        ["Gallery opening", "Boardroom dinner", "Resort stay", "Black tie event", "Heirloom gift",
         "Collector shelf", "Wine pairing dinner", "Anniversary splurge", "Client gifting", "Special occasion"],
        ["{s} elegant dry-down.".replace("{s}", S),
         "{s} refined not loud.".replace("{s}", S),
         "{s} premium texture clear.".replace("{s}", S),
         "{s} sophisticated sillage.".replace("{s}", S),
         "{s} bottle display worthy.".replace("{s}", S)],
        ["Long lasting without shout.", "4 star: price high, quality matches.", "Worth special occasions.",
         "Velvety heart note real.", "Not designer flex—quality flex.", "Repeat luxury annual treat.",
         "Kaafi classy feel.", "Honest not daily budget scent.", "Premium packaging matched.", "Sach bolu sophisticated."],
    )


def build_spiritual() -> list[str]:
    return _gen("spiritual",
        ["Temple morning", "Puja thali ready", "Aarti evening", "Pilgrimage trip", "Diya lighting",
         "Chanting hour", "Retreat week", "Guru dakshina gift", "Home mandir", "Sacred thread day"],
        ["{s} lagane se devotional warm feel.".replace("{s}", S),
         "{s} diya smoke complement.".replace("{s}", S),
         "{s} breath slow hoti hai.".replace("{s}", S),
         "{s} temple cotton vibe.".replace("{s}", S),
         "{s} ghar shanti feel.".replace("{s}", S)],
        ["Never office context—puja only.", "Repeat mandir staple.", "Frankincense sandal believable.",
         "4 star projection zero—temple ok.", "Honest not miracle—ritual helper.", "Kaafi authentic.",
         "Sensitive skin daily puja fine.", "Premium devotional respect.", "Sach bolu peaceful puja.", "First spiritual attar keeping."],
    )


def build_bestseller() -> list[str]:
    return _gen("bestseller",
        ["Pehla Anand Rasa order", "Friend referral se", "Instagram reel", "Festival rush buy", "Cart add-on",
         "Family recommendation", "Office colleague tip", "Anniversary splurge curious", "Discovery kit se", "Repeat restock"],
        ["{s} hype justified laga.".replace("{s}", S),
         "{s} balanced daily wear.".replace("{s}", S),
         "{s} gift safe nikla.".replace("{s}", S),
         "{s} consistent quality.".replace("{s}", S),
         "{s} crowd favorite samajh aaya.".replace("{s}", S)],
        ["Worth trying new brand.", "4 star personal taste vary.", "Reliable hold.", "Kaafi fan favorite.",
         "Honestly dependable.", "Sensitive skin ok.", "Repeat fourth bottle.", "Not unique—reliably good.",
         "Sach bolu worth hype.", "Gateway to other lines."],
    )


def build_gift() -> list[str]:
    return _gen("gift",
        ["Birthday hamper", "Wedding return gift", "Corporate diwali", "Mother's day box", "Housewarming",
         "Anniversary box", "Festive hamper", "Bridal trousseau", "Thank you gift", "Discovery kit"],
        ["{s} unboxing wow mila.".replace("{s}", S),
         "{s} presentation premium thi.".replace("{s}", S),
         "{s} ribbon quality achhi.".replace("{s}", S),
         "{s} hamper star product.".replace("{s}", S),
         "{s} keepsake box reuse hua.".replace("{s}", S)],
        ["Recipient converted customer.", "4 star shipping heavy.", "Corporate repeat third year.",
         "Kaafi thoughtful gift.", "Honestly packaging half the joy.", "Premium reveal slow open.",
         "Build box custom feel luxe.", "Sach bolu gift memory real.", "Worth premium gifting.", "Repeat gifter loyal."],
    )


def build_apsara() -> list[str]:
    return _gen("apsara",
        ["Kathak rehearsal", "Sangeet night", "Classical recital", "Bridal getting ready", "Heritage wedding",
         "Photo shoot", "Poetry evening", "Temple festival", "Dance competition", "Art collector gift"],
        ["{s} stage grace subtle.".replace("{s}", S),
         "{s} divine floral not loud.".replace("{s}", S),
         "{s} temple jasmine authentic.".replace("{s}", S),
         "{s} heritage bloom feel.".replace("{s}", S),
         "{s} mythic rose soft.".replace("{s}", S)],
        ["Not daily office scent—art days.", "Teacher compliment backstage.", "4 star long performance reapply.",
         "Kaafi elegant stage.", "Honest niche appeal.", "Premium artistic gift.", "Repeat recital season.",
         "Sach bolu graceful.", "First apsara impressed.", "Worth mythology lover."],
    )


def build_astrology() -> list[str]:
    return _gen("astrology",
        ["Chart reading day", "Astrologer visit", "Muhurat shopping", "Retrograde season", "Couple compatibility",
         "Remedy box", "New year forecast", "Gemstone pairing ritual", "Zodiac party", "Journaling stars"],
        ["{s} cosmic calm helper.".replace("{s}", S),
         "{s} remedy wear feel.".replace("{s}", S),
         "{s} chart day scent.".replace("{s}", S),
         "{s} ritual pairing achha.".replace("{s}", S),
         "{s} aligned aura subtle.".replace("{s}", S)],
        ["Belief optional enjoyment mandatory.", "4 star jargon confusing—scent great.", "Gift astro friend hit.",
         "Kaafi vedic respectful tone.", "Honestly sceptic friendly.", "Repeat annual ritual.",
         "Sach bolu astrology lover gift.", "Planet zodiac umbrella works.", "Premium remedy presentation.", "Worth ritual set."],
    )


def build_mood() -> list[str]:
    return _gen("mood",
        ["Rainy afternoon", "Sunlit balcony", "Slow Sunday", "Journal hour", "Creative afternoon",
         "Post workout calm", "Solo drive", "Coffee shop work", "Playlist match", "Self care evening"],
        ["{s} cozy lift deta hai.".replace("{s}", S),
         "{s} mood shift subtle.".replace("{s}", S),
         "{s} feel-good dry-down.".replace("{s}", S),
         "{s} balcony breeze match.".replace("{s}", S),
         "{s} not antidepressant—helper.".replace("{s}", S)],
        ["4 star tag vague scent good.", "Rainy day specialist.", "Kaafi acha rainy calm.",
         "Honest afternoon treat.", "Repeat monsoon bottle.", "Sensitive skin ok.", "Sach bolu mood lift real.",
         "Not magic happiness.", "Premium self care.", "Worth mood experiment."],
    )


def build_festival() -> list[str]:
    return _gen("festival",
        ["Diwali prep", "Navratri night", "Eid gathering", "Durga puja pandal", "Onam morning",
         "Holi brunch", "Ganesh visarjan", "Christmas eve", "Pongal harvest", "Baisakhi fair"],
        ["{s} diya pairing perfect.".replace("{s}", S),
         "{s} festive warmth ghar mein.".replace("{s}", S),
         "{s} family room celebration scent.".replace("{s}", S),
         "{s} tradition note subtle.".replace("{s}", S),
         "{s} gathering comfortable—not loud.".replace("{s}", S)],
        ["4 star sweet food environment compete.", "Year round less use—festival yes.", "Repeat annual stock.",
         "Kaafi festive hold.", "Honest not firecracker smell.", "Premium festive wrap.", "Sach bolu celebration glow.",
         "Guests noticed brand.", "Puja + festive wear.", "Worth festival collection."],
    )


def build_daily() -> list[str]:
    return _gen("daily",
        ["Office commute", "WFH desk", "College campus", "School pickup run", "Market errands",
         "Lunch break walk", "Metro ride", "Weekday uniform", "Evening walk", "Gym to dinner transition"],
        ["{s} ek dot kaafi.".replace("{s}", S),
         "{s} subtle trail.".replace("{s}", S),
         "{s} desk friendly.".replace("{s}", S),
         "{s} no perfume cloud.".replace("{s}", S),
         "{s} daily driver confirmed.".replace("{s}", S)],
        ["Repeat monthly restock.", "4 star weekend want bolder.", "Elevator safe tested.",
         "Kaafi weekday staple.", "Cost per wear low.", "Honest boring reliable good.", "Heat extra dab once.",
         "Sach bolu office safe.", "First daily attar success.", "Worth daily tag."],
    )


def build_meditation() -> list[str]:
    return _gen("meditation",
        ["Morning sit", "Vipassana day", "Breathwork class", "Silent retreat", "Zafu session",
         "Mantra hour", "Sunrise sit", "Temple garden", "Yoga nidra prep", "Candle meditation"],
        ["{s} breath anchor.".replace("{s}", S),
         "{s} cushion calm real.".replace("{s}", S),
         "{s} silent depth no distraction.".replace("{s}", S),
         "{s} focus aid subtle.".replace("{s}", S),
         "{s} quiet room scent.".replace("{s}", S)],
        ["Never bought for office—sit only.", "4 star silence purists optional.", "Headache no trigger critical.",
         "Kaafi zen wood vibe.", "Honest not enlightenment juice.", "Repeat retreat pack.", "Sach bolu still mind helper.",
         "Teacher approved.", "Premium retreat tool.", "Worth meditators."],
    )


def build_premium() -> list[str]:
    return _gen("premium",
        ["Flagship visit", "Consult pick", "Collector buy", "Heirloom gift", "Spa parallel",
         "Limited batch", "Five star stay", "Private consultation", "Art preview", "Milestone celebration"],
        ["{s} top tier resin feel.".replace("{s}", S),
         "{s} batch depth noticeable.".replace("{s}", S),
         "{s} collector grade.".replace("{s}", S),
         "{s} premium hold hours.".replace("{s}", S),
         "{s} flagship find.".replace("{s}", S)],
        ["4 star price premium justified mostly.", "Special occasion not daily.", "Worth splurge once.",
         "Kaafi rare bloom.", "Honest drawback small bottle big price.", "Repeat annual treat.", "Sach bolu house best.",
         "Sensitive skin gentle.", "Premium memorable.", "Not casual overspend guilt sometimes."],
    )


def build_limited() -> list[str]:
    return _gen("limited",
        ["Drop day", "Waitlist win", "Numbered bottle", "Launch party", "Early access",
         "Seasonal batch", "Anniversary edition", "VIP club", "Collab release", "Sold out restock"],
        ["{s} exclusive dry-down.".replace("{s}", S),
         "{s} rare resin feel.".replace("{s}", S),
         "{s} batch number pride.".replace("{s}", S),
         "{s} collect now urge.".replace("{s}", S),
         "{s} wait worth.".replace("{s}", S)],
        ["4 star FOMO pricing high.", "Display sometimes wear.", "Kaafi drop day story.",
         "Honest marketing anxiety.", "Repeat waitlist subscriber.", "Sach bolu limited pour special.",
         "Not resale flip—wear.", "Premium numbered presentation.", "Worth collector joy.", "Exclusive character real."],
    )


def build_seasonal() -> list[str]:
    return _gen("seasonal",
        ["Monsoon terrace", "Summer wedding", "Winter shawl", "Hill station trip", "Coastal monsoon",
         "December wedding", "Spring picnic", "Mango season ghar", "Autumn travel", "Diwali week"],
        ["{s} humidity behave kiya.".replace("{s}", S),
         "{s} weather smart feel.".replace("{s}", S),
         "{s} season shift match.".replace("{s}", S),
         "{s} monsoon hold surprising.".replace("{s}", S),
         "{s} cool air sharper.".replace("{s}", S)],
        ["4 star monsoon extra dab.", "Off season storage note.", "Repeat monsoon annual.",
         "Kaafi climate match.", "Honest niche seasonal tags.", "Worth weather pairing.", "Sach bolu monsoon user.",
         "Winter depth beautiful.", "Summer light enough.", "Premium seasonal gift."],
    )


def build_generic() -> list[str]:
    return _gen("generic",
        ["Pehli baar attar", "Online order skeptical", "Cousin wedding", "Store discovery", "Travel bottle",
         "Friend recommended", "Festival purchase", "Layering experiment", "Reading reviews then buy", "Instagram discovery"],
        ["{s} gently surprised.".replace("{s}", S),
         "{s} warm balanced.".replace("{s}", S),
         "{s} natural oils feel.".replace("{s}", S),
         "{s} elegant bottle.".replace("{s}", S),
         "{s} alcohol free gentle.".replace("{s}", S)],
        ["Repeat exploring collections.", "4 star learning application.", "Kaafi acha first impression.",
         "Honest gateway product.", "Sensitive skin week ok.", "Sach bolu worth it.", "Fabric hold decent.",
         "Worth Anand Rasa intro.", "Honestly human craft.", "Daily potential seen."],
    )


GENERATORS = {
    "planet": build_planet,
    "incense": build_incense,
    "chakra": build_chakra,
    "zodiac": build_zodiac,
    "nakshatra": build_nakshatra,
    "love": build_love,
    "stress": build_stress,
    "perfume": build_perfume,
    "luxury": build_luxury,
    "spiritual": build_spiritual,
    "bestseller": build_bestseller,
    "gift": build_gift,
    "apsara": build_apsara,
    "astrology": build_astrology,
    "mood": build_mood,
    "festival": build_festival,
    "daily": build_daily,
    "meditation": build_meditation,
    "premium": build_premium,
    "limited": build_limited,
    "seasonal": build_seasonal,
    "generic": build_generic,
}
