"""Collection-specific review bodies — part 2."""

SHORT = "{{ prv_short }}"


def _love_bodies():
    return [
        f"Anniversary dinner pe lagaya—{SHORT} soft floral warmth, table candle ke saath perfect.",
        f"Wife ko Valentine gift. Ab wo khud restock karti hai, best sign.",
        f"Date night scent—compliment mila car mein, restaurant mein nahi. Subtle.",
        f"Proposal backup tha—ended up wearing only {SHORT}. She noticed.",
        f"Honeymoon essential ban gaya. Travel size chahiye ab.",
        f"Wedding sangeet—romantic without sweet headache. Dance floor tested.",
        f"First date redo after ten years—scent memory banaya.",
        f"Partner surprise gift—he wears daily now shyly.",
        f"Candlelit home dinner—intimate sillage, TV room mein soft.",
        f"Rose attar cliché lagta tha—{SHORT} sophisticated rose, powdery nahi.",
        f"Musk undertone warm—skin close romance.",
        f"Projection thodi kam party ke liye; date night ke liye bilkul ideal.",
        f"Alcohol perfume se switch—romantic scents gentler on skin.",
        f"Layer moisturizer—longevity anniversary worthy.",
        f"Sister ki shaadi gift—bridal getting ready scent.",
        f"Romantic feeling genuine—marketing speak nahi lagta.",
        f"Compliment from partner rare—{SHORT} earned it.",
        f"Evening walk holding hands—scent part of memory.",
        f"Self love Sunday—romantic for self bhi valid.",
        f"Sensitive skin date ready—no rash worry.",
        f"Fabric hold—saree next day faint romantic trace.",
        f"Corporate couple gift—both loved.",
        f"Instagram couple reel product—cautious, pleased.",
        f"Monsoon date indoor—cozy romantic warmth.",
        f"Winter shawl romance—scent carries beautiful.",
        f"Summer wedding guest romantic note subtle.",
        f"Honest—single hoon, self gift still nice.",
        f"Divorce recovery self care—soft scent comfort.",
        f"Long distance visit—scent memory partner kept.",
        f"Engagement photoshoot—romantic backdrop scent.",
        f"Restaurant complaint none—elevator safe.",
        f"Kid said parents smell nice—cute.",
        f"Premium packaging gift unbox special.",
        f"Repeat buy third bottle—love line staple.",
        f"First attar romantic entry—success.",
        f"Honest drawback: wish rollerball option.",
        f"Mohini energy subtle—not overpowering seduction.",
        f"Heart note creamy—anniversary dinner approved.",
        f"Soft floral warmth exactly as described.",
        f"Partner allergic to strong perfume—this works.",
        f"Night drive romance—car cozy.",
        f"Booked staycation—brought {SHORT} only.",
        f"Compliment stranger coffee shop—blushed.",
        f"Layering vanilla oil—too sweet solo perfect.",
        f"Wedding anniversary twenty years—new ritual scent.",
        f"Sach bolu romantic feel real hai.",
        f"4 star—opening generic, dry-down beautiful.",
        f"Gift wrap ribbon quality—presentation matched scent.",
        f"First Anand Rasa love—exploring more.",
        f"Evening puja then romantic dinner—dual use.",
        f"Fabric silk hold impressive romantic.",
        f"Honest—not aphrodisiac magic, mood helper yes.",
        f"Worth it for special occasions collection.",
        f"Mast date night—subtle premium.",
        f"Baarish window romance—scent cozy.",
        f"Husband gift from kids—father wears proudly.",
        f"Slow love scent—hour two best.",
        f"Travel anniversary—one bottle enough.",
        f"Sensitive romantic—no headache.",
        f"Repeat wedding season guest scent.",
        f"Premium feel worth splurge occasions.",
        f"Honest 5 stars anniversary repeat.",
        f"Couple matching scents cute tradition.",
        f"Restaurant date compliment waiter noticed? No. Partner yes.",
        f"Romantic getaway bag essential.",
        f"Self purchased not gift—still special.",
        f"Pehle week unsure sweet ho kya—nahi hua.",
        f"Wrist dot romantic enough.",
        f"Evening gown scent—elegant not loud.",
        f"Love collection entry—keeping.",
        f"Honest drawback small bottle events only.",
        f"Partner switched from designer—says prefer this.",
        f"Compliment family function subtle.",
        f"Moonlit balcony romance cliché par achha.",
        f"First romantic attar—impressed.",
        f"Worth gifting newly engaged friends.",
        f"Mast soft warmth—ekdum intimate.",
        f"Rose without grandma purse smell—modern.",
        f"Anniversary restock must.",
        f"Honest review romantic believers and skeptics both ok.",
        f"Date home cooked—scent elevated evening.",
        f"Delivery late aayi Valentine pe—par scent ne mood bacha liya.",
        f"Silk scarf hold romantic memory.",
        f"Premium romantic—not cheap chocolate vibe.",
        f"Repeat customer love line only.",
        f"Sach bolu worth anniversary splurge.",
    ]


def _stress_bodies():
    return [
        f"Office ke baad {SHORT} lagake baithti hoon—shoulder tension kam feel hoti hai.",
        f"Sleep routine mein add kiya. Lavender type calm, synthetic nahi.",
        f"Exam week survival scent—desk par dot, small comfort.",
        f"Yoga unwind after brutal Monday—breath easier feels.",
        f"Therapy evenings associative calm—week three strong.",
        f"Commute home metro crowd—wrist calm bubble illusion helpful.",
        f"Sunday reset essential—clean flat plus scent.",
        f"Monsoon blues helper—wood rain vibe.",
        f"Panic week HR drama—bathroom dab reset.",
        f"Before sleep pillow edge—gentle not overpowering.",
        f"Headache prone—no trigger critical. Passed.",
        f"4 stars—sleep scent projection zero which is good.",
        f"Desk burnout standup before—anchor ritual.",
        f"Sensitive skin stress line gentle.",
        f"Alcohol perfume anxiety—switch helped.",
        f"Partner noticed calmer evenings—bonus.",
        f"Insomnia not cured—ritual helps wind down.",
        f"Lavender incense plus attar—double calm.",
        f"Moon attar type cool—emotional reset.",
        f"Ketu meditative calm—detachment lite.",
        f"Sandal balm vibe—restorative.",
        f"Soft woods hug scent—blanket pairing.",
        f"Quiet exhale marketing—actually feels that.",
        f"No headache claim tested—true for me.",
        f"Repeat restock bedside table.",
        f"Travel jet lag—familiar calm scent.",
        f"Corporate wellness gift hit.",
        f"First stress attar—keeping.",
        f"Honest—not medical treatment, self care yes.",
        f"Evening chai plus scent—Indian unwind.",
        f"4 star—wish stronger for panic moments. Daily calm ok.",
        f"Fabric pajama hold—morning faint calm.",
        f"Kid exam season household calm attempt.",
        f"Meditation adjacent—not full chakra just calm.",
        f"Breathwork class recommendation worked.",
        f"Sensitive nose office safe calm scent.",
        f"Monsoon extra dab once—still calm.",
        f"Winter evening bath then attar—cozy.",
        f"Summer light calm—not cloying.",
        f"Instagram wellness reel—tried sceptical.",
        f"Friend therapist recommended scent ritual—why not.",
        f"Honest drawback bottle small for nightly use.",
        f"Worth it cheaper than weekly stress coffee.",
        f"Mast shaam ka ritual—mann halka.",
        f"Baarish terrace calm—seasonal favorite.",
        f"Subtle projection—bedroom appropriate.",
        f"First Anand Rasa stress—brand trust.",
        f"Repeat third bottle consistency.",
        f"Compliment calmer demeanor colleague said.",
        f"Layer coconut oil sleep longevity.",
        f"Honest 5 stars nightly user.",
        f"Panic attack companion not fix—grounding tool.",
        f"Office drawer emergency dot.",
        f"Premium calm—not spa cheap lavender.",
        f"Slow routine build week two habit.",
        f"Yoga mat nearby scent association.",
        f"Travel hotel unfamiliar—scent home.",
        f"Sensitive skin nightly—no rash.",
        f"Gift stressed friend—thank you note.",
        f"Honest—placebo maybe, still worth.",
        f"Evening news detox scent ritual.",
        f"4 stars cap hard open tired hands.",
        f"Worth stress collection purpose matched.",
        f"Quiet room scent literal.",
        f"Repeat subscription wish.",
        f"Sach bolu calm mind helper.",
        f"Desk plant and attar—WFH calm.",
        f"Commute audiobook plus scent—decompress.",
        f"Family noticed less snapping—win.",
        f"Premium packaging self care respect.",
        f"Honest drawback not instant zen.",
        f"First attar calm entry perfect.",
        f"Meditation light support—not distraction.",
        f"Worth it sleep quality peripheral help.",
        f"Monsoon anxiety seasonal match.",
        f"Repeat customer stress only line.",
        f"Honest 4 star—some days subtle.",
        f"Calm mind marketing delivered enough.",
        f"Evening walk decompress scent.",
        f"Sensitive calm—no synthetic blast.",
        f"Gift mother retirement calm routine.",
        f"Worth premium per peaceful evening.",
        f"Mast office stress antidote.",
        f"Baarish sleep better ritual.",
        f"Subtle hug scent description accurate.",
        f"First bottle month lasted nightly dots.",
        f"Honest review stress realistic expectations.",
        f"Yoga teacher approved ingredients.",
        f"Repeat restock must not run out.",
        f"Calm without drowsy—important.",
        f"Worth trying before heavier meds only doctor—self care.",
        f"Sach bolu evening relaxation real.",
    ]


def _perfume_bodies():
    return [
        f"Office Monday {SHORT}—elevator safe, meeting safe. Subtle professional.",
        f"Client lunch compliment—after not during. Classy.",
        f"Airport travel one bottle ten days—consistent.",
        f"Hotel lobby scent memory—business trip staple.",
        f"Brunch outing fresh—not brunch syrup sweet.",
        f"Humid wedding guest—held without reapply marathon.",
        f"Sensitive skin alcohol perfume rash—oil base fine.",
        f"Perfume rotation slot—weekday office.",
        f"Evening dinner transition—same bottle works.",
        f"Modern fragrance soul attar—hybrid accurate.",
        f"Long lasting neck dot—6 hours realistic.",
        f"4 stars—opening office sharp, dry-down saves.",
        f"Layer light EDT depth—experiment success.",
        f"Gift colleague farewell—professional thoughtful.",
        f"First perfume series try—impressed.",
        f"Saffron sandal heritage—perfume page honest.",
        f"Skin safe daily wear—no irritation month.",
        f"Commute metro subtle—no choke.",
        f"WFH video call safe—camera can't smell win.",
        f"Presentation day confidence—not loud.",
        f"Travel pouch leak test passed.",
        f"Repeat office bottle—third restock.",
        f"Premium soft dry-down—expensive right feeling.",
        f"Honest—not designer clone, own character.",
        f"Summer AC office—projection moderate perfect.",
        f"Winter scarf carry—beautiful.",
        f"Monsoon humidity behaved—one extra dab.",
        f"Compliment HR onboarding—friendly.",
        f"Kid school pickup safe scent.",
        f"Fabric shirt hold next day faint.",
        f"Corporate gift perfume series—clients liked.",
        f"Instagram discovery cautious—converted.",
        f"Alcohol free claim—skin happier.",
        f"Slow bloom perfume style—hour one best.",
        f"Honest drawback wish 50ml option.",
        f"Worth daily wear cost per use low.",
        f"Mast office signature—subtle premium.",
        f"Baarish WFH scent cozy professional.",
        f"First Anand Rasa perfume not attar—gateway.",
        f"Evening gym then dinner—versatile.",
        f"Sensitive migraine—no trigger.",
        f"Gift husband office—uses daily.",
        f"Premium packaging desk worthy.",
        f"Repeat customer perfume series loyal.",
        f"Honest 5 stars travel essential.",
        f"Layer moisturizer longevity boost.",
        f"Book club evening—compliment.",
        f"4 star delivery box dent—scent fine.",
        f"Worth perfume series description match.",
        f"Modern Indian fragrance accurate label.",
        f"Conference name tag scent memory.",
        f"Subtle compliment magnet—not beast.",
        f"First bottle two months light use.",
        f"Honest review office realistic.",
        f"Weekend brunch weekday office same bottle.",
        f"Premium feel bottle weight quality.",
        f"Repeat wedding season guest.",
        f"Sach bolu daily driver potential.",
        f"Headache prone passed test.",
        f"Gift sister job promotion—fit.",
        f"Honest—not nightclub scent—thank god.",
        f"Travel international flight—no leak.",
        f"Summer wedding guest survived.",
        f"Winter boardroom appropriate.",
        f"Monsoon client indoor meeting ok.",
        f"Compliment stranger rare airport.",
        f"Kid noticed nice—home ok.",
        f"Premium worth switch from alcohol.",
        f"Slow appreciation week two depth.",
        f"Honest drawback cap tight.",
        f"First attar perfume hybrid—education.",
        f"Worth exploring full series.",
        f"Mast compliments without announcing.",
        f"Baarish office commute calm.",
        f"Subtle satin dry-down accurate.",
        f"Repeat restock subscription wish.",
        f"Honest 4 star projection wish more.",
        f"Gift set perfume highlight star.",
        f"Sensitive skin month trial fine.",
        f"Corporate diwali perfume gifts hit.",
        f"Worth premium everyday luxury.",
        f"Office wear primary use confirmed.",
        f"Evening dinner same scent works.",
        f"Honest review travel tested.",
        f"First Anand Rasa perfume—more orders.",
        f"Layer experiment vanilla too sweet solo best.",
        f"Premium boutique gift worthy.",
        f"Repeat third bottle batch same.",
        f"Sach bolu office safe true.",
        f"Humidity hold wedding tested.",
        f"Honest 5 stars daily wear.",
    ]


def _luxury_bodies():
    return [
        f"Gallery opening {SHORT}—elegant dry-down, not shouty wealth.",
        f"Boardroom dinner appropriate—refined sillage.",
        f"Client gifting premium—thank you call received.",
        f"Resort stay bathroom display worthy bottle.",
        f"Collector shelf addition—typography matches.",
        f"Art preview subtle sophistication.",
        f"Black tie event wrist dot enough.",
        f"Vanity display pride—guests ask brand.",
        f"Heritage hotel stay scent memory luxury.",
        f"Wine pairing dinner—controlled richness.",
        f"Premium quality evident pour to dry-down.",
        f"Elegant bottle weight—luxury signal subtle.",
        f"Long lasting without loud—sophisticated.",
        f"4 stars—price high, quality matches mostly.",
        f"Refined fragrance not trendy flash.",
        f"Velvety heart note—premium accurate.",
        f"Gift CEO retirement—appropriate tone.",
        f"First luxury attar—benchmark set.",
        f"Honest—not designer name flex, quality flex.",
        f"Repeat luxury line third bottle.",
        f"Sensitive skin premium gentle.",
        f"Travel five star hotel—scent fits.",
        f"Compliment understated wealth whisper.",
        f"Fabric silk hold 24h faint elegant.",
        f"Corporate luxury gift list staple.",
        f"Instagram luxury reel sceptical—pleased.",
        f"Alcohol perfume downgrade—prefer oil luxury.",
        f"Slow luxury reveal hour two best.",
        f"Honest drawback small bottle luxury prices.",
        f"Worth splurge occasions.",
        f"Mast refined—ekdum classy.",
        f"Baarish indoor luxury cozy.",
        f"Premium packaging unbox ceremony.",
        f"First Anand Rasa luxury—trust.",
        f"Evening opera scent appropriate.",
        f"Sensitive migraine no trigger.",
        f"Gift parents anniversary luxury—touched.",
        f"Repeat customer luxury only.",
        f"Honest 5 stars special events.",
        f"Layering oud fail solo luxury best.",
        f"Book launch author wore—compliment.",
        f"4 star projection discrete maybe too.",
        f"Worth luxury collection promise.",
        f"Sophisticated without old person smell.",
        f"Conference luxury networking subtle.",
        f"Subtle premium feel accurate.",
        f"First bottle preserved special occasions.",
        f"Honest review luxury expectations met.",
        f"Winter gala shawl scent beautiful.",
        f"Summer garden party survived elegant.",
        f"Monsoon indoor luxury appropriate.",
        f"Compliment jeweller shop—funny.",
        f"Kid said fancy—cute.",
        f"Premium worth gift wealthy friend.",
        f"Slow appreciation connoisseur pace.",
        f"Honest drawback not daily for budget.",
        f"First attar luxury tier—impressed.",
        f"Worth exploring oud sandal siblings.",
        f"Mast bottle shelf eye candy.",
        f"Baarish reading nook luxury scent.",
        f"Subtle wealth appropriate India context.",
        f"Repeat restock special bottle.",
        f"Honest 4 star wish bigger size.",
        f"Gift wedding wealthy couple—hit.",
        f"Sensitive skin luxury gentle.",
        f"Corporate VIP gift premium.",
        f"Worth price per memorable wear.",
        f"Luxury hotel amenity comparison wins.",
        f"Evening whiskey pairing joke—scent fit.",
        f"Honest—not flashy gold bottle—tasteful.",
        f"Travel luxury weekend one bottle.",
        f"Premium creaminess dry-down real.",
        f"Repeat collector mentality.",
        f"Sach bolu sophisticated true.",
        f"Headache prone passed.",
        f"Gift mother luxury milestone—cried.",
        f"Honest review luxury realistic.",
        f"First luxury purchase Anand Rasa—more.",
        f"Layer moisturizer rich longer.",
        f"Premium memorable gift confirmed.",
        f"Repeat third batch consistent.",
        f"Honest 5 stars refinement.",
        f"Wedding luxury guest scent.",
        f"Mast elegant dry-down.",
        f"Baarish luxury tea time.",
        f"Subtle controlled richness.",
        f"Worth luxury label earned.",
        f"Honest drawback casual daily overkill.",
        f"First bottle anniversary opened.",
        f"Sach bolu premium quality.",
    ]


def _spiritual_bodies():
    return [
        f"Temple morning {SHORT}—diya smoke complement natural.",
        f"Puja thali ready scent—ritual cue.",
        f"Aarti evening staple—devotional warm.",
        f"Retreat week silent—scent quiet perfect.",
        f"Pilgrimage trip bottle—sacred memory.",
        f"Priest blessing day wore—no vanity feel.",
        f"Diya lighting scent pairing—home mandir.",
        f"Chanting hour anchor—breath slow.",
        f"Sacred thread ceremony—appropriate subtle.",
        f"Guru dakshina gift—accepted warmly.",
        f"Frankincense layer vibe—spiritual not churchy.",
        f"Sandal note authentic—temple memory.",
        f"Ghar shanti feel—peace home.",
        f"Breath slow marketing—actually helps.",
        f"4 stars—projection zero temple ok.",
        f"Ketu moksha lite—meditation before puja.",
        f"Crown divine calm—morning sit.",
        f"Nag champa adjacent—cleaner attar version.",
        f"Kesar chandan puja mood—warm sacred.",
        f"Incense plus attar ritual layered.",
        f"First spiritual attar—keeping.",
        f"Honest—not miracle, devotion helper.",
        f"Sensitive skin puja daily fine.",
        f"Gift spiritual mother—daily use.",
        f"Repeat temple visit scent.",
        f"Travel Char Dham—bottle sacred.",
        f"Compliment pandit casual—validation.",
        f"Fabric kurta hold puja long.",
        f"Corporate diwali spiritual gift ok.",
        f"Instagram sadhana reel—tried.",
        f"Alcohol free skin prayer friendly.",
        f"Slow spiritual appreciation.",
        f"Honest drawback casual wear less.",
        f"Worth spiritual collection purpose.",
        f"Mast puja scent—authentic.",
        f"Baarish indoor puja cozy.",
        f"Subtle devotional perfect.",
        f"First Anand Rasa spiritual—explore.",
        f"Evening aarti habit formed.",
        f"Sensitive migraine no trigger.",
        f"Gift father retirement puja—uses.",
        f"Repeat third bottle mandir.",
        f"Honest 5 stars ritual.",
        f"Layer coconut oil tradition.",
        f"Book scripture study scent.",
        f"4 star wish temple booklet.",
        f"Worth spiritual alignment note.",
        f"Quiet perfect description match.",
        f"Family puja collective scents.",
        f"Subtle temple cotton vibe.",
        f"First attar spiritual entry.",
        f"Honest review believer respectful.",
        f"Winter morning puja warm.",
        f"Summer temple queue calm.",
        f"Monsoon indoor sacred cozy.",
        f"Compliment grandmother approved.",
        f"Kid calm puja—bonus.",
        f"Premium packaging prasad style respect.",
        f"Slow routine month habit.",
        f"Honest—not replace sincerity.",
        f"Worth trying spiritual curious.",
        f"Meditation before office spiritual lite.",
        f"Baarish prayer extra peaceful.",
        f"Subtle sthir mann feel.",
        f"Repeat restock must.",
        f"Honest 4 star opening sharp.",
        f"Gift guru birthday—touched.",
        f"Sensitive skin daily puja.",
        f"Corporate retreat spiritual bags.",
        f"Worth premium ritual tool.",
        f"Travel temple hopping scent.",
        f"Honest review spiritual realistic.",
        f"First bottle festival opened.",
        f"Sach bolu peaceful puja.",
        f"Headache prone passed.",
        f"Gift sister mundan—appropriate.",
        f"Honest drawback not perfume party.",
        f"Repeat customer spiritual line.",
        f"Evening scripture scent.",
        f"Premium devotional—not cheap incense vibe.",
        f"Honest 5 stars morning puja.",
        f"Worth spiritual philosophy match.",
        f"Mast diya pairing.",
        f"Baarish ghar mandir scent.",
        f"Subtle authentic feel.",
        f"First Anand Rasa—spiritual hook.",
        f"Layer incense attar complete.",
        f"Honest review years use now.",
        f"Sach bolu ritual enhanced.",
    ]


def _bestseller_bodies():
    return [
        f"Pehla Anand Rasa order bestseller se—{SHORT} hype justified.",
        f"Friend referral—same bottle she swore by.",
        f"Instagram reel discovery—cautious, converted.",
        f"Repeat restock fourth bottle—fan favorite real.",
        f"Festival rush buy—delivery ok, scent consistent.",
        f"Office colleague tip—team small cult.",
        f"Family recommendation mother—generational win.",
        f"Cart add-on curiosity—best impulse.",
        f"Anniversary splurge bestseller—worth.",
        f"Crowd favorite accurate—understand why.",
        f"Worth hype without disappointment.",
        f"Balanced wear daily possible.",
        f"Signature pick potential—trying.",
        f"Daily driver week three—confirmed.",
        f"Gift safe bestseller—recipient pleased unknown taste.",
        f"Consistent quality three orders—trust.",
        f"4 stars—personal taste not wow all notes.",
        f"Reliable hold fabric skin.",
        f"First attar bestseller entry—gateway.",
        f"Honest—bestseller reason universal appeal.",
        f"Sensitive skin crowd pleasing gentle.",
        f"Travel tried true bestseller only.",
        f"Compliment generic good way.",
        f"Premium feel bestseller price fair.",
        f"Repeat subscription wish.",
        f"Corporate gift bestseller safe.",
        f"Wedding guest universally ok.",
        f"Monsoon behaved bestseller.",
        f"Winter daily bestseller cozy.",
        f"Summer light enough surprise.",
        f"Kid noticed nice—family.",
        f"Layer moisturizer standard boost.",
        f"Honest drawback not unique—reliable.",
        f"Worth bestseller label earned.",
        f"Mast safe first buy.",
        f"Baarish comfort bestseller.",
        f"Subtle crowd pleaser.",
        f"First bottle month lasted.",
        f"Honest review hype realistic.",
        f"Restock must not out.",
        f"Gift brother unknown—hit.",
        f"Sensitive migraine passed.",
        f"Premium packaging pleasant.",
        f"Repeat customer Anand Rasa because bestseller.",
        f"Honest 5 stars reliable.",
        f"Office safe bestseller confirmed.",
        f"Travel essential one bottle.",
        f"Compliment wedding common.",
        f"Slow love some, instant others.",
        f"Honest 4 star want more unique.",
        f"Worth exploring niche after.",
        f"Build box bestseller pick—smart.",
        f"Discovery kit star—agreed.",
        f"First order hooked brand.",
        f"Sach bolu fan favorite.",
        f"Headache prone ok.",
        f"Gift parents safe.",
        f"Honest—not life changing—very good.",
        f"Repeat festival stock up.",
        f"Premium consistent batches.",
        f"Honest review referral source.",
        f"Summer wedding guest ok.",
        f"Winter scarf hold.",
        f"Monsoon one extra dab.",
        f"Compliment colleague standard.",
        f"Kid school safe.",
        f"Worth price daily math.",
        f"Mast restock item.",
        f"Baarish indoor comfort.",
        f"Subtle reliable.",
        f"First attar bestseller—more collections.",
        f"Honest drawback popularity means common.",
        f"Repeat third year customer.",
        f"Gift set highlight bestseller.",
        f"Sensitive skin month fine.",
        f"Corporate safe gift.",
        f"Worth trying if new brand.",
        f"Travel pouch bestseller only.",
        f"Honest 5 stars dependable.",
        f"Office elevator tested.",
        f"Premium feel not premium price.",
        f"Slow appreciation optional.",
        f"Honest review bestseller role.",
        f"Wedding season fatigue still good.",
        f"Mast introductory bottle.",
        f"Sach bolu worth ordering.",
        f"Restock alert on.",
        f"Honest 4 star personal preference.",
        f"First Anand Rasa—bestseller correct.",
        f"Layer simple best.",
        f"Premium reliable gift.",
        f"Repeat loyal staple.",
        f"Honest review crowd truth.",
        f"Worth hype test passed.",
    ]


def _incense_bodies():
    return [
        f"Morning puja {SHORT}—clean smoke, ash kam. Pooja staple.",
        f"Evening aarti home mandir—traditional feeling authentic.",
        f"Yoga studio corner—students comment peaceful.",
        f"Meditation room slow burn—1.5 hour claim tested ok.",
        f"Diwali week daily—guests ask brand.",
        f"Satyanarayan katha—smoke gentle, headache nahi.",
        f"Monsoon indoors incense cozy—ventilation still.",
        f"Guest room welcome stick—subtle hospitality.",
        f"Sunday clean-up ritual—fresh sacred air.",
        f"Nag champa type lover—this cleaner variant.",
        f"Lavender evening calm—sleep routine adjacent.",
        f"Kesar chandan festive—warm sacred accurate.",
        f"Musk rose ambiance—quiet romantic room not skin.",
        f"Jasmine generic peaceful—meditation deepened.",
        f"Hand rolled feel—natural ingredients trust.",
        f"Slow burn stick length good—value.",
        f"4 stars—smoke sensitive need window open.",
        f"Ash minimal claim—mostly true.",
        f"Holder important—packaging could include.",
        f"First incense Anand Rasa—repeat.",
        f"Honest—not skin perfume—room fragrance.",
        f"Temple visit memory—home replicate lite.",
        f"Sensitive asthma cautious—mild ok distance.",
        f"Gift mother puja—monthly restock.",
        f"Repeat box third—consistent.",
        f"Travel not applicable—home use.",
        f"Compliment neighbor puja day—funny.",
        f"Premium sticks burn even—no crackle waste.",
        f"Corporate diwali incense gift—appropriate.",
        f"Instagram puja reel product—works.",
        f"Honest drawback shorter than claimed once.",
        f"Worth incense collection description.",
        f"Mast morning puja—traditional.",
        f"Baarish indoor incense cozy ventilated.",
        f"Subtle trail room calm.",
        f"First agarbatti premium—impressed.",
        f"Evening wind down stick—habit.",
        f"Sensitive smoke mild version ok.",
        f"Gift father temple—uses daily.",
        f"Repeat festival stock.",
        f"Honest 5 stars puja use.",
        f"Layer attar after incense—complete ritual.",
        f"Book reading nook incense—cozy.",
        f"4 star packaging plastic wish less.",
        f"Worth natural sticks premium.",
        f"Home shrine staple confirmed.",
        f"Family puja shared box.",
        f"Subtle sacred air accurate.",
        f"First incense switch from cheap—quality jump.",
        f"Honest review burn time realistic.",
        f"Winter closed windows careful—still ok.",
        f"Summer morning open door—perfect.",
        f"Monsoon humidity storage dry—important.",
        f"Compliment priest visit—embarrassing proud.",
        f"Kid homework room mild—calm.",
        f"Premium packaging gift diwali.",
        f"Slow habit daily stick.",
        f"Honest—not luxury hotel—home temple.",
        f"Worth trying one box minimum.",
        f"Meditation app timer one stick—fit.",
        f"Baarish puja extra cozy.",
        f"Subtle clean smoke true.",
        f"Repeat subscription wish.",
        f"Honest 4 star smoke strength variable batch.",
        f"Gift set incense highlight.",
        f"Sensitive headache mild ok.",
        f"Corporate temple inauguration gift.",
        f"Worth premium over market loose.",
        f"Travel not—but carry small pack puja.",
        f"Honest review incense role clear.",
        f"First Anand Rasa incense—attar next.",
        f"Layer diya incense stick—complete.",
        f"Premium hand rolled feel.",
        f"Repeat loyal incense only brand.",
        f"Honest 5 stars daily puja.",
        f"Wedding house puja box gift.",
        f"Mast traditional feeling.",
        f"Baarish indoor sacred.",
        f"Subtle room fragrance hours.",
        f"First box lasted month daily.",
        f"Sach bolu pooja staple.",
        f"Headache prone mild sticks only ok.",
        f"Gift mother in law—success.",
        f"Honest drawback not perfume substitute.",
        f"Repeat restock must.",
        f"Evening aarti habit.",
        f"Premium worth ritual respect.",
        f"Honest review burn clean.",
        f"Yoga class donation box—popular.",
        f"Worth incense collection promise.",
    ]


def _gift_bodies():
    return [
        f"Birthday hamper {SHORT}—unboxing wow genuine scream.",
        f"Wedding return gift—guests praised presentation premium.",
        f"Corporate diwali hamper—clients photo sent thank you.",
        f"Mother's day box—mom display console keeps.",
        f"Housewarming ribbon quality—hosts touched.",
        f"Anniversary box couple—both scents loved.",
        f"Festive hamper diwali—ribbon worthy reels.",
        f"Thank you gift boss—professional elegant.",
        f"Bridal trousseau addition—aunt approved luxury.",
        f"Client appreciation—deal closed after? joke maybe.",
        f"Premium packaging unbox ceremony—worth video.",
        f"Gift memory lasting—recipient remembers brand.",
        f"Hamper star product—{SHORT} highlight rest good.",
        f"Keepsake box reused jewelry—bonus.",
        f"Festive wrap aesthetic—Instagram worthy.",
        f"Premium reveal slow open—respect.",
        f"4 stars—hamper heavy shipping cost.",
        f"Discovery kit 3 attars—smart try all.",
        f"Build box 5 attars—custom feel luxury.",
        f"First gift set order—recipient converted customer.",
        f"Honest—not cheap gift basket—thoughtful.",
        f"Sensitive recipient skin—no issues reported.",
        f"Repeat corporate diwali order third year.",
        f"Travel gift hand carry—secure pack.",
        f"Compliment recipient public—giver proud.",
        f"Premium presentation matched price.",
        f"Wedding season bulk gifts—consistent quality.",
        f"Instagram gift reel inspired—delivered.",
        f"Honest drawback wish note card included.",
        f"Worth gift sets premium label.",
        f"Mast unboxing experience.",
        f"Baarish delivery dry inside—packing good.",
        f"Subtle luxury gift not flashy.",
        f"First Anand Rasa gift—self order next.",
        f"Evening gift handover—emotional.",
        f"Sensitive packaging no damage.",
        f"Gift husband birthday—uses daily.",
        f"Repeat gift different sets—all hit.",
        f"Honest 5 stars gifting purpose.",
        f"Layer not applicable gift—but recipient happy.",
        f"Book club secret santa—winner.",
        f"4 star one bottle cap loose fixed.",
        f"Worth discovery kit entry brand.",
        f"Shareable set sisters fought nicely.",
        f"Festive gift timing delivery tight ok.",
        f"Subtle thank you scent memory.",
        f"First gift nervous—success.",
        f"Honest review gift giver perspective.",
        f"Winter wedding return gift appropriate.",
        f"Summer birthday melt worry—ok cool pack.",
        f"Monsoon hamper dry—sealed well.",
        f"Compliment mother in law rare.",
        f"Kid helped wrap—cute.",
        f"Premium ribbon reuse.",
        f"Slow gift planning worth.",
        f"Honest—not personal scent pick—safe sets.",
        f"Worth build box customization.",
        f"Travel gift international friend—arrived.",
        f"Honest 5 stars corporate repeat.",
        f"Office secret santa budget stretch worth.",
        f"Premium hamper photo wall—marketing organic.",
        f"Repeat festival corporate list.",
        f"Sach bolu gift memory real.",
        f"Headache prone recipient ok.",
        f"Gift parents  anniversary—cried.",
        f"Honest drawback price premium.",
        f"Repeat customer gift giver only.",
        f"Evening hand delivery special.",
        f"Premium worth special occasions.",
        f"Honest review packaging focus fair.",
        f"Wedding favours small sets—cute.",
        f"Mast festive wrap.",
        f"Baarish gift delivery ok.",
        f"Subtle luxury presentation.",
        f"First gift set Anand Rasa—loyal.",
        f"Honest 4 star delivery date slip.",
        f"Discovery kit gateway recipient ordered more.",
        f"Sensitive skin gift set mild options.",
        f"Corporate HR gift inclusive.",
        f"Worth premium gifting experience.",
        f"Travel hamper not—but ship well.",
        f"Honest review recipient feedback aggregated.",
        f"First diwali corporate—all praised.",
        f"Sach bolu premium reveal.",
        f"Repeat annual gift ritual.",
        f"Honest 5 stars presentation.",
        f"Gift sister wedding—highlight.",
        f"Mast ribbon quality.",
        f"Baarish unboxing dry.",
        f"Subtle elegant gift.",
        f"Worth gift sets collection.",
        f"Honest drawback personalization limited.",
        f"Repeat build box custom.",
        f"Premium gift trust brand.",
        f"Honest review giver recommend.",
    ]


GENERATORS = {
    "love": _love_bodies,
    "stress": _stress_bodies,
    "perfume": _perfume_bodies,
    "luxury": _luxury_bodies,
    "spiritual": _spiritual_bodies,
    "bestseller": _bestseller_bodies,
    "incense": _incense_bodies,
    "gift": _gift_bodies,
}
