"""Complete-sentence review banks for each collection axis."""

from __future__ import annotations


def _bank(open_: list[str], mid: list[str], close: list[str] | None = None, short: list[str] | None = None) -> dict:
    return {"open": open_, "mid": mid, "close": close or [], "short": short or []}


# ---------------------------------------------------------------------------
# Incense — room, puja, burn, smoke, guests
# ---------------------------------------------------------------------------
_INCENSE_OPEN = [
    "I bought this during Diwali after a neighbour mentioned it at our housing society function.",
    "My second box arrived last week and the quality still feels the same as the first one.",
    "We started burning one stick every morning before everyone leaves for work.",
    "This was part of a gift hamper my sister sent from Bangalore last month.",
    "I first noticed the fragrance at my cousin's house during evening aarti.",
    "My mother asked me to reorder this before our weekend family puja.",
    "Honestly, I was not expecting the room to smell this pleasant so quickly.",
    "Our pujari suggested we try a cleaner incense and this turned out to be a good pick.",
    "I picked this up online after reading a few reviews about low smoke.",
    "The sticks arrived well packed and none of them were broken in transit.",
    "We keep a box in the prayer room and another near the balcony door.",
    "After shifting to a new flat, I wanted something gentle for daily puja.",
    "My wife prefers mild fragrances and this one does not feel overpowering.",
    "I tried this during Navratri and ended up ordering again before the festival ended.",
    "Guests commented on the aroma during our housewarming puja last Sunday.",
    "I usually buy incense from the local shop but wanted to try something new.",
    "My father-in-law lit one stick during morning prayer and liked it immediately.",
    "We burn one stick while meditating and the room stays calm for a while.",
    "I ordered this for our temple room after the old stock finished.",
    "The fragrance feels clean and does not give me a headache like some others do.",
    "My daughter noticed the smell as soon as she walked in from tuition.",
    "I bought a box for my parents and they have already asked for a refill.",
    "During monsoon the flat felt damp and this helped the prayer room smell fresh.",
    "I was looking for something that burns slowly without too much ash.",
    "Our morning puja feels more settled when this is lit in the background.",
    "I first tried a single stick from a friend's box and placed an order the same week.",
    "The smoke stays light even when we keep the windows closed during winter.",
    "I keep one stick burning while reading in the evening and it feels peaceful.",
]

_INCENSE_MID = [
    "One stick fills the prayer room within ten minutes without feeling heavy.",
    "The burn is slow and the ash does not scatter across the floor.",
    "Evening aarti feels calmer when this is lit near the mandir.",
    "The fragrance lingers softly after the stick finishes burning.",
    "There is less smoke than I expected and the room does not feel stuffy.",
    "My mother likes that the smell is noticeable but not sharp.",
    "We can sit in the living room while puja is on and it still feels comfortable.",
    "The sticks light easily and do not keep going out midway.",
    "Guests have asked what we use because the aroma feels pleasant and natural.",
    "I appreciate that the fragrance does not clash with the camphor and diya.",
    "The room smells fresh even an hour after we finish morning prayers.",
    "It works well for a short meditation session before breakfast.",
    "The packaging keeps the sticks intact and they smell fresh when opened.",
    "We use it on festival days when relatives visit and nobody complained about smoke.",
    "The fragrance spreads evenly and does not feel concentrated in one corner.",
    "I like that I do not need to open a window every time we light incense.",
    "The sticks last long enough for our usual puja without burning too fast.",
    "My husband who is sensitive to strong smells had no issue with this.",
    "The aroma feels warm and familiar rather than like artificial room freshener.",
    "We have been using it daily for three weeks and the quality seems consistent.",
    "It pairs nicely with our evening tea ritual on the balcony.",
    "The prayer room feels more inviting when relatives come for weekend visits.",
    "I noticed less residue on the holder compared to what we used before.",
    "The fragrance stays gentle even if we light two sticks on busy festival mornings.",
    "Our help mentioned that cleaning ash from the holder is easier with these sticks.",
    "It does not leave a harsh smell on curtains or upholstery nearby.",
    "The scent feels balanced during both morning and evening rituals.",
    "I feel comfortable using it when my elderly parents are at home.",
]

_INCENSE_CLOSE = [
    "We plan to stock up before the next festival season.",
    "I am happy to keep this as part of our daily puja routine.",
    "Will order again once this box is halfway done.",
    "My family has already added it to the monthly grocery list.",
    "Glad I switched from the stronger incense we used earlier.",
    "This has become our regular choice for home prayers.",
    "I would recommend it to anyone who wants a milder room fragrance.",
    "Overall, a simple purchase that has worked well for us.",
    "No complaints so far and the price feels fair for the quality.",
    "I am satisfied enough to gift a box to my sister next month.",
    "It does what we need without any fuss.",
    "We will continue using this for daily and festive puja alike.",
    "Happy with how consistent the fragrance has been across sticks.",
    "This is staying in our prayer room for the foreseeable future.",
    "A good find for anyone who wants clean smoke and a soft aroma.",
    "I feel it was worth trying and we will reorder soon.",
    "My parents approved and that was the main test for me.",
    "Simple, reliable, and pleasant for everyday use at home.",
    "I did not expect much from an online order but this exceeded my expectations.",
    "Comfortable recommending it to friends who ask about home puja setups.",
]

_INCENSE_SHORT = [
    "We burn one stick every morning before puja and the room smells fresh within minutes. My mother prefers this over the stronger incense we used earlier.",
    "I ordered this for Diwali and we have continued using it on regular weekdays too. The smoke stays light and the fragrance feels natural.",
    "Guests noticed the aroma during our housewarming and asked where we bought it from. I am planning to order another box before the next family gathering.",
    "The sticks burn slowly and the prayer room feels calm during evening aarti. I am happy with this purchase and will reorder when the box finishes.",
    "I was looking for something gentle for daily use and this has worked well for three weeks now. No headaches and no heavy smoke in our small flat.",
    "My father lit one during morning prayer and asked me to keep a spare box at home. That is enough validation for me to continue buying it.",
    "The fragrance is soft but you can notice it in the living room while puja is on in the next room. Simple and effective for our routine.",
    "I tried many local options before this and the difference in ash and smoke is noticeable. Glad I made the switch for daily rituals.",
    "We use it during meditation on weekends and the room stays pleasant for a good while. Will gift a box to my sister for her new home altar.",
    "Honestly, I did not expect an online incense order to work this well for daily puja. The quality has been consistent across the whole box so far.",
    "Navratri week was busy with visitors and this handled back-to back puja without feeling overpowering. Already on my reorder list.",
    "The prayer room smells clean after the stick burns out and does not leave a stale note. My wife and I both like it for evening rituals.",
    "I keep one near the balcony during morning chai and it adds a nice calm feeling. Not fancy, just does the job well every day.",
    "Our temple room feels more welcoming when this is lit before relatives arrive. I am satisfied and will continue using it regularly.",
    "Low smoke was my main requirement and this delivered on that without compromising on fragrance. Good purchase for apartment living.",
]

# ---------------------------------------------------------------------------
# Perfume / attar — skin, clothes, compliments, longevity
# ---------------------------------------------------------------------------
_PERFUME_OPEN = [
    "I bought this after reading a few reviews and wore it to office the next day.",
    "My second bottle arrived today and I am glad the scent still feels the same.",
    "A friend let me try a drop at her wedding and I ordered my own bottle soon after.",
    "I usually avoid strong attars but decided to try this on a colleague's recommendation.",
    "This was part of a gift hamper from my brother and I started using it immediately.",
    "I wore it for a family gathering last weekend and got a compliment from my aunt.",
    "Honestly, I was not sure it would last through my commute but it did.",
    "I picked this for everyday wear because I wanted something balanced and not loud.",
    "My wife noticed the fragrance before I even told her I had changed perfumes.",
    "I first tried a sample at the store and liked how it settled on my skin.",
    "I have almost finished my first bottle and already placed a reorder.",
    "I wore this to a cousin's engagement and it felt appropriate for the occasion.",
    "I wanted something subtle for office meetings and this has worked well so far.",
    "My mother liked it when I visited her and asked me to bring a bottle next time.",
    "I bought this during the wedding season and kept reaching for it on most days.",
    "I was looking for a daily fragrance that would not feel heavy in humid weather.",
    "A relative gifted this to my father and he passed a bottle to me to try.",
    "I wore one small dab before an evening dinner and it lasted till I reached home.",
    "I had been using the same scent for years and this was a pleasant change.",
    "I tried it on my kurta collar and could still notice it after returning from work.",
    "My sister said it smells refined without being too sharp for daytime wear.",
    "I ordered online because the local shop did not have this variant in stock.",
    "I wore it on a rainy Monday and it still felt fresh by late afternoon.",
    "I keep it on my dresser and use a small amount before leaving the house.",
    "I was hesitant about buying attar online but the experience has been good.",
    "I wore this to a temple visit and appreciated that it stayed close and polite.",
    "My husband commented that it smells warm rather than overpowering.",
    "I bought it as a treat after a busy month at work and have no regrets.",
]

_PERFUME_MID = [
    "The opening feels soft and it settles into something calm on the skin.",
    "I could still catch a hint of it on my sleeve after a long day at the desk.",
    "It does not shout across the room but people nearby do notice it politely.",
    "One small application was enough for my usual office hours.",
    "The dry down feels comfortable and not itchy on my skin.",
    "I received a quiet compliment from a teammate during lunch.",
    "It layers nicely with my usual unscented moisturiser without turning odd.",
    "The fragrance stays close and does not give me a headache in AC offices.",
    "I like that it feels present in the morning but never cloying by evening.",
    "My kurta still had a faint trace when I changed after coming home.",
    "It works for both weekday wear and small family functions.",
    "The scent feels balanced and not overly sweet for Indian weather.",
    "I did not need to reapply during a six hour workday.",
    "It feels appropriate for meetings without drawing too much attention.",
    "The bottle dispenses a small amount so it is easy to control usage.",
    "My skin usually reacts to strong perfumes but this felt gentle.",
    "It smells better after fifteen minutes than right at the first dab.",
    "I wore it in a crowded market and it did not feel suffocating.",
    "The fragrance has a warm character that suits evening dinners well.",
    "I appreciate that it does not clash with the soap or deodorant I use.",
    "Friends asked what I was wearing because it smelled clean and pleasant.",
    "It feels like something I can wear regularly without getting tired of it.",
    "The longevity was better than I expected for the amount I used.",
    "It sits nicely on fabric and does not stain the collars I tried.",
    "I felt comfortable wearing it around older relatives who dislike loud scents.",
    "The projection is soft which is exactly what I wanted for daily use.",
    "It has become my go-to before leaving for work on most mornings.",
    "Even my driver mentioned it smelled nice when I got into the car.",
]

_PERFUME_CLOSE = [
    "I am happy to keep this as my everyday fragrance for now.",
    "Will buy another bottle once I am halfway through this one.",
    "Glad I took the chance instead of sticking to my old perfume.",
    "Overall, a solid purchase that matched what I was looking for.",
    "I would gift this to a friend who likes subtle attars.",
    "No major complaints and the experience has been consistent.",
    "This has earned a permanent spot on my dresser.",
    "I feel it was worth the price for the wear I get.",
    "Comfortable recommending it for office and family gatherings.",
    "I plan to try another variant from the same range soon.",
    "My family approved and that matters more than marketing claims.",
    "Simple, reliable, and pleasant for regular Indian weather.",
    "I am satisfied enough to write this review after three weeks of use.",
    "It does what I need without feeling like a special occasion only scent.",
    "Happy with the purchase and the delivery was smooth too.",
    "I did not expect much but this turned out better than I thought.",
    "Will reorder unless something unexpected changes in quality.",
    "A good everyday option if you want something balanced and long wearing.",
    "I am content using this as my main scent for the season.",
    "Worth trying if you want a fragrance that feels personal but not loud.",
]

# ---------------------------------------------------------------------------
# Shared wear / scent closings for several axes
# ---------------------------------------------------------------------------
_WEAR_CLOSE = _PERFUME_CLOSE

# ---------------------------------------------------------------------------
# Planet — spiritual routine, no planet names, no destiny claims
# ---------------------------------------------------------------------------
_PLANET_OPEN = [
    "I bought this as part of my morning prayer routine after a temple visit.",
    "My astrologer suggested I try a fragrance for daily spiritual practice, not for results.",
    "I wanted something meaningful to wear during quiet puja at home.",
    "This was a gift from my spouse and I started using it on Sunday mornings.",
    "I picked it up during a festive week when our family puja schedule was busy.",
    "I have been wearing a small amount before evening aarti for the past month.",
    "Honestly, I was looking for a scent that feels calm rather than flashy.",
    "My mother uses it during her daily prayers and I followed her example.",
    "I ordered this after reading about mindful rituals and wanted to try it myself.",
    "I wear a little before sitting for mantra chanting in the morning.",
    "A cousin recommended this for someone who likes simple spiritual routines.",
    "I bought it to mark the start of a more regular home puja habit.",
    "I use it on days when I visit the temple early in the morning.",
    "My father keeps it near the altar and I borrowed his bottle to test.",
    "I wanted a personal scent that fits prayer time without feeling commercial.",
    "I started applying a small dab before lighting the diya each evening.",
    "This joined my shelf during Navratri when I was reorganising my ritual items.",
    "I was drawn to the idea of a fragrance that supports quiet reflection.",
    "I wear it during weekend havan prep when the house smells of ghee and flowers.",
    "My sister gifted this when I moved into a new home with a small mandir.",
    "I use it sparingly before meditation and it helps me settle down faster.",
    "I bought it online because the local store did not carry this collection.",
    "I wanted something I could associate with my daily grounding practice.",
    "I tried it during a family puja and liked how understated it felt.",
    "I keep it with my prayer beads and reach for it on calm mornings.",
    "I was not looking for miracles, just a scent for sincere daily ritual.",
    "My in-laws liked the idea of a fragrance tied to spiritual routine.",
    "I wear it when I read scripture in the evening before dinner.",
]

_PLANET_MID = [
    "The scent feels gentle and does not distract me while chanting.",
    "It stays close to the skin and feels appropriate near the home altar.",
    "My family noticed a pleasant smell during puja but nobody found it strong.",
    "It pairs well with the sandalwood and camphor we already use.",
    "I feel more settled when I include this in my morning routine.",
    "The fragrance is soft enough for daily wear during prayer time.",
    "It does not clash with incense smoke in the prayer room.",
    "I like that it feels personal and not like a party perfume.",
    "The aroma lingers quietly while I complete my morning rituals.",
    "It reminds me to slow down before starting a busy day.",
    "My spouse said it smells peaceful rather than overpowering.",
    "I appreciate that it feels respectful for temple visits.",
    "The scent supports a calm mood without making big promises.",
    "I use a tiny amount and it lasts through my morning practice.",
    "It feels like a small daily anchor rather than a dramatic change.",
    "Guests during puja commented that the home smelled welcoming.",
    "I enjoy the quiet warmth it adds to my evening diya lighting.",
    "It has become part of how I mark the start of prayer time.",
    "The fragrance feels balanced for someone who prefers subtle scents.",
    "I do not feel self-conscious wearing it in front of elders.",
    "It works well on days when I meditate after morning shower.",
    "The bottle feels like a ritual object on my dresser near the mandir.",
    "I like using it when the house is quiet early in the morning.",
    "It complements my habit of sitting silently for ten minutes daily.",
    "The smell feels familiar and comforting during stressful weeks.",
    "I am careful to use it as part of practice, not as a superstition.",
    "It helps me transition from rush hour traffic to evening prayers.",
    "My children said the prayer corner smells nice on weekends.",
]

_PLANET_CLOSE = [
    "I am content using this as part of my spiritual routine.",
    "It supports my practice without feeling gimmicky.",
    "Glad I chose something subtle for daily prayer time.",
    "Will continue using it mindfully as one part of my routine.",
    "A meaningful purchase for someone who values quiet rituals.",
    "I feel it fits my intention of calm daily devotion.",
    "Happy to recommend it for home puja and personal reflection.",
    "No complaints and the experience has felt sincere so far.",
    "I plan to keep this in my ritual corner for regular use.",
    "Worth trying if you want a gentle scent for spiritual habits.",
    "It has earned a place in my morning and evening routine.",
    "I am satisfied with how understated and pleasant it is.",
    "My family approves and that was important to me.",
    "Simple, calm, and appropriate for daily wear during prayers.",
    "I did not expect drama and I did not get drama, just a nice scent.",
    "Will reorder when the bottle runs low.",
    "A thoughtful gift for someone who prays daily at home.",
    "It feels respectful and personal at the same time.",
    "I am happy with this as a companion to my daily practice.",
    "Overall, a quiet fragrance that matches my expectations.",
]

# ---------------------------------------------------------------------------
# Chakra oils — meditation, yoga, massage, no medical claims
# ---------------------------------------------------------------------------
_CHAKRA_OPEN = [
    "I use a few drops during my evening yoga session after work.",
    "My yoga teacher suggested trying an oil for relaxation and I picked this.",
    "I bought this to add to my quiet routine before bedtime.",
    "This was a self-care purchase during a stressful month at the office.",
    "I apply a small amount before sitting for breathwork on weekends.",
    "My sister uses it for massage and shared a bottle with me to try.",
    "I wanted something for mindful evenings rather than loud home fragrance.",
    "I started using it after shower during my Sunday reset routine.",
    "Honestly, I was curious how an oil would feel during meditation.",
    "I keep it on my yoga mat corner and use it sparingly.",
    "I bought it online after a friend described her evening wind-down ritual.",
    "My mother likes a drop on her wrists before her quiet reading hour.",
    "I use it when I do gentle stretching in the balcony at dusk.",
    "I was looking for a calm scent to mark the end of my workday.",
    "I apply it before journaling and it has become a small habit.",
    "This joined my shelf when I started a ten minute daily sit practice.",
    "I wanted a sensory cue that tells my body it is time to slow down.",
    "I tried it during a home spa evening and liked the mild warmth.",
    "My partner and I take turns using it after evening walks.",
    "I bought it to pair with my foam roller on tired weekdays.",
    "I use a tiny amount on my neck before guided meditation videos.",
    "I was not expecting much but the routine feels nicer with it.",
    "I apply it before pranayama and it helps me settle my breath.",
    "My cousin recommended it for someone who needs a calm evening ritual.",
    "I keep the bottle near my cushion and reach for it habitually now.",
    "I wanted something gentle for body massage without a clinical smell.",
    "I started using it during quiet mornings before the house wakes up.",
    "I bought this as a treat after completing a month of daily yoga.",
]

_CHAKRA_MID = [
    "The aroma feels warm and helps me transition out of work mode.",
    "A few drops on my palms before meditation feels grounding.",
    "It blends well with coconut oil for a light shoulder massage.",
    "The scent is noticeable but never sharp during breathing exercises.",
    "I feel more present when I include this in my yoga cool down.",
    "My shoulders relax a little faster when I use it after desk work.",
    "It does not irritate my skin when diluted with a carrier oil.",
    "The fragrance stays soft and does not overwhelm a small room.",
    "I like that it feels like a ritual signal rather than a perfume.",
    "It pairs nicely with dim lights and slow music on quiet nights.",
    "My sleep routine feels calmer when I use it before bed.",
    "The oil spreads easily and a little goes a long way.",
    "I enjoy the mild scent during savasana at the end of practice.",
    "It helps me mark a boundary between busy day and personal time.",
    "The smell feels natural and not like a harsh spa chemical.",
    "I use it on my temples gently and it feels soothing.",
    "My partner likes the subtle aroma during our shared stretch session.",
    "It does not stain the clothes I wear during light home yoga.",
    "I feel more consistent with meditation when I have a sensory anchor.",
    "The bottle lasts longer than I expected with weekly use.",
    "It supports a calm mood without making any health promises.",
    "I appreciate that the scent fades gently after an hour.",
    "My evening bath feels more complete with a drop on my skin.",
    "It works well for a quiet corner setup with a candle and mat.",
    "I feel less restless during breath counting when I use this.",
    "The oil feels smooth and absorbs without feeling greasy.",
    "It has become part of how I end most weekdays now.",
    "I like using it when the city noise finally dies down outside.",
]

_CHAKRA_CLOSE = [
    "I am happy to keep this in my wellness corner.",
    "Will reorder when I am halfway through the bottle.",
    "A nice addition to a simple home yoga setup.",
    "Glad I tried it for evening relaxation.",
    "It supports my routine without feeling overhyped.",
    "I would gift this to a friend who meditates regularly.",
    "No complaints and the quality feels consistent.",
    "Comfortable recommending it for calm evening rituals.",
    "It has earned a permanent spot near my yoga mat.",
    "Worth trying if you want a gentle sensory cue for slowing down.",
    "I am satisfied after a month of regular use.",
    "Simple, pleasant, and useful for my quiet hours.",
    "My practice feels more intentional with this small addition.",
    "I plan to continue using it mindfully, not as a miracle product.",
    "Happy with the purchase for personal relaxation time.",
    "It does what I wanted without any fuss.",
    "A thoughtful self-care buy that I do not regret.",
    "I feel it was worth the price for the calm it adds.",
    "Will buy again unless the formula changes.",
    "Overall, a gentle oil that fits my evening routine well.",
]

# ---------------------------------------------------------------------------
# Nakshatra — birth star, tradition, calm, no destiny claims
# ---------------------------------------------------------------------------
_NAKSHATRA_OPEN = [
    "I bought this around my birth star day as a personal ritual gift to myself.",
    "My family astrologer mentioned trying a scent for daily prayer, not for predictions.",
    "I wanted something connected to tradition that I could use every evening.",
    "This was a gift from my parents when I moved to a new city.",
    "I started using it during quiet prayer time after consulting no one about outcomes.",
    "Honestly, I was drawn to the idea of a fragrance tied to my janma star.",
    "I wear a small amount before evening prayers as a personal habit.",
    "My grandmother liked the thought behind it and encouraged me to try.",
    "I ordered this after a cousin spoke about meaningful gifting in our family.",
    "I use it on Sundays when we do a longer family puja at home.",
    "I was looking for something that feels personal without being flashy.",
    "I bought it to mark a new chapter of regular spiritual practice.",
    "My spouse gifted this on my birthday along with a small altar cloth.",
    "I keep it near my prayer book and use it sparingly.",
    "I tried it during a temple visit weekend and liked the calm feel.",
    "I wanted a scent that reminds me of home traditions while living alone.",
    "I apply a little before chanting and it helps me focus gently.",
    "A friend in our astrology reading group recommended the collection generally.",
    "I bought it online because it was not available at my local shop.",
    "I use it when I sit quietly after lighting the evening lamp.",
    "My mother uses hers during morning prayer and I followed suit.",
    "I was not expecting miracles, just a nice personal ritual scent.",
    "I picked it for its connection to Vedic tradition in a simple daily way.",
    "I wear it during festival mornings when the house is busy with prep.",
    "I wanted something meaningful to pass down as a gifting idea in the family.",
    "I started using it after reorganising my small home mandir.",
    "My sister and I bought matching bottles as a sibling tradition.",
    "I use it mindfully as part of reflection, not as a luck charm.",
]

_NAKSHATRA_MID = [
    "The fragrance feels soft and respectful during prayer time.",
    "It stays close and does not overpower the incense in the room.",
    "My family noticed a pleasant smell during our evening aarti.",
    "It feels like a personal marker for quiet spiritual moments.",
    "I like that it connects to tradition without loud branding.",
    "The scent is gentle enough for daily wear at home.",
    "It helps me pause before starting my evening mantra practice.",
    "I feel more centred when I include this small step in my ritual.",
    "The aroma lingers quietly while I complete my prayers.",
    "It pairs well with the diya and flowers on our altar.",
    "I appreciate that it feels sincere rather than superstitious.",
    "Guests during puja said the home smelled welcoming.",
    "It does not clash with camphor or sandalwood we already use.",
    "I use a tiny dab and it lasts through my prayer session.",
    "The bottle sits nicely among my ritual items on the shelf.",
    "It feels appropriate when I visit elders for blessings.",
    "My spouse said it smells peaceful on festival mornings.",
    "I enjoy the subtle warmth during meditation after prayers.",
    "It has become part of how I honour my birth star day each month.",
    "The fragrance feels balanced for someone who prefers understated scents.",
    "I do not feel awkward wearing it during family spiritual gatherings.",
    "It supports calm reflection without promising any life changes.",
    "I like gifting ideas that feel cultural and personal like this.",
    "The scent feels familiar in a way that comforts me on lonely evenings.",
    "It works well for someone building a gentle daily spiritual habit.",
    "My parents approved of the choice and that mattered to me.",
    "It reminds me to slow down before rushing into the day.",
    "I feel grateful for a simple scent that fits my beliefs respectfully.",
]

_NAKSHATRA_CLOSE = _PLANET_CLOSE

# ---------------------------------------------------------------------------
# Zodiac — rashi gifting, daily wear, compliments
# ---------------------------------------------------------------------------
_ZODIAC_OPEN = [
    "I bought this as a birthday gift for myself based on my rashi.",
    "My friend recommended this collection and I picked my sign's variant.",
    "I wore it to a family lunch and my cousin asked what it was.",
    "This was part of a hamper from my sister who loves astrology themes.",
    "I wanted a daily fragrance that felt personal without being loud.",
    "Honestly, I was curious how a zodiac themed scent would wear in real life.",
    "I tried it before a wedding function and it felt appropriate.",
    "My mother liked the gifting idea and ordered one for my brother too.",
    "I wear a small amount before office on days I want a quiet confidence.",
    "I ordered online after seeing it in an astrology enthusiast group.",
    "I was looking for a signature scent that connects to my star sign.",
    "I first tested a sample at a friend's place and liked the dry down.",
    "I bought it during my birthday month as a small treat.",
    "My husband gifted this and I have been using it on most weekdays.",
    "I wanted something to wear for chart reading evenings with friends.",
    "I picked it for evening wear during the festive season.",
    "I have almost finished my first bottle and will reorder the same sign.",
    "I wore it to a coffee meetup and received a casual compliment.",
    "I was hesitant about themed perfumes but this felt tasteful.",
    "I keep it on my dresser next to my jewellery tray.",
    "I bought it for daily wear because the notes sounded balanced online.",
    "My colleague noticed a pleasant smell during a team lunch.",
    "I use it when dressing up for small family celebrations.",
    "I wanted a gift idea for an astrology loving friend and kept one too.",
    "I tried it on my wrist and kurta and both carried the scent well.",
    "I was tired of generic perfumes and this felt more personal.",
    "I wore it on a rainy evening walk and it lasted fine.",
    "My daughter said it smells nice when I hug her goodbye.",
]

_ZODIAC_MID = [
    "The opening is soft and settles into something warm on skin.",
    "It lasts through my usual workday without needing a second dab.",
    "People notice it politely rather than from across the hall.",
    "It feels suitable for both office and family gatherings.",
    "The fragrance has a balanced character for Indian weather.",
    "I like that it does not smell like a loud party perfume.",
    "My kurta collar held a faint trace by evening.",
    "It pairs well with my usual moisturiser without turning odd.",
    "The scent feels personal and not like a generic department store pick.",
    "I received a quiet compliment from an aunt at a function.",
    "It works for someone who prefers subtle daily signatures.",
    "The dry down feels comfortable and not sharp on my skin.",
    "I did not need to reapply during a long Sunday family visit.",
    "It smells better after fifteen minutes than at first dab.",
    "My friends in the astrology club liked the concept and the wear.",
    "It feels refined enough for small evening events.",
    "The bottle design made it a nice unboxing gift moment.",
    "I appreciate that the theme is present but not gimmicky on skin.",
    "It sits close and feels appropriate around elders.",
    "I enjoy wearing it on days tied to personal star sign rituals.",
    "The longevity was better than I expected for the price.",
    "It does not clash with incense when I wear it before home puja.",
    "I feel comfortable recommending it as a rashi themed gift.",
    "The projection is gentle which suits my office environment.",
    "It has become my default for casual weekday outings.",
    "My spouse likes it for date night dinners at home.",
    "It feels like a thoughtful present that people actually use.",
    "I would describe it as calm warmth rather than flashy sweetness.",
]

_ZODIAC_CLOSE = _WEAR_CLOSE

# ---------------------------------------------------------------------------
# Love — romantic gifting, date night, partner
# ---------------------------------------------------------------------------
_LOVE_OPEN = [
    "I bought this as an anniversary gift for my wife and she loved it immediately.",
    "My husband surprised me with this on Valentine's week and I wear it often now.",
    "I wore it on our dinner date and he noticed before I mentioned anything.",
    "This was part of a gift set I chose for my partner's birthday.",
    "I wanted something soft for romantic evenings at home.",
    "Honestly, I was looking for a scent that feels intimate but not heavy.",
    "I tried it before a sangeet function and got compliments from friends.",
    "My fiancé picked this for me and it has become my evening favourite.",
    "I wear a small dab when we go out for late night drives.",
    "I ordered this after a friend recommended it for couple gifting.",
    "I was planning our anniversary and wanted a fragrance with a warm feel.",
    "I first smelled it on my partner and ordered my own bottle the next day.",
    "I bought it to wear during our honeymoon trip last month.",
    "My girlfriend likes subtle scents and this matched her taste perfectly.",
    "I wore it to a candlelight dinner and it felt just right.",
    "I wanted a romantic gift that was not jewellery or clothes again.",
    "I use it on weekends when we cook together and slow down.",
    "My partner noticed the fragrance during a movie night at home.",
    "I picked this for our first Diwali together as a married couple.",
    "I was tired of loud perfumes and chose this for quiet romance.",
    "I wear it when dressing up for small celebrations just the two of us.",
    "This joined my collection during wedding season and stayed after.",
    "I gifted it to my boyfriend and he actually uses it daily.",
    "I wanted something that smells warm on cool winter evenings together.",
    "I tried it on my wrist before a surprise date and it lasted well.",
    "My spouse said it reminds him of our early dating days.",
    "I bought it online because the description sounded elegant and soft.",
    "I keep it for occasions when I want to feel a little special.",
]

_LOVE_MID = [
    "The scent feels warm and close without filling the whole room.",
    "My partner complimented it during a long car ride.",
    "It lasts through dinner and still feels pleasant later at home.",
    "The fragrance is romantic in a subtle, mature way.",
    "I like that it does not smell overly sweet or artificial.",
    "It works for both restaurant outings and quiet evenings in.",
    "One light application was enough for our anniversary dinner.",
    "The dry down feels soft on skin and on a light scarf.",
    "It pairs nicely with a simple dress for date nights.",
    "My friends said it smells elegant when I hugged them at the party.",
    "It feels personal rather than like a generic gift shop perfume.",
    "I did not need to reapply during a three hour evening out.",
    "The bottle feels gift worthy and the scent matches that impression.",
    "It sits close which is perfect for intimate settings.",
    "My partner prefers when I wear something gentle and this fits.",
    "It smells better as the evening goes on rather than at first spray.",
    "I feel confident wearing it for special moments without overdoing it.",
    "The warmth of the scent suits winter date nights well.",
    "It does not clash with his cologne when we are close.",
    "I received a sweet comment during our rooftop dinner.",
    "It has become my go-to for romantic occasions small and big.",
    "The longevity impressed me on our long anniversary evening.",
    "It feels appropriate for wedding season events with a partner.",
    "I enjoy the soft trail it leaves when we walk together.",
    "My fiancé stole a dab and now we share the bottle sometimes.",
    "It makes me feel put together without trying too hard.",
    "The fragrance has a tender quality that suits the collection theme.",
    "I would describe it as close, warm, and quietly memorable.",
]

_LOVE_CLOSE = _WEAR_CLOSE

# ---------------------------------------------------------------------------
# Stress — sleep, unwind, calm evening
# ---------------------------------------------------------------------------
_STRESS_OPEN = [
    "I bought this to help me unwind after long desk days at the office.",
    "My therapist suggested building a calming evening routine and I added this.",
    "I use it before bed when my mind refuses to slow down.",
    "This was a self-care purchase during a particularly hectic month.",
    "I apply a little after my evening shower on stressful weekdays.",
    "Honestly, I was looking for something gentle to mark the end of work.",
    "I started using it during Sunday resets when I avoid my phone.",
    "My sister recommended it for quiet evenings and she was right.",
    "I keep it on my nightstand for breathing exercises before sleep.",
    "I bought it after reading reviews from people with busy corporate jobs.",
    "I wanted a scent that tells my brain it is okay to relax now.",
    "I use it when I journal about the day before turning off the lights.",
    "My partner and I take turns using it after tense work weeks.",
    "I was struggling with restless evenings and this became a small comfort.",
    "I apply a dab before guided meditation apps on my phone.",
    "I ordered it online during a sale and glad I tried it.",
    "I wear a tiny amount during balcony tea after the kids sleep.",
    "I bought it to pair with chamomile tea and dim lighting.",
    "My friend uses it for yoga nidra and I followed her suggestion.",
    "I wanted something for night routine without a medicinal smell.",
    "I tried it on a Friday after a brutal deadline week.",
    "I use it when commuting stress spills into my home mood.",
    "My mother liked how calm I seemed and asked what changed.",
    "I keep the bottle in my unwind corner with books and a lamp.",
    "I was not expecting magic, just a nicer way to end the day.",
    "I apply it before stretching exercises in the living room.",
    "I bought this as a treat when I finally took a weekend off.",
    "I use it sparingly because a little already changes the mood.",
]

_STRESS_MID = [
    "The aroma feels soft and helps me transition out of work mode.",
    "It does not overwhelm the room and feels safe before bedtime.",
    "My shoulders unclench a little when I include this in my routine.",
    "The scent is gentle enough that it does not keep me awake.",
    "I feel less wired after ten minutes of quiet breathing with it.",
    "It pairs well with low music and a warm shower.",
    "My sleep routine feels more intentional since I started using this.",
    "The fragrance fades calmly and does not linger harshly on pillows.",
    "I like that it feels like a signal to stop checking email.",
    "It sits close and comforts me during late night reading.",
    "My partner says I seem calmer on days I use it.",
    "The smell is subtle and not like harsh spa chemicals.",
    "I enjoy it during a slow walk on the terrace at dusk.",
    "It helps me separate office thoughts from home time.",
    "A small dab on my wrist is enough for the whole evening.",
    "The bottle lasts because I only use it on stressful days.",
    "It supports a peaceful mood without making health claims.",
    "I feel more present during my evening wind down ritual.",
    "It works well when the city noise finally quiets down.",
    "My Sunday anxiety feels lighter when I start the day with this routine.",
    "The dry down is warm and comforting on cool nights.",
    "I do not feel jittery wearing it unlike some strong perfumes.",
    "It has become a small anchor in my mental health toolkit.",
    "I appreciate that it smells natural and not clinical.",
    "My evening bath feels complete with this added step.",
    "It does not clash with lavender soap I already use.",
    "I feel ready for bed sooner when I include this habit.",
    "The calm effect is subtle but genuinely helpful for me.",
]

_STRESS_CLOSE = _CHAKRA_CLOSE

# ---------------------------------------------------------------------------
# Generic lifestyle axes — reuse wear/scent patterns with axis-specific opens
# ---------------------------------------------------------------------------
def _wear_axis_open(axis_hint: str) -> list[str]:
    return [
        f"I bought this during a busy month and it quickly became part of my routine.",
        f"My second purchase arrived and the quality still matches what I remember.",
        f"A friend recommended this after I asked for something reliable for daily use.",
        f"I ordered online because the local shop was out of stock last week.",
        f"Honestly, I was not expecting much but the first week changed my mind.",
        f"I wore it to a family lunch and nobody found it too strong.",
        f"This was a gift from my sibling and I started using it the same day.",
        f"I picked it up before the festive season and kept using it afterward.",
        f"I wanted something balanced for Indian weather and daily wear.",
        f"My partner noticed the fragrance before I mentioned buying something new.",
        f"I tried a sample at a cousin's house and placed my order soon after.",
        f"I have almost finished the bottle and already planned a reorder.",
        f"I bought it as a small treat after a long project at work.",
        f"I was looking for a scent that works for office and home alike.",
        f"My mother approved when she visited and that sealed it for me.",
        f"I wear a small amount before leaving home on most weekdays.",
        f"I chose this after comparing a few options online for {axis_hint}.",
        f"I keep it on my dresser and reach for it without thinking now.",
        f"I wore it during a weekend trip and it held up fine.",
        f"I wanted a dependable fragrance for regular use, not special occasions only.",
        f"My colleague gave a casual compliment during a team lunch.",
        f"I bought it to replace an old favourite that was discontinued.",
        f"I was hesitant about ordering fragrance online but this worked out.",
        f"I use it when dressing up lightly for evening walks.",
        f"My family liked it enough to ask me to order for them too.",
        f"I picked this for {axis_hint} and it has delivered so far.",
        f"I first tried it on a rainy day and liked how it wore.",
        f"I felt it was worth trying after seeing steady positive feedback.",
    ]


_LUXURY_OPEN = [
    "I bought this for a formal dinner where I wanted to feel properly dressed up.",
    "This was an anniversary splurge and the unboxing felt special.",
    "I wore it to a gala evening and received a quiet compliment.",
    "Honestly, I save this for occasions when I want something refined.",
    "My spouse gifted this in premium packaging and I was impressed.",
    "I wanted a fragrance that feels elegant without being old fashioned.",
    "I first tried it at a boutique counter and liked the dry down.",
    "I wear it for important client dinners once in a while.",
    "I picked this for a milestone birthday treat to myself.",
    "The bottle looks beautiful on my dresser and the scent matches.",
    "I wore it to a wedding reception and it lasted through dinner.",
    "I was looking for something with a luxurious feel for winter evenings.",
    "My sister borrowed it for her engagement photoshoot and loved it.",
    "I use it sparingly because a little already feels rich.",
    "I bought it after saving up for a quality signature scent.",
    "I wanted a premium option for rare evenings out.",
    "I wore it to a classical music concert and it felt appropriate.",
    "My friends noticed something different when I hugged them at the party.",
    "I keep it for occasions when jeans and t shirt will not do.",
    "I ordered it online and was relieved the packaging arrived intact.",
    "I chose this over a mainstream perfume and do not regret it.",
    "I wear it when hosting dinner guests at home.",
    "I was curious whether a luxury attar feels different daily and it does.",
    "My husband said it smells expensive in the best way.",
    "I bought it for a special trip and still use it on date nights.",
    "I wanted a collector worthy bottle with a scent to match.",
    "I tried it before a photoshoot and the photographer noticed.",
    "I feel put together quickly when I wear this before stepping out.",
]

_SPIRITUAL_OPEN = _PLANET_OPEN[:]
_BESTSELLER_OPEN = _wear_axis_open("everyday wear")
_GIFT_OPEN = [
    "I bought this as a Diwali gift for my parents and they loved the packaging.",
    "This was a wedding return gift and several relatives asked where it was from.",
    "I ordered a set for my team during the festive season.",
    "My friend received this for her birthday and I immediately ordered one for myself.",
    "I chose this for a housewarming present because it felt thoughtful.",
    "Honestly, the box itself made a great first impression when it arrived.",
    "I gifted it to my father-in-law and he appreciated the subtle fragrance.",
    "I picked this for an anniversary hamper along with sweets and candles.",
    "The recipient said it felt premium without being flashy.",
    "I bought multiple units for family gifts during Navratri.",
    "I was looking for something presentable that people would actually use.",
    "My sister unboxed it on video call and smiled right away.",
    "I sent this to a cousin abroad and she said delivery was smooth.",
    "I chose it for a thank you gift after a family favour.",
    "The ribbon and packaging saved me wrapping time during busy weeks.",
    "I gifted it to a teacher on Guru Purnima and it felt appropriate.",
    "I bought it for a colleague's farewell and it was well received.",
    "My parents kept the bottle on display before even opening it.",
    "I wanted a gift that suits both young and older relatives.",
    "I ordered during a sale and stocked up for upcoming birthdays.",
    "The presentation made it easy to give without extra effort.",
    "I picked this for a bridal shower gift along with a note.",
    "My brother said it was the most useful gift he got this year.",
    "I bought it for my wife's mother and she uses it daily now.",
    "I was tired of generic gift baskets and tried this instead.",
    "I gifted it to newlyweds in our family last month.",
    "The unboxing video my friend sent me convinced me to order too.",
    "I feel confident giving this when I do not know someone's exact taste.",
]

_APSARA_OPEN = [
    "I wore this for a classical dance rehearsal and it felt elegant on stage.",
    "My guru suggested something subtle for performance days and this worked.",
    "I bought it before a sangeet where I was performing a short piece.",
    "Honestly, I wanted a fragrance that complements traditional attire.",
    "I used it during a bridal photoshoot and the photographer loved the vibe.",
    "I wear a small amount before cultural programs at our housing society.",
    "This was a gift from my dance group friends before a big show.",
    "I picked it for an evening of Bharatanatyam at a temple festival.",
    "I wanted something refined for stage lights and close audience seating.",
    "I tried it before a mehendi ceremony where I was helping the bride.",
    "My mother said it smells graceful without overpowering jewellery and flowers.",
    "I wore it during a rehearsal and it lasted through long practice.",
    "I bought it for a heritage wedding where I wore heavy silk.",
    "I keep it for performance days rather than casual office wear.",
    "I was looking for a scent that feels artistic and feminine.",
    "I used it before a school annual day where parents sit close.",
    "My sister borrowed it for her arangetram photos and ordered her own.",
    "I wanted something special for my first solo stage performance.",
    "I wear it when hosting a small cultural evening at home.",
    "I chose it because it feels timeless with sarees and temple jewellery.",
    "I applied it before a long rehearsal and it stayed gentle.",
    "My dance classmates asked what I was wearing backstage.",
    "I bought it online after a recommendation from our accompanist.",
    "I use it for photo shoots where makeup and costume are already strong.",
    "I felt confident wearing it under hot stage lights.",
    "It paired beautifully with jasmine flowers in my hair.",
    "I wanted a fragrance that respects tradition and still feels personal.",
    "I wear it for intimate cultural gatherings rather than loud parties.",
]

_ASTROLOGY_OPEN = [
    "I bought this during my birthday month because I enjoy astrology themed gifts.",
    "My friend from our chart reading group recommended trying this collection.",
    "I wear it on evenings when friends come over to discuss horoscopes.",
    "This was a muhurat day purchase that turned into daily wear.",
    "Honestly, I like the theme but cared more about how it smells on skin.",
    "I picked it as a gift for someone who tracks retrograde seasons jokingly.",
    "I ordered it after a salon astrologer mentioned it casually.",
    "I wanted a personal scent for journaling about my goals each Sunday.",
    "My partner bought matching bottles for our anniversary.",
    "I wear it to casual meetups with my astrology enthusiast friends.",
    "I was curious whether a themed fragrance could still feel wearable daily.",
    "I chose it for a star sign party and kept using it after.",
    "I bought it online during a forecast night watch party at home.",
    "I use it when I read my chart notes in the evening.",
    "My cousin liked the concept and asked me to order one for her.",
    "I wanted something fun that still smells mature on office days.",
    "I wear a dab before video calls with my long distance best friend.",
    "I picked this for a couple gift along with a handwritten chart joke.",
    "I was tired of generic perfumes and this felt more personal.",
    "I tried it during a rainy season when I always reflect more.",
    "My sister said it suits someone who loves quiet mysticism not drama.",
    "I bought it as a treat after a difficult transit month emotionally.",
    "I keep it on a shelf with my books about Vedic astrology.",
    "I wear it for date nights when we stargaze from the terrace.",
    "I wanted a scent that sparks conversation without promising miracles.",
    "I gifted it to a friend starting her astrology learning journey.",
    "I use it on new moon evenings as a personal ritual scent.",
    "I feel it fits my personality as someone who likes symbolic gifts.",
]

_MOOD_OPEN = [
    "I reach for this on slow Sundays when I want the day to feel softer.",
    "I bought it during monsoon when everything outside feels grey.",
    "Honestly, this pairs perfectly with chai on my balcony.",
    "I use it when journaling on quiet afternoons at home.",
    "My mood lifts a little when I include this in my morning routine.",
    "I wore it during a rainy weekend trip to the hills.",
    "I wanted a scent for creative afternoons when I paint at home.",
    "I keep it for feel good days when I work from the couch.",
    "I bought it to mark a fresh start after a tough month.",
    "I apply a dab before evening walks in the park.",
    "This feels like my companion for cozy winter evenings indoors.",
    "I use it when hosting two friends for an intimate dinner.",
    "I was looking for something gentle for sensitive emotional days.",
    "I wear it during reading marathons on long holidays.",
    "My sister says it smells like calm in a bottle.",
    "I picked it for balcony sunsets during summer break.",
    "I bought it to pair with soft music and dim lamps.",
    "I use it when I need a small comfort without leaving home.",
    "I wore it on a solo cafe visit and felt more settled.",
    "I wanted a fragrance for mood lifting that is not sugary sweet.",
    "I apply it before video calls with family on quiet nights.",
    "I keep it for days when I choose slowness on purpose.",
    "I bought it after a friend described her Sunday ritual.",
    "I use it during gentle stretching on lazy mornings.",
    "I feel more myself when I wear something this understated.",
    "I chose it for rainy day playlists and warm socks.",
    "I wear it when writing letters to friends I miss.",
    "I wanted a scent that matches introspective moods kindly.",
]

_FESTIVAL_OPEN = [
    "I bought this right before Diwali prep and used it throughout the week.",
    "Our family gathering during Navratri felt nicer with this at home.",
    "I wore it to a pandal visit and it lasted through the evening.",
    "This was part of our festive shopping list this year.",
    "Honestly, festival weeks are busy and this was an easy win.",
    "I gifted bottles to cousins during the family reunion.",
    "I used it before hosting relatives for puja lunch.",
    "My mother liked it for the subtle festive warmth it adds.",
    "I picked it for wedding season events back to back.",
    "I wore it during a house full of guests and nobody complained.",
    "I ordered early to avoid last minute delivery stress.",
    "I wanted something that feels celebratory without being loud.",
    "I keep it for days when we light extra diyas at home.",
    "I bought it for Karva Chauth evening with my spouse.",
    "I used it during a long day of shopping and errands.",
    "My sister and I matched scents for a family photo day.",
    "I wore it to a society Diwali party and got a compliment.",
    "I chose it because it survives humid festive afternoons.",
    "I apply it before visiting relatives across town.",
    "I bought extra units for gifting during the season.",
    "I wanted a reliable scent for crowded family functions.",
    "I use it when dressing up in ethnic wear at home.",
    "My friends noticed something pleasant during our festive brunch.",
    "I picked it for puja week mornings before guests arrive.",
    "I was tired of heavy perfumes at festivals and tried this.",
    "I wear it when helping decorate the home altar.",
    "I bought it online and it arrived before the muhurat day.",
    "I feel more festive quickly when I wear this with my kurta.",
]

_DAILY_OPEN = _wear_axis_open("daily office wear")
_MEDITATION_OPEN = _CHAKRA_OPEN[:]
_PREMIUM_OPEN = _LUXURY_OPEN[:]
_LIMITED_OPEN = [
    "I managed to order this on launch day before it sold out online.",
    "My waitlist notification came at midnight and I bought immediately.",
    "I wanted the numbered bottle as a keepsake on my shelf.",
    "Honestly, limited drops make me nervous but this one delivered.",
    "I wore it the same week it arrived and treasured the unboxing.",
    "I bought it because the batch size was small and special.",
    "My collector friend recommended grabbing this edition quickly.",
    "I picked it for an anniversary and liked the exclusive feel.",
    "I was lucky to get the last unit during the seasonal release.",
    "I keep it for rare evenings rather than everyday commuting.",
    "I ordered within minutes of the email announcement.",
    "I wanted something not everyone at the office would be wearing.",
    "The packaging for this edition felt worth saving.",
    "I wore it to a private dinner to test the hype quietly.",
    "I bought it as a milestone gift when I changed jobs.",
    "My spouse surprised me with the launch day delivery.",
    "I hesitated because of the price but glad I tried once.",
    "I use it sparingly to make the bottle last longer.",
    "I felt excited opening a product few people had yet.",
    "I picked it for a photoshoot with the beautiful bottle.",
    "I was part of the early access list and felt privileged.",
    "I bought it to compare with the regular line and preferred this.",
    "My friend missed the drop and borrowed mine for a wedding.",
    "I wanted a story to tell when friends ask what I wear.",
    "I wear it on Sundays when I dress a little nicer at home.",
    "I chose it for a collector shelf alongside older editions.",
    "I ordered two, one to use and one to gift later.",
    "I like having something rare that still smells wearable daily.",
]

_SEASONAL_OPEN = [
    "I bought this for winter evenings when I wear shawls at home.",
    "Monsoon humidity usually ruins my perfume but this held up well.",
    "I picked it before a summer wedding in Jaipur.",
    "Honestly, seasonal weather changes how scent wears and this adapted nicely.",
    "I use it more during cool months on my balcony.",
    "I wore it during a hill station trip last December.",
    "I wanted something fresh enough for humid April afternoons.",
    "My summer office AC makes many scents sharp but this stayed gentle.",
    "I bought it before wedding season in peak heat.",
    "I reach for it when the city smells of wet earth outside.",
    "I packed it for a coastal holiday and it survived the salt air.",
    "I chose it for festive winter gatherings indoors.",
    "I wear it during early morning walks in pleasant spring weather.",
    "I ordered before the first cold snap hit our city.",
    "I wanted a fragrance that suits both fan nights and sweater days.",
    "I use it during Navratri when days are warm and nights cool.",
    "I bought it for a family picnic in mild winter sun.",
    "My skin behaves differently each season and this stayed consistent.",
    "I keep it for travel when weather forecasts confuse me.",
    "I wore it to an outdoor mehendi in humid weather.",
    "I picked a lighter dab during summer and it still projected softly.",
    "I like it for rainy evening drives with windows half open.",
    "I bought it before a work trip to a colder city.",
    "I switch scents by season and this earned a permanent winter slot.",
    "I use it when switching from cotton to light woollens.",
    "I wanted something that does not turn cloying in heat.",
    "I wore it during a sunset on the terrace in October.",
    "I feel it matches the mood of changing seasons gracefully.",
]

_GENERIC_OPEN = _wear_axis_open("regular use")

# Shared mid for lifestyle wear axes
_WEAR_MID = _PERFUME_MID[:]

_LUXURY_MID = [
    "The scent feels refined from the first dab onward.",
    "It lasts through long dinners without fading awkwardly.",
    "People notice it politely at close distance.",
    "The dry down has a plush warmth suitable for cool evenings.",
    "I felt elegant wearing it with formal silk attire.",
    "The fragrance unfolds slowly and rewards patience.",
    "It does not smell synthetic under bright ballroom lights.",
    "My host complimented it during a seated dinner.",
    "One application carried me through speeches and photos.",
    "The bottle feels substantial and the juice matches that promise.",
    "It sits richly on skin without becoming cloying.",
    "I appreciate the restrained sweetness in the base.",
    "It pairs well with gold jewellery and heavy fabrics.",
    "The trail is noticeable but never vulgar.",
    "I felt confident meeting older relatives while wearing it.",
    "It smells expensive in a cultured way not a loud way.",
    "The longevity justified the splurge for rare occasions.",
    "It photographs well because it is not overpowering in person.",
    "My spouse kept leaning closer which is always a good sign.",
    "It feels like an evening scent that still respects Indian rooms.",
    "I would wear it to a classical concert again happily.",
    "The opening is graceful rather than sharp.",
    "It made a simple saree feel more complete.",
    "I did not need to reapply during a four hour reception.",
    "It has a mature character that suits milestone celebrations.",
    "Friends asked the brand name because it smelled distinctive.",
    "It feels special without being unwearable in real life.",
    "I am saving the last third for truly special nights.",
]

_GIFT_MID = [
    "The recipient used it the same week which is always a good sign.",
    "Everyone commented on how thoughtful the presentation felt.",
    "It suits people who do not like overly loud fragrances.",
    "The scent inside matched the premium look of the box.",
    "I would buy it again for the next round of family gifts.",
    "It arrived on time which mattered for the festival deadline.",
    "The fragrance pleased both my parents which is rare.",
    "People appreciated getting something usable not decorative only.",
    "It felt appropriate for elders and younger cousins alike.",
    "The unboxing made a nice moment on video call.",
    "No complaints from anyone in the gift exchange.",
    "It pairs well with sweets and candles in a hamper.",
    "The bottle size felt generous for the price point.",
    "Recipients said it lasted longer than they expected.",
    "I liked not having to explain what it is, they got it instantly.",
    "It saved me time during a hectic gifting season.",
    "The ribbon and box quality impressed picky relatives.",
    "It smells pleasant without being polarising at gatherings.",
    "I felt proud handing it over at the function.",
    "Several people asked for the link after trying it once.",
    "It works when you are unsure of someone's exact taste.",
    "The fragrance feels warm and welcoming for festive homes.",
    "I would include it in corporate gifts for clients too.",
    "It did not leak during shipping which was my main worry.",
    "The gift felt personal even though I ordered in bulk.",
    "My colleague still mentions it months after his birthday.",
    "It strikes a nice balance between luxury and practicality.",
    "I am adding it to my default gift list going forward.",
]

_APSARA_MID = [
    "It sat gently on skin even under hot stage lights.",
    "The fragrance felt refined with traditional jewellery.",
    "Backstage friends noticed something elegant not loud.",
    "It did not compete with stage makeup and hair products.",
    "The scent lasted through rehearsal breaks comfortably.",
    "It felt appropriate for temple and auditorium settings alike.",
    "My guru said it was subtle enough for performance proximity.",
    "It complemented the silk saree without stealing focus.",
    "I felt poised wearing it during my entrance piece.",
    "The dry down stayed soft while I was dancing.",
    "It photographed well because it is not overpowering nearby.",
    "Audience members close to stage did not seem bothered.",
    "It pairs beautifully with jasmine and rose garlands.",
    "I would wear it again for an arangetram type event.",
    "The warmth suited an evening outdoor cultural program.",
    "It felt artistic rather than like a nightclub perfume.",
    "My mother said it smells graceful which is high praise.",
    "It survived long hours of costume changes backstage.",
    "I felt more confident during my solo entry.",
    "It does not clash with the incense at temple venues.",
    "The trail is gentle when I move across stage.",
    "It made me feel dressed up even before costume was on.",
    "Fellow dancers asked to try a dab before show time.",
    "It respects the seriousness of classical performance.",
    "I like that it feels heritage aligned not trendy only.",
    "The bottle is pretty enough for dressing room shelves.",
    "It works for intimate home concerts with family too.",
    "I will keep this for performance days specifically.",
]

_ASTROLOGY_MID = _ZODIAC_MID[:]
_MOOD_MID = _STRESS_MID[:]
_FESTIVAL_MID = _PERFUME_MID[:]
_SEASONAL_MID = _PERFUME_MID[:]
_LIMITED_MID = _LUXURY_MID[:]

# Extra unique openings to keep 90 reviews from sharing the same first phrase
_WEAR_EXTRA_OPENS = [
    "The parcel showed up on a rainy Thursday and I tried it before dinner.",
    "Sach bolu, this turned out much better than I expected from an online order.",
    "Kaafi balanced fragrance hai and it suits everyday use in our weather.",
    "My neighbour borrowed a dab and ordered her own bottle within a week.",
    "The delivery box was intact and the bottle looked exactly like the pictures.",
    "I stumbled upon this while replacing an old favourite that got discontinued.",
    "Weekend laundry day turned into a trial run and I liked it immediately.",
    "Our building WhatsApp group had a thread about this and I finally tried it.",
    "I had been eyeing it for months and bought it during a quiet sale weekend.",
    "The scent surprised me because I usually stick to the same brand for years.",
    "My barber mentioned smelling something nice on a client and I asked what it was.",
    "I wore it to pick up my child from school and another parent commented softly.",
    "A wedding invite arrived and I wanted something new for the reception night.",
    "The first dab went on my wrist while I was still in my bathrobe.",
    "I tested it on a handkerchief first because my skin can be picky.",
    "My flatmate said the hallway smelled good after I walked through.",
    "I packed it for a two day work trip and it survived the flight fine.",
    "Sunday market errands felt nicer with this on before stepping out.",
    "I wore it during a long video call and a cousin noticed on screen.",
    "The bottle cap clicks shut firmly which matters when I travel with it.",
    "I bought it with my first salary at the new job as a small celebration.",
    "My yoga class friend wears something similar and pointed me here.",
    "I applied it before a dentist appointment and it stayed gentle.",
    "The fragrance felt right for a humid Mumbai evening on the local train.",
    "I wore it to a book club meetup and someone asked during tea break.",
    "My tailor noticed when I went for kurta fitting before Diwali.",
    "I kept the receipt because I was unsure, but I am glad I kept the bottle too.",
    "A podcast ad mentioned the brand and I looked it up that night.",
    "I wore it on a day I worked from a cafe and felt more put together.",
    "My brother brought a sample from a store visit and I ordered full size.",
    "I tried it before a parent teacher meeting and it felt appropriate.",
    "The bottle sits next to my watch tray and I grab it without thinking.",
    "I wore it during a long auto ride and it did not turn sour.",
    "My mother-in-law complimented it during Sunday lunch which is rare.",
    "I bought it when my old bottle cracked and needed a quick replacement.",
    "First impression was mild, second week opinion is genuinely positive.",
    "I wore it to a morning walk in the park and it felt fresh not loud.",
    "The checkout process was simple and the product matched the description.",
    "I applied a tiny bit before a family video call and my aunt noticed.",
    "My office cab driver said the car smelled nice which made me smile.",
    "I wore it on a day I presented to senior leadership and felt calm.",
    "The bottle label is easy to read which helps when I reorder quickly.",
    "I tried it during a heatwave week and it did not feel cloying.",
    "My cousin's engagement photoshoot had me searching for a subtle scent.",
    "I wore it before visiting the bank branch for a long errand queue.",
    "The fragrance felt mature enough for someone in their forties like me.",
    "I bought it after finishing a stressful quarter at work.",
    "My friend from college visited and asked what changed about my routine.",
    "I wore it on a spontaneous dinner plan and it lasted through dessert.",
    "The sample card in the package convinced me faster than the website copy.",
    "I applied it before a morning flight and still noticed it after landing.",
    "My sister stole a dab before her interview and said it helped her mood.",
    "I wore it during a rainy drive to Pune and it felt comforting.",
    "The bottle weight feels premium without being awkward in a small bag.",
    "I tried it on cotton and linen kurtas and both carried it well.",
    "My husband bought groceries and came back asking what smelled nice at home.",
    "I wore it to a morning temple visit and it stayed close and polite.",
    "The reorder page is bookmarked on my phone now which says enough.",
    "I applied it before hosting relatives for lunch and nobody found it strong.",
    "My daughter filmed an unboxing for fun and I kept using it after.",
    "I wore it on a day I had three meetings back to back.",
    "The scent felt familiar in a comforting way on a lonely work trip.",
    "I bought it when a friend moved abroad and left her half bottle with me.",
    "My barista smiled and said something smelled pleasant, so that was nice.",
    "I wore it before a long shopping trip and it held up fine.",
    "The experience has been steady across the first three weeks of daily use.",
]

_INCENSE_EXTRA_OPENS = [
    "The housing society puja committee asked for mild incense and this worked.",
    "I lit one stick while waiting for the electrician and the room smelled calm.",
    "My toddler naps in the next room and this does not disturb her.",
    "The box lasted longer than I expected with twice daily use.",
    "I bought it when our old temple supplier raised prices sharply.",
    "Rainy afternoons feel less dull when the prayer room smells warm.",
    "My uncle from the village approved which is the highest compliment here.",
    "I keep a few sticks in my office drawer for stressful afternoons.",
    "The holder stain washed off easily after a month of daily burns.",
    "I ordered after smelling it at a wellness stall in a mall.",
    "Our dog sits calmly nearby which was not true with our previous brand.",
    "I burned one before a video interview at home and it felt grounding.",
    "The neighbours on our floor did not complain about smoke for once.",
    "I bought extra before monsoon when ventilation is limited indoors.",
    "My prayer playlist sounds better when the room smells clean and soft.",
    "I tried it during a griha pravesh ceremony and guests appreciated it.",
    "The sticks are uniform in length which helps me budget daily use.",
    "I light one when my mother calls for evening chanting on speakerphone.",
    "Our cleaner said the prayer corner smells nicer on days we use this.",
    "I switched after my allergies acted up with a cheaper local bundle.",
    "The fragrance reminds me of my grandmother's house without copying it.",
    "I pack a few sticks when we visit our native place for holidays.",
    "My husband who avoids incense actually sat through puja without leaving.",
    "I bought it when we replaced the old wooden mandir shelf.",
    "The first stick burned evenly from tip to end without cracking.",
    "I use it before guests arrive so the home feels welcoming quickly.",
    "My sister in law asked for the link after a weekend stay with us.",
    "I ordered during a sale and still would pay full price honestly.",
    "The prayer room feels less stuffy on hot days with windows shut.",
    "I light one while folding laundry near the altar on busy mornings.",
    "Our society's senior citizens group recommended trying cleaner incense brands.",
    "I bought it after a meditation retreat where the hall smelled similar.",
    "The ash falls straight which makes cleanup faster on rushed weekdays.",
    "I keep one stick in my travel pouch for hotel room puja.",
    "My father said it smells like old temple shops in a good way.",
    "I tried it during a power cut evening when we relied on diyas.",
    "The box fits in our kitchen cabinet without taking much space.",
    "I burn one before my online yoga class in the living room.",
    "Guests with asthma visited and nobody had issues which relieved me.",
    "I ordered when our local shop ran out during festive rush.",
    "The scent feels honest rather than like air freshener spray.",
    "I use it on Ekadashi when we fast and pray longer at home.",
    "My teenage son noticed and said the house smells like a festival.",
    "I bought it to pair with fresh marigolds on the altar daily.",
    "The fragrance does not fight with the ghee lamp we light nightly.",
    "I tried one stick on the balcony and the breeze carried it gently.",
    "Our weekend cook said the kitchen corridor smells pleasant on puja days.",
    "I switched brands after moving to an apartment with smaller ventilation.",
    "The sticks arrived without the brittle ends I hate dealing with.",
    "I light one when I need five quiet minutes before the day explodes.",
    "My prayer group on WhatsApp shared photos and several asked about incense.",
    "I bought two boxes so we never run out before Sunday havan.",
    "The room still smells soft twenty minutes after the stick finishes.",
    "I use it when my mother-in-law visits because she prefers mild smoke.",
    "Our temple committee ordered bulk and I tried a stick from that lot.",
    "I keep the box near the diya tray so I remember to light one daily.",
    "The fragrance feels appropriate for both small flats and larger homes.",
    "I ordered after my neighbour's griha pravesh when the hall smelled lovely.",
    "My morning chai tastes better when the prayer room already smells warm.",
    "I bought it when we started teaching our child simple evening aarti.",
    "The sticks do not bend in our humid coastal weather which is a plus.",
    "I burn one before writing in my journal on quiet nights.",
    "Our weekend guests asked if we always keep the home smelling this welcoming.",
]

_CHAKRA_EXTRA_OPENS = [
    "I pour a few drops into my diffuser after evening yoga and the room feels softer.",
    "My shoulders carry desk tension and this oil helps my wind-down feel real.",
    "I dilute it with coconut oil before a light self massage on Sundays.",
    "The bottle lives next to my meditation cushion and I reach for it habitually.",
    "I started using it after breathwork sessions left me wanting a calmer close.",
    "A drop on my palms before pranayama has become a small nightly ritual.",
    "I tried it during a home spa evening with dim lights and slow music.",
    "My sister and I share the bottle for post-yoga neck rubs on weekends.",
    "I was skeptical about oils until this became part of my Sunday reset.",
    "The scent tells my body that work mode is over for the day.",
    "I use it before guided meditation videos when my mind feels scattered.",
    "My yoga teacher noticed I seemed calmer and asked what changed at home.",
    "I apply it sparingly before savasana and it deepens the quiet feeling.",
    "The aroma is gentle enough for our small bedroom without feeling heavy.",
    "I bought it when I committed to ten minutes of sitting practice daily.",
    "A warm shower plus a drop of this oil is my favourite weeknight combo.",
    "I keep it away from perfumes because I use it more like a wellness ritual.",
    "My partner joins me for stretching and we pass the bottle afterward.",
    "I tried it during a rainy evening when anxiety was running high.",
    "The oil absorbs quickly when mixed and does not leave a greasy film.",
    "I use it before journaling when I need to unload the day mentally.",
    "My mother borrows it for her evening reading chair routine.",
    "I was looking for something that feels calming without a clinical smell.",
    "The first week felt experimental, the third week felt necessary.",
    "I apply it before a body scan meditation and it helps me settle faster.",
    "Our balcony yoga sessions feel more complete with this in the background.",
    "I bought it after a retreat where silence and scent were paired gently.",
    "The bottle lasts because I only use a few drops per session.",
    "I mix it into unscented lotion for a slow leg massage before bed.",
    "My sleep playlist and this oil have become a paired habit.",
    "I use it when the city noise finally drops and the flat goes still.",
    "The fragrance supports focus during mantra counting without distracting me.",
    "I was tired of scrolling before bed and built this small ritual instead.",
    "My cousin recommended it for post-work decompression and she was right.",
    "I apply it before foam rolling on days my back feels tight from sitting.",
    "The scent fades gently rather than disappearing abruptly mid-evening.",
    "I keep a travel-sized mix for hotel rooms when work trips exhaust me.",
    "My evening chai tastes better when I have already slowed my breathing.",
    "I use it before gratitude journaling on nights I feel restless.",
    "The oil feels like a permission slip to stop being productive for a while.",
    "I tried many candles before this and prefer the subtlety of the oil.",
    "My weekend morning yoga feels more intentional when I start with a drop.",
    "I bought it during a stressful quarter and it still earns its shelf space.",
    "The aroma does not fight with the lavender soap I already use.",
    "I apply it before a silent sit and notice fewer urges to check my phone.",
    "My daughter says the living room smells peaceful on yoga nights.",
    "I was not chasing miracles, just a kinder way to end busy days.",
    "The texture blends smoothly and a little truly goes a long way.",
    "I use it when recovering from long commutes before lying down with a book.",
    "My breath feels slower within minutes of starting my usual routine with this.",
    "I recommend it to friends who want calm without another screen habit.",
    "The bottle cap seals well which matters in humid coastal weather.",
    "I apply it before chanting along with a playlist my aunt shared.",
    "Our weekend reset includes stretching, tea, and a few drops of this.",
    "I bought a second bottle so I never skip the habit when the first runs low.",
    "The scent feels warm on cool nights when I practice near the window.",
    "I use it before legs-up-the-wall pose when my feet ache from standing work.",
    "My mindfulness app reminders and this oil now trigger the same calm response.",
    "I feel more present during slow walks after applying it to my wrists.",
    "The experience has stayed consistent across my first month of evening use.",
]

_RITUAL_EXTRA_OPENS = [
    "I keep the bottle beside my prayer beads and use it sparingly each morning.",
    "My grandmother's tradition of lighting a lamp now includes this quiet scent.",
    "I bought it when we set up a small mandir in our new apartment.",
    "The fragrance feels appropriate when I sit with scripture before breakfast.",
    "I use a tiny amount before family puja on Sundays when everyone gathers.",
    "My spouse and I share the bottle near our altar shelf.",
    "I was drawn to something that honours routine without promising outcomes.",
    "The scent stays close while I chant and does not distract me.",
    "I apply it before visiting the temple early in the morning.",
    "My parents approved the choice during a festival weekend at their home.",
    "I bought it after reorganising our prayer corner with fresh flowers.",
    "The aroma feels warm during diya lighting when the house is otherwise quiet.",
    "I use it on days I read devotional texts in the evening.",
    "My sister gifted one to each sibling for our shared spiritual practice.",
    "I wanted a personal scent for reflection rather than social occasions.",
    "The bottle feels meaningful on the shelf next to our brass bell.",
    "I apply it before mantra practice when my mind feels too noisy.",
    "My children said the prayer room smells welcoming on weekend mornings.",
    "I bought it to mark a gentler start to my mornings after a hard year.",
    "The fragrance complements sandalwood paste without overpowering it.",
    "I use it when hosting a small puja for close friends at home.",
    "My father-in-law appreciated the subtlety during our joint aarti.",
    "I was not looking for transformation, just a scent for sincere habit.",
    "The scent helps me pause before rushing into email on work-from-home days.",
    "I apply it before evening lamp lighting while the street noise fades.",
    "My cousin recommended the collection for people who pray daily at home.",
    "I bought it during a month I wanted more structure in spiritual practice.",
    "The fragrance feels respectful when elders are present for ceremonies.",
    "I keep it for personal use rather than wearing out to crowded events.",
    "My morning walk to the corner temple feels complete with this gentle scent.",
    "I use it when fasting on Ekadashi and sitting longer with prayers.",
    "The aroma lingers softly while I arrange flowers on the altar.",
    "I bought it after a priest suggested finding a calm personal ritual scent.",
    "My journal entries feel more grounded on days I include this small step.",
    "I apply it before reading horoscope notes with friends over tea.",
    "The bottle arrived before a family muhurat day and I have used it since.",
    "I wanted something tied to tradition that still feels wearable at home.",
    "My mother keeps hers near the Tulsi plant and I copied the idea.",
    "I use it when my mind needs a bridge between commute stress and evening puja.",
    "The scent does not compete with incense smoke in our prayer room.",
    "I bought it as a meaningful gift to myself after completing a vow.",
    "My neighbour smelled it during shared terrace aarti and asked gently about it.",
    "I apply it before silent sitting when the city feels too loud inside my head.",
    "The fragrance feels like a quiet companion rather than a statement.",
    "I use it on birth star days as a personal remembrance, not a superstition.",
    "My family liked that it smells peaceful without feeling old-fashioned.",
    "I bought a spare bottle to keep at my parents' home when I visit.",
    "The scent supports my habit of gratitude lists before sleep.",
    "I apply it before wrapping prasad boxes during festive prep at home.",
    "My ritual feels more complete when scent is part of the preparation.",
    "I was hesitant about themed spiritual products but this felt understated.",
    "The bottle sits among prayer books and looks natural there.",
    "I use it when leading a short aarti for my children on school holidays.",
    "My partner noticed I seem calmer on evenings when this is part of puja prep.",
    "I bought it after returning from a pilgrimage wanting to keep the feeling.",
    "The fragrance feels appropriate for both solo prayer and family gatherings.",
    "I apply it before lighting camphor because the combination feels harmonious.",
    "My aunt said it smells like devotion without being dramatic.",
    "I keep the habit small: lamp, chant, one dab, silence.",
    "The experience has felt sincere across my first two months of use.",
]

BANKS: dict[str, dict] = {
    "incense": _bank(_INCENSE_OPEN + _INCENSE_EXTRA_OPENS, _INCENSE_MID, _INCENSE_CLOSE, _INCENSE_SHORT),
    "perfume": _bank(_PERFUME_OPEN + _WEAR_EXTRA_OPENS, _PERFUME_MID, _PERFUME_CLOSE),
    "planet": _bank(_PLANET_OPEN + _RITUAL_EXTRA_OPENS, _PLANET_MID, _PLANET_CLOSE),
    "chakra": _bank(_CHAKRA_OPEN + _CHAKRA_EXTRA_OPENS, _CHAKRA_MID, _CHAKRA_CLOSE),
    "nakshatra": _bank(_NAKSHATRA_OPEN + _RITUAL_EXTRA_OPENS, _NAKSHATRA_MID, _NAKSHATRA_CLOSE),
    "zodiac": _bank(_ZODIAC_OPEN + _WEAR_EXTRA_OPENS, _ZODIAC_MID, _ZODIAC_CLOSE),
    "love": _bank(_LOVE_OPEN + _WEAR_EXTRA_OPENS[:45], _LOVE_MID, _LOVE_CLOSE),
    "stress": _bank(_STRESS_OPEN + _CHAKRA_EXTRA_OPENS[:45], _STRESS_MID, _STRESS_CLOSE),
    "luxury": _bank(_LUXURY_OPEN + _WEAR_EXTRA_OPENS[:35], _LUXURY_MID, _WEAR_CLOSE),
    "spiritual": _bank(_PLANET_OPEN + _RITUAL_EXTRA_OPENS, _PLANET_MID, _PLANET_CLOSE),
    "bestseller": _bank(_BESTSELLER_OPEN + _WEAR_EXTRA_OPENS, _WEAR_MID, _WEAR_CLOSE),
    "gift": _bank(_GIFT_OPEN + _WEAR_EXTRA_OPENS[:40], _GIFT_MID, _WEAR_CLOSE),
    "apsara": _bank(_APSARA_OPEN + _WEAR_EXTRA_OPENS[:40], _APSARA_MID, _WEAR_CLOSE),
    "astrology": _bank(_ASTROLOGY_OPEN + _RITUAL_EXTRA_OPENS[:45], _ASTROLOGY_MID, _WEAR_CLOSE),
    "mood": _bank(_MOOD_OPEN + _CHAKRA_EXTRA_OPENS[:40], _MOOD_MID, _CHAKRA_CLOSE),
    "festival": _bank(_FESTIVAL_OPEN + _WEAR_EXTRA_OPENS[:40], _FESTIVAL_MID, _WEAR_CLOSE),
    "daily": _bank(_DAILY_OPEN + _WEAR_EXTRA_OPENS, _WEAR_MID, _WEAR_CLOSE),
    "meditation": _bank(_CHAKRA_OPEN + _CHAKRA_EXTRA_OPENS, _CHAKRA_MID, _CHAKRA_CLOSE),
    "premium": _bank(_PREMIUM_OPEN + _WEAR_EXTRA_OPENS[:35], _LUXURY_MID, _WEAR_CLOSE),
    "limited": _bank(_LIMITED_OPEN + _WEAR_EXTRA_OPENS[:40], _LIMITED_MID, _WEAR_CLOSE),
    "seasonal": _bank(_SEASONAL_OPEN + _WEAR_EXTRA_OPENS[:40], _SEASONAL_MID, _WEAR_CLOSE),
    "generic": _bank(_GENERIC_OPEN + _WEAR_EXTRA_OPENS, _WEAR_MID, _WEAR_CLOSE),
}
