"""Collection-specific authentic review body generators."""

SHORT = "{{ prv_short }}"

# Each generator returns a list of unique review bodies for its collection.


def _planet_bodies():
    return [
        f"Honestly pehle Navagraha attars ko thoda gimmick lagta tha. {SHORT} subah puja se pehle lagati hoon—mann shaant rehta hai, sandal jaisi warmth skin par, bilkul loud nahi.",
        f"Mummy ne graha shanti ke din suggest kiya. {SHORT} ka dry-down warm aur grounded hai. Temple jaate waqt ek settled feel milta hai.",
        f"Friend ne gift kiya. Pehle din unsure thi, ab Sunday havan se pehle lagana habit ban gaya. Resin note subtle hai, premium feel.",
        f"Surya wale rituals ke liye liya tha—confidence ke liye nahi drama ke liye. Wrist par chhoti dot kaafi hai office ke baad bhi.",
        f"Chandra attar jaisa cool floral nahi, par {SHORT} evening aarti ke baad perfect lagta hai. Moon energy wala calm, sach bolu.",
        f"Japa mala ke saath use karta hoon. Scent chant ke rhythm mein blend ho jata hai. Alcohol perfume se switch kiya—skin happier.",
        f"Guru purnima pe order kiya. {SHORT} lagane ke baad mandir wali feeling ghar mein bhi aa jati hai. Bottle heavy, pour controlled.",
        f"Navgraha prayer ke baad lagaya—waise koi miracle nahi, par breath slow ho jata hai. Kurta par zyada tikta hai than skin.",
        f"Pehli baar attar try kar raha tha. {SHORT} sharp start, baad mein creamy wood. Wife ne compliment diya dinner par.",
        f"Saturn energy wala grounding chahiye tha. {SHORT} deep wood note hai, patience wala vibe. Daily nahi, ritual days pe.",
        f"Instagram reel se dekha, cautious order. {SHORT} worth it—temple smoke type warmth without actual dhoop.",
        f"Rahu/Ketu remedies ke liye astrologer ne attar suggest kiya. {SHORT} smoky resin feel, intimidating nahi.",
        f"Mercury days pe meetings hoti hain—{SHORT} subtle clarity deta hai. Colleague ne lift mein poocha kya lagaya.",
        f"Mangal wale din gym ke baad lagata hoon. Spice note hai par skin par soft. Energy boost jaisa nahi, focus jaisa.",
        f"Jupiter ke liye liya—warm resin, thoda saffron vibe. Study session se pehle lagana achha lagta hai.",
        f"Venus day pe date night—{SHORT} romantic nahi loud, intimate warmth. Partner ko pasand aaya.",
        f"Ketu wala detachment mood—{SHORT} meditative wood, moksha vibe nahi pretentious. Cushion ke paas lagake sit karta hoon.",
        f"Shani remedy ke time use karti hoon. Dark wood, patient dry-down. Instant gratification wala scent nahi—aur yahi baat hai.",
        f"Budh attar energy—green herb feel {SHORT} mein clearly hai. Presentation day pe lagaya, calm rehti thi.",
        f"Temple queue mein wait karte waqt lagati hoon. Grounding milta hai, garmi mein bhi overwhelm nahi.",
        f"Father ko gift kiya retirement pe. Unhone kaha cotton kurta par ab bhi smell hai teen din baad.",
        f"Morning puja + chai + {SHORT} = meri daily trio. Subtle projection, par mood shift real hai.",
        f"Planetary remedy box mein tha. Honestly best product tha box ka. Baaki gemstones rakhe, yeh use hota hai.",
        f"Ghar ke mandir mein diya jalane se pehle lagata hoon. Resin aur sandal blend natural lagta hai.",
        f"First bottle khatam, doosra order. Batch consistency achhi hai—pehle jaisa hi warm dry-down.",
        f"4 stars—opening thoda sharp lagta hai mere taste ko. Dry-down perfect hai isliye ruk gayi.",
        f"Wedding season mein guest ke roop mein pehna. Humid hall mein bhi fabric par tik gaya.",
        f"Layered with coconut oil—longevity badh gayi. {SHORT} solo bhi achha hai, layered aur rich.",
        f"Travel pouch mein rakha. Flight ke baad bhi scent intact, leak nahi hua.",
        f"Puja thali ready karte waqt lagana ritual ban gaya. Devotional feel, costume jewellery nahi.",
        f"Evening walk ke baad lagati hoon. Neighbours nahi poochte, par ghar mein soft trail.",
        f"Nani ne kaha pehle attar aise hi lagate the. {SHORT} wahi purana warmth, modern bottle.",
        f"Graha shanti path ke din pandit ji ne notice kiya—attar ki baat ki. Achha sign laga.",
        f"Office stress ke baad wrist par dot. {SHORT} shoulder tension kam feel hoti hai, weird but true.",
        f"Monsoon mein ek extra dab chahiye tha. Expected hai, phir bhi fabric par hold surprising.",
        f"Ketu meditation se pehle—quiet wood, no floral distraction. Silence ke saath match.",
        f"Surya attar comparison—{SHORT} zyada balanced. Not too bright, not too dull.",
        f"Recommended by cousin jo astrology follow karti hai. Birth chart ke hisaab se planet pick kiya.",
        f"Gift wrap premium tha. Unboxing se lekar scent tak thoughtful laga.",
        f"Honestly {SHORT} brochure jaisa nahi smell karta. Human, thoda nostalgic.",
        f"Navgraha set se ek bottle—yeh sabse zyada use hota hai. Daily spiritual uniform.",
        f"Headache prone hoon—isse trigger nahi hua. Alcohol perfumes se switch ka reason yahi.",
        f"Cap click satisfying hai. Chhoti cheez hai par luxury signal deti hai.",
        f"Aarti ke baad lagane ki habit—diya smoke ke saath complement, clash nahi.",
        f"4 stars—projection kam hai wedding hall ke liye. Ghar ke puja ke liye bilkul sahi.",
        f"Pulse points pe do drop. Chhoti quantity, zyada bottle life. Economical bhi hai.",
        f"Retrograde season meme tha—scent genuinely calming raha though.",
        f"Husband usually ignore karta hai fragrances. {SHORT} ke baad poocha ghar mein kya change hua.",
        f"Sunday reset—ghar saaf, {SHORT} lagao, mann halka. Simple ritual.",
        f"Temple visit se pehle shower skip days pe bhi fresh feel deta hai.",
        f"Jyotish consultation ke baad order kiya. Remedy feel without superstition vibe.",
        f"Fabric test: silk dupatta par 24h faint trace. Linen kurta par zyada.",
        f"Kid ne kaha 'nice smell'—ghar mein rare compliment.",
        f"Only wish: bigger bottle option for daily users. Scent 5 stars.",
        f"First attar from Anand Rasa. {SHORT} ne impression achha banaya—aur collections explore karungi.",
        f"Evening journal likhte waqt lagati hoon. Focus better lagta hai, placebo ho sakta hai par kaam karta hai.",
        f"Guru dakshina ke saath guru ji ko diya. Unhone appreciate kiya—natural ingredients ki baat ki.",
        f"Rahu energy ambitious projects ke liye—{SHORT} deep smoky, late night work sessions.",
        f"Chandra calm chahiye tha emotional week mein. {SHORT} ne help ki—soft, cool dry-down.",
        f"Mangal courage wala note subtle hai. Gym se pehle lagana ritual.",
        f"Budh clarity—green fresh open, meetings ke din. Elevator safe.",
        f"Shukra beauty ritual—self-care Sunday pe {SHORT}. Rose undertone nahi, warm musk.",
        f"Shani discipline—slow burn scent for slow goals. Long term projects ke saath pair.",
        f"Ketu liberation—meditation cushion ke paas. Detachment practice mein anchor.",
        f"Graha dosha nahi samajhti fully, par {SHORT} peaceful lagta hai. Worth trying.",
        f"Navgraha yantra ke paas rakh ke lagaya—cheesy laga par mood achha tha.",
        f"Incense ke baad attar—complementary layering. Puja room staple ban gaya.",
        f"Corporate diwali gift list mein add kiya. Clients ne positive feedback diya.",
        f"Restock during festival rush—delivery time achha tha, scent consistent.",
        f"4 stars—box thoda dented aaya. Bottle safe thi, scent unaffected.",
        f"Pehle attar sticky samajhti thi. {SHORT} clean dry-down, no grease feel.",
        f"Morning sunlight mein lagane ka alag hi maza. Solar energy literal aur metaphorical.",
        f"Night owl hoon—Chandra type calm {SHORT} se milta hai before sleep routine.",
        f"Chart reading ke din wear kiya. Astrologer friend ne casually nod kiya.",
        f"Meditation app session se pehle—breath anchor ke liye. Subtle but helpful.",
        f"Varanasi trip pe liya tha—ghar wapas yaad dilata hai. Travel memory scent.",
        f"Anand Rasa ka pehla order tha. {SHORT} se trust build hua brand par.",
        f"Wrist par lagane se zyada kurta collar par achha lagta hai. Personal preference.",
        f"Sensitive skin—week long trial, no rash. Alcohol-free claim believable laga.",
        f"Surprisingly office mein bhi chal gaya—ek dot, no complaints.",
        f"Baarish ke din terrace pe chai aur {SHORT}. Monsoon ritual ban gaya.",
        f"Grandmother ki attar bottle yaad dilayi—modern packaging, purani warmth.",
        f"Planetary energy samajhne se pehle bhi achha lagta tha—ab context aur mil gaya.",
        f"Honest review: instant wow nahi, slow love hai. Week doosre se samajh aaya.",
        f"Puja ke baad family compliments—subtle scent, sabko pasand.",
        f"Japa count ke saath scent rhythm—weird combo par kaam karta hai.",
        f"Ekdum subtle projection—log paas aake poochte hain, door se announce nahi.",
        f"Premium feel bottle mein clearly hai. Pour control achha, waste nahi hota.",
        f"Mast lagta hai Sunday ko—no rush, slow scent, slow day.",
        f"Navgraha set mein yeh bottle sabse pehle khatam hoti hai ghar pe.",
    ]


def _zodiac_bodies():
    return [
        f"Birthday month mein apne rashi ke liye liya. {SHORT} personal lagta hai—jaise signature scent ho.",
        f"Sister ko Leo rashi gift di. Unhone kaha daily wear kar rahi hain—rare for her.",
        f"Aries energy bold hai—{SHORT} bhi confident open, par obnoxious nahi.",
        f"Taurus wala comfort chahiye tha. Warm sandal-rose dry-down, stable feel.",
        f"Gemini dual mood—{SHORT} morning fresh, evening thoda deeper. Interesting shift.",
        f"Cancer rashi—emotional comfort scent. Soft, nurturing, blanket jaisa.",
        f"Leo gift for myself. Royalty vibe without gold glitter smell. Charisma subtle.",
        f"Virgo colleague ko gift—clean, precise scent profile. Unko pasand aaya.",
        f"Libra balance—floral wood harmony. Date night pe compliment mila.",
        f"Scorpio intensity—{SHORT} deep, mysterious dry-down. Not for everyone, mujhe pasand.",
        f"Sagittarius travel scent ban gaya. Airport to hotel, consistent character.",
        f"Capricorn discipline—office safe, serious, long-lasting. Daily driver potential.",
        f"Aquarius unique—{SHORT} aloof start, warm heart note baad mein.",
        f"Pisces sensitivity—dreamy soft, meditation friendly. Headache nahi hota.",
        f"Chart reading party mein sab ne apna rashi wear kiya. Fun experience.",
        f"Wife ne husband ko rashi gift kiya anniversary pe. He actually uses it daily.",
        f"Pehle zodiac scents cheesy lagte the. {SHORT} surprisingly mature.",
        f"Rashi ke traits padh ke order kiya—scent match karta hai honestly.",
        f"Office mein daily signature. Colleagues ne adapt kar liya, ab normal.",
        f"Wedding guest—rashi scent conversation starter. Teen logon ne same brand order kiya.",
        f"Instagram astrology page se link mila. Cautious buy, ab restock.",
        f"4 stars—expected louder for Leo energy. Subtle hai par classy.",
        f"Friend referral—uska Cancer attar pasand tha, mera Libra bhi achha nikla.",
        f"Alcohol perfume se switch—skin gentler, scent personal.",
        f"Layer moisturizer pe—longevity badhi. Rashi scent aur bhi skin-close.",
        f"Festive season daily wear. Compliments milte hain, overkill nahi.",
        f"Gifting rashi attar—thoughtful lagta hai astrology lovers ko.",
        f"Horoscope app notification ke baad order kiya—impulse par achha nikla.",
        f"Partner same sign—matching attars cute ritual ban gaye.",
        f"Confidence boost nahi fake—{SHORT} bas feel-good reminder hai.",
        f"Kurta par hold achha. Wedding season mein reapply kam karna pada.",
        f"First attar try—zodiac entry point achha tha. Personal connection.",
        f"Scorpio friend ko gift—woh obsessed ho gayi. Best gift feedback ever.",
        f"Virgo perfectionist—scent clean dry-down pasand aaya. No messy sweetness.",
        f"Aries gym bag mein—post workout fresh. Spice note subtle.",
        f"Gemini mood swings—scent bhi shift karta hai skin chemistry se. Fun.",
        f"Cancer homebody—Sunday cooking ke saath {SHORT}. Cozy.",
        f"Leo stage presentation pe—confidence scent. Backstage dab.",
        f"Libra couple therapy joke—harmony scent actually calming laga.",
        f"Sagittarius road trip essential. One bottle, ten days.",
        f"Capricorn board meeting—subtle power scent. No distraction.",
        f"Aquarius art gallery opening—unique without trying hard.",
        f"Pisces poetry night—soft sillage, intimate circle compliment.",
        f"Rashi gift set se ek—favourite nikla. Baaki bhi good.",
        f"Mom ko mother's day rashi gift. Daily morning walk pe lagati hain.",
        f"College campus—subtle trail, classmates curious.",
        f"4 stars—projection low for party. Daily wear ke liye perfect.",
        f"Honest—astrology believer nahi, scent phir bhi achha.",
        f"Birth chart matching gift for couple. Sweet gesture, good scents.",
        f"Retrograde survival kit mein—rashi attar included. Mood help.",
        f"Wrist dot enough for office. Elevator safe, confirmed.",
        f"Fabric longevity—cotton shirt next day faint trace.",
        f"Premium bottle feel. Gift worthy presentation.",
        f"Repeat customer—teen rashi bottles, sab consistent quality.",
        f"Diwali pe rashi gifts—family ne appreciate kiya thoughtfulness.",
        f"Date night rashi scent—partner noticed, positive.",
        f"Sensitive skin trial—no issues week long.",
        f"Travel size wish hai. Full bottle handbag mein heavy.",
        f"Astrology club meetup—everyone compared scents. Fun afternoon.",
        f"Sach bolu—{SHORT} daily uniform ban sakta hai. Not boring though.",
        f"Wedding sangeet—rashi scent with outfit. Cohesive vibe.",
        f"Monsoon humidity—behaved well. Extra dab once.",
        f"Winter shawl par beautiful carry. Warm rashi energy literal.",
        f"Summer wedding—didn't melt sweet. Impressed.",
        f"First Anand Rasa order—zodiac hook worked. Exploring planet next.",
        f"Compliment from stranger at cafe—rare moment.",
        f"Kid said smells nice—home win.",
        f"Layering fail with oud—solo best for rashi scents.",
        f"Evening aarti plus rashi attar—double ritual. Peaceful.",
        f"Corporate gift rashi based on client sign—personal touch appreciated.",
        f"Restock alert subscribed—can't run out mid month.",
        f"4 stars—delivery late during festival. Scent made up for it.",
        f"Pehle week unsure, doosre week love. Slow burn product.",
        f"Rashi pride without cringe—{SHORT} nails the balance.",
        f"Book club astrology theme—scents matched discussion.",
        f"Husband skeptical, ab khud order karta hai. Conversion story.",
        f"Gym then rashi attar—fresh without shower rush.",
        f"Night drive scent—car AC cozy.",
        f"Premium feel worth price. Daily cost per wear low actually.",
        f"Mast daily signature—subtle, personal, consistent.",
        f"Waise astrology gift cliche hai—par yeh genuinely useful nikla.",
        f"Chart reader recommended—fit my rashi traits she said.",
        f"Honest drawback: cap tight for arthritic hands. Scent still 5 star.",
    ]


def _nakshatra_bodies():
    return [
        f"Birth star ke hisaab se liya—{SHORT} calming lagta hai evening prayers mein.",
        f"Astrologer ne nakshatra attar suggest kiya. Pehle doubtful thi, ab ritual staple.",
        f"Rohini energy—beauty aur growth vibe. Scent soft floral, skin par gentle.",
        f"Ashwini healing speed—fresh herb open, light feel. New beginnings scent.",
        f"Pushya nourishment—warm stable dry-down. Family puja days pe.",
        f"Ardra storm emotion—intense start, calm end. Transformation wala arc.",
        f"Magha royalty—deep authoritative wood. Ancestor remembrance days.",
        f"Revati compassion—tender close, completion energy. Peaceful nights.",
        f"Nakshatra homam ke din pehna—pandit ne nod kiya. Small validation.",
        f"Vedic consultation ke baad order. Birth star alignment personal lagta hai.",
        f"Chanting practice mein—scent breath ke saath. Meditative pairing.",
        f"Wedding muhurat shopping—nakshatra gift for bride. She cried happy.",
        f"New moon night ritual—{SHORT} quiet anchor. Cosmic calm cheesy par real.",
        f"Ancestral remembrance—grandmother ki yaad. Traditional warmth modern bottle.",
        f"4 stars—projection very soft. Nakshatra ritual ke liye sahi hai.",
        f"Janma nakshatra gift from brother. Thoughtful beyond typical gift.",
        f"Evening prayers staple—mann shaant, scent subtle.",
        f"Krittika fire energy—sharp spice open, warm wood dry-down.",
        f"Bharani transformation—deep rose, intense par beautiful.",
        f"Mrigashira searching—curious fresh note, exploratory feel.",
        f"Punarvasu renewal—clean restart scent after tough week.",
        f"Ashlesha mystical—coiled depth, not for everyone.",
        f"Purva Phalguni pleasure—warm romantic undertone subtle.",
        f"Uttara Phalguni partnership—balanced harmony scent.",
        f"Hasta skill—precise clean floral wood.",
        f"Chitra bright—jewel-like clarity, sparkling open.",
        f"Swati independence—airy free note, wind vibe.",
        f"Vishakha determination—focused resin trail.",
        f"Anuradha devotion—friendship warmth, loyal scent.",
        f"Jyeshtha elder wisdom—mature deep dry-down.",
        f"Mula roots—earthy grounding, get to the point scent.",
        f"Purva Ashadha invincible—bold warm confidence.",
        f"Uttara Ashadha victory—steady lasting character.",
        f"Shravana listening—quiet receptive calm.",
        f"Dhanishtha wealth rhythm—musical warm pulse.",
        f"Shatabhisha healing hundred—cool medicinal herb hint.",
        f"Purva Bhadrapada spiritual fire—intense sacred.",
        f"Uttara Bhadrapada depth—profound slow dry-down.",
        f"Instagram vedic page se dekha. {SHORT} authentic laga, gimmick nahi.",
        f"First nakshatra attar—impressed. Exploring others now.",
        f"Layer coconut oil—vedic ritual style. Longevity improved.",
        f"Temple visit birth star day—special scent for special day.",
        f"Mom same nakshatra—matching scents cute tradition started.",
        f"Fabric hold overnight—cotton saree faint morning trace.",
        f"Sensitive skin—alcohol-free gentle. Week trial fine.",
        f"Gift for astrology lover—hit. They knew their star immediately.",
        f"Honest—nakshatra names confusing, scent simple achha.",
        f"Peaceful fragrance sach mein—aggressive notes nahi.",
        f"Puja room corner scent—meditation adjacent.",
        f"4 stars—wish nakshatra guide booklet included. Scent great.",
        f"Restock same star—batch consistent thankfully.",
        f"Travel memory—Rishikesh trip purchase, ghar pe calm.",
        f"Wife birth star gift—she wears daily now.",
        f"Office unlikely place—but wrist dot works subtle.",
        f"Monsoon extra dab—expected. Still lovely.",
        f"Winter evening prayers—warm nakshatra hold.",
        f"Summer light enough—surprised for oil attar.",
        f"Compliment at family function—aunt recognized quality.",
        f"Kid calm around scent—bonus for home puja.",
        f"Corporate gift nakshatra based—client touched.",
        f"Slow love product—week two appreciation.",
        f"Chart on fridge, attar on dresser—aligned aesthetic.",
        f"Muhurat shopping impulse—best impulse ever.",
        f"Pehle attar—nakshatra entry perfect for spiritual beginners.",
        f"Evening journal nakshatra theme—scent sets mood.",
        f"Guru purnima gift set—star attar highlight.",
        f"Honest drawback: small bottle for daily users. Quality undeniable.",
        f"Breathwork class—nakshatra scent anchor. Focus improved maybe placebo.",
        f"Family puja collective—everyone different star, shared brand.",
        f"Wedding guest nakshatra conversation—bonding moment.",
        f"Premium packaging—unboxing respect for tradition.",
        f"Repeat third bottle—loyalty earned.",
        f"Sach bolu peaceful hai—exactly what description promised.",
        f"Headache prone—no trigger. Important for ritual scents.",
        f"Layering with incense—complementary not clash.",
        f"First Anand Rasa—nakshatra line hooked me.",
        f"Baarish aur birth star ritual—cozy combo.",
        f"Subtle projection—temple appropriate.",
        f"Worth it for personal fragrance ritual aligned with star.",
        f"Mast evening scent—calm mind before sleep.",
        f"Astrologer casual compliment—made my day.",
        f"Honest 4 star—opening sharp, dry-down divine.",
        f"Birth star pride without shouting—balance achha.",
    ]


def _chakra_bodies():
    return [
        f"Root chakra grounding—{SHORT} earthy cedar vibe. Yoga ke pehle lagati hoon.",
        f"Sacral creativity—warm amber floral. Painting sessions ke saath.",
        f"Solar plexus confidence—bright spice, leadership meetings.",
        f"Heart chakra—soft rose compassion. Breakup recovery gentle support.",
        f"Throat clarity—herb clean note. Teaching days essential.",
        f"Third eye focus—cool spice meditation. Ajna point dab ritual.",
        f"Crown connection—airy floral resin. Morning sit practice.",
        f"Reiki session mein practitioner ne notice kiya. Energy work complement.",
        f"Sound bath—chakra scent layered experience. Immersive.",
        f"Morning yoga mat scent—root anchor literal.",
        f"Evening journal heart chakra—emotional release writing.",
        f"Breathwork class recommendation—throat chakra speaker days.",
        f"Healing circle—everyone different chakra, shared calm.",
        f"Muladhara security—patchouli earth. Grounded after travel.",
        f"Svadhisthana flow—passion without overwhelm.",
        f"Manipura fire—solar plexus bold but controlled.",
        f"Anahata harmony—relationship repair scent gentle.",
        f"Vishuddha truth—honest conversations easier feel?",
        f"Ajna insight—study sessions focus aid.",
        f"Sahasrara peace—crown meditation divine calm.",
        f"4 stars—expected stronger projection. Chakra work subtle anyway.",
        f"Chakra meditation app sync—scent ritual cue.",
        f"Gift for yoga teacher—she loved root and heart.",
        f"Sensitive skin chakra oils—no irritation.",
        f"Layer unscented lotion—chakra hold extended.",
        f"First chakra attar set—root favourite so far.",
        f"Instagram yoga influencer rec—tried, keeping.",
        f"Corporate wellness gift chakra set—HR hit.",
        f"Honest—chakra sceptic, scent still achha daily.",
        f"Evening bath then heart chakra—self love routine.",
        f"Solar plexus presentation day—confidence dab.",
        f"Throat podcast recording—clear vibe placebo maybe.",
        f"Third eye exam week—focus scent superstition helps.",
        f"Crown Sunday silence—no music just scent.",
        f"Balance energy body marketing—scent delivers calm at least.",
        f"Seven bottle exploration—each distinct, none bad.",
        f"Repeat root bottle third time—consistency good.",
        f"Monsoon yoga indoors—chakra scent cozy.",
        f"Winter root grounding essential—seasonal match.",
        f"Summer solar light—bright not heavy.",
        f"Wedding stress heart chakra—emotional stability.",
        f"Travel sacral—creativity on road trips.",
        f"Office throat—meetings subtle communication aid.",
        f"Fabric kurta hold—chakra scents linger gentle.",
        f"Compliment holistic friend—she approved ingredients.",
        f"Kid calm near heart chakra scent—home peaceful.",
        f"Premium bottle chakra collection—display worthy.",
        f"Pehle attar chakra entry—educational and wearable.",
        f"Honest drawback: wish size bigger for daily yoga.",
        f"Meditation cushion nearby—scent association strong.",
        f"Energy balance cheesy word—feeling real though.",
        f"Restock heart and root—staples.",
        f"Gift set chakra—recipient explored all seven.",
        f"4 star—crown too airy for me, root perfect.",
        f"Sach bolu yoga mat scent ban gaya.",
        f"Headache free trial—important for breathwork.",
        f"Layering root then heart—interesting depth.",
        f"First Anand Rasa chakra—exploring planet next.",
        f"Evening wind down sacral—creative hobby time.",
        f"Solar gym pre-workout—fire energy subtle.",
        f"Throat singing practice—scent companion.",
        f"Third eye tarot night—mood set.",
        f"Crown temple visit—spiritual tourism scent.",
        f"Honest review: not magic, nice ritual tool.",
        f"Worth it for yoga serious practitioners.",
        f"Mast root grounding—ekdum earthy.",
        f"Baarish aur heart chakra—cozy healing.",
        f"Subtle projection—all chakra appropriate.",
        f"Family gift chakra curious sister—she converted.",
        f"Corporate retreat wellness bags—included.",
        f"Slow appreciation week two—depth emerges.",
        f"Chart no, chakra yes—easier entry point.",
        f"Premium feel each bottle—collection investment.",
        f"Honest 5 stars root—daily essential.",
        f"Teacher training gift—students ask which chakra.",
        f"Wrist vs chakra points—both work.",
        f"Incense plus chakra attar—ritual layered.",
        f"Sensitive skin week—passed.",
        f"Travel root only—portable grounding.",
        f"Compliment studio mate—shared brand.",
        f"Wish discovery set smaller sizes—try all.",
        f"Balance through smell—philosophy matches experience.",
        f"Repeat customer chakra line—trust built.",
        f"Evening anahata—gratitude journaling scent.",
        f"Manipura business launch—wore daily that week.",
        f"Honest—some chakras suit me more, quality all good.",
        f"First bottle heart—emotional month lifeline.",
        f"Worth premium price per wear calculation.",
    ]


# Export map
GENERATORS = {
    "planet": _planet_bodies,
    "zodiac": _zodiac_bodies,
    "nakshatra": _nakshatra_bodies,
    "chakra": _chakra_bodies,
}
