"""Collection-specific review bodies — part 3."""

SHORT = "{{ prv_short }}"


def _apsara_bodies():
    return [
        f"Kathak rehearsal {SHORT}—stage presence scent subtle grace.",
        f"Sangeet night bridal—divine floral not overpowering.",
        f"Classical dance recital—teacher compliment backstage.",
        f"Mythology lover gift—apsara reference understood appreciated.",
        f"Temple festival wear—heritage bloom accurate.",
        f"Photo shoot getting ready—camera loves subtle glow.",
        f"Heritage wedding guest—timeless beauty vibe.",
        f"Art collector appreciation—bottle display worthy.",
        f"Poetry evening intimate—mythic rose soft.",
        f"Temple jasmine note—authentic not synthetic.",
        f"Gold amber warmth—apsara aura cheesy name real feel.",
        f"Silk musk dry-down—graceful movement scent.",
        f"4 stars—stage sweat needs reapply performance long.",
        f"First apsara attar—unique line impressed.",
        f"Honest—not costume fragrance—artistic.",
        f"Sensitive skin performance makeup compatible.",
        f"Gift dancer friend—perfect niche.",
        f"Repeat performance season bottle.",
        f"Travel recital tour—one bottle.",
        f"Compliment audience member—rare.",
        f"Premium packaging gift artistic friend.",
        f"Instagram classical reel—product fit.",
        f"Honest drawback daily office odd.",
        f"Worth apsara collection promise.",
        f"Mast stage scent—elegant.",
        f"Baarish indoor rehearsal cozy floral.",
        f"Subtle divinity appropriate.",
        f"First Anand Rasa apsara—explore.",
        f"Evening performance ritual scent.",
        f"Sensitive migraine no trigger.",
        f"Gift mother classical music—uses concerts.",
        f"Repeat third recital season.",
        f"Honest 5 stars artistic use.",
        f"Layer moisturizer performance longevity.",
        f"Book launch mythology—scent matched.",
        f"4 star wish sample vial travel.",
        f"Worth heritage wedding guest.",
        f"Story scent narrative feels.",
        f"Family sangeet collective compliment.",
        f"Subtle temple jasmine true.",
        f"First attar artistic—niche success.",
        f"Honest review performer perspective.",
        f"Winter indoor performance warm floral.",
        f"Summer outdoor stage light enough.",
        f"Monsoon indoor rehearsal ok.",
        f"Compliment costume designer—fit.",
        f"Kid dance recital mom wore—sweet.",
        f"Premium mythic rose quality.",
        f"Slow appreciation art crowd.",
        f"Honest—not everyone daily wear.",
        f"Worth mythology enthusiast gift.",
        f"Travel performance essential.",
        f"Honest 5 stars stage grace.",
        f"Office unusual—weekend art ok.",
        f"Premium bottle vanity art deco.",
        f"Repeat loyal apsara line.",
        f"Sach bolu graceful scent.",
        f"Headache prone passed.",
        f"Gift sister kathak—cried happy.",
        f"Honest drawback niche appeal.",
        f"Repeat wedding season performances.",
        f"Evening poetry scent perfect.",
        f"Premium worth artistic splurge.",
        f"Honest review mythology match.",
        f"First bottle performance opened.",
        f"Mast heritage bloom.",
        f"Baarish creative afternoon.",
        f"Subtle apsara aura.",
        f"Worth exploring full line.",
        f"Honest 4 star projection soft stage.",
        f"Gift art history professor—hit.",
        f"Sensitive skin stage ok.",
        f"Corporate cultural event gift.",
        f"Worth premium artistry.",
        f"Travel national competition scent.",
        f"Honest review dancer approved.",
        f"First Anand Rasa artistic—hooked.",
        f"Layer subtle best solo.",
        f"Premium memorable performance.",
        f"Repeat recital must.",
        f"Honest 5 stars grace.",
        f"Wedding cultural program scent.",
        f"Mast divine floral subtle.",
        f"Baarish studio practice.",
        f"Subtle stage appropriate.",
        f"First performance nervous scent comfort.",
        f"Sach bolu timeless beauty.",
        f"Honest drawback mainstream office no.",
        f"Repeat artistic customer.",
        f"Evening temple festival wear.",
        f"Premium presentation artistic.",
        f"Honest review heritage accurate.",
        f"Photo shoot compliment photographer noticed.",
        f"Worth apsara philosophy match.",
    ]


def _astrology_bodies():
    return [
        f"Chart reading day {SHORT}—cosmic calm placebo powerful.",
        f"Astrologer visit wore—casual nod validation.",
        f"Gemstone pairing scent ritual—combined remedy feel.",
        f"Muhurat shopping impulse—aligned purchase.",
        f"Zodiac party everyone different signs—fun compare.",
        f"Retrograde season survival scent—meme real calm.",
        f"New year forecast party—scent conversation starter.",
        f"Couple compatibility reading—matching attars cute.",
        f"Remedy box scent best part—stones display.",
        f"Journaling stars evening—scent mood set.",
        f"Planet zodiac nakshatra umbrella—astrology lover paradise.",
        f"Vedic symbolism respectful—not gimmick feel.",
        f"4 stars—astrology sceptic still likes scent.",
        f"First astrology collection mix—exploring.",
        f"Honest—belief optional enjoyment mandatory.",
        f"Sensitive skin remedy wear fine.",
        f"Gift astro friend—perfect.",
        f"Repeat chart season bottle.",
        f"Travel consultation city—scent memory.",
        f"Compliment astrologer office—meta.",
        f"Premium packaging ritual respect.",
        f"Instagram astro reel—ordered.",
        f"Honest drawback jargon confusing booklet wish.",
        f"Worth astrology collection breadth.",
        f"Mast chart day scent.",
        f"Baarish forecast reading cozy.",
        f"Subtle celestial warm.",
        f"First Anand Rasa astro set—more.",
        f"Evening star gazing scent—cheesy fun.",
        f"Sensitive migraine ok.",
        f"Gift brother astro nerd—hit.",
        f"Repeat annual forecast ritual.",
        f"Honest 5 stars believer.",
        f"Layer ritual oils—traditional style.",
        f"Book astrology club—scents matched.",
        f"4 star delivery muhurat late funny.",
        f"Worth ritual set bundle.",
        f"Forecast mood scent helper.",
        f"Family astro dinner debate scent peace.",
        f"Subtle aligned aura marketing ok.",
        f"First attar astro entry—education.",
        f"Honest review sceptic friendly.",
        f"Winter solstice ritual wear.",
        f"Summer eclipse party scent.",
        f"Monsoon indoor reading calm.",
        f"Compliment tarot reader—niche.",
        f"Kid horoscope school project—mom wore sign.",
        f"Premium remedy presentation.",
        f"Slow belief build optional.",
        f"Honest—not fortune guarantee.",
        f"Worth astrology ritual set page.",
        f"Travel astro conference scent.",
        f"Honest 5 stars enthusiast.",
        f"Office chart day subtle dot.",
        f"Premium consult pick story.",
        f"Repeat multi axis explorer.",
        f"Sach bolu cosmic calm.",
        f"Headache prone passed.",
        f"Gift parents anniversary astro—sweet.",
        f"Honest drawback overwhelming choices.",
        f"Repeat festival astro gifts.",
        f"Evening remedy journaling.",
        f"Premium worth believer gift.",
        f"Honest review umbrella collection.",
        f"First ritual set opened eclipse.",
        f"Mast star sign gift.",
        f"Baarish indoor chart reading.",
        f"Subtle remedy wear.",
        f"Worth Vedic respect tone.",
        f"Honest 4 star sceptic enjoyment.",
        f"Gift colleague retrograde kit—laughed thanked.",
        f"Sensitive skin fine.",
        f"Corporate astro wellness trendy—worked.",
        f"Worth exploring all three axes.",
        f"Travel remedy pouch.",
        f"Honest review chart day ritual.",
        f"First Anand Rasa astro—planet next.",
        f"Layer incense chart—complete.",
        f"Premium celestial warm real.",
        f"Repeat loyal astro customer.",
        f"Honest 5 stars alignment fun.",
        f"Wedding muhurat scent—appropriate.",
        f"Mast forecast mood.",
        f"Baarish retrograde calm.",
        f"Subtle sky note.",
        f"First box ritual set—gateway.",
        f"Sach bolu astrology lover gift.",
        f"Honest drawback need guide.",
        f"Repeat chart reading annual.",
        f"Evening compatibility session scent.",
        f"Premium worth astro friend.",
        f"Honest review belief agnostic ok.",
    ]


def _mood_bodies():
    return [
        f"Rainy afternoon {SHORT}—mood lift real cozy.",
        f"Sunlit balcony Sunday—sunny musk vibe.",
        f"Creative block break—scent spark maybe.",
        f"Coffee shop work—subtle not distract.",
        f"Slow Sunday reset—feel good dry-down.",
        f"Post workout fresh—mood shift up.",
        f"Journal hour companion—soft shift.",
        f"Friends brunch compliment—light.",
        f"Solo drive playlist match—drive scent.",
        f"Playlist pairing weird works—mood sync.",
        f"4 stars—mood marketing sceptic still nice.",
        f"First mood tagged product—curious ok.",
        f"Honest—not antidepressant—afternoon helper.",
        f"Sensitive skin daily mood fine.",
        f"Gift friend breakup—gentle.",
        f"Repeat rainy season bottle.",
        f"Travel mood pouch—familiar.",
        f"Compliment cafe barista—funny.",
        f"Premium packaging self care.",
        f"Instagram mood reel—tried.",
        f"Honest drawback vague tag works anyway.",
        f"Worth mood collection experiment.",
        f"Mast rainy calm.",
        f"Baarish terrace mood boost.",
        f"Subtle feel good.",
        f"First Anand Rasa mood—more tags.",
        f"Evening wind down mood.",
        f"Sensitive migraine ok.",
        f"Gift sister exams—small comfort.",
        f"Repeat weather moods bottles.",
        f"Honest 5 stars rainy day.",
        f"Layer moisturizer mood longer.",
        f"Book rainy day read scent.",
        f"4 star sunny note weak rainy strong.",
        f"Worth emotional reset claim lite.",
        f"Balcony breeze scent accurate.",
        f"Family movie night mood.",
        f"Subtle cozy wrap vibe.",
        f"First attar mood—entry fun.",
        f"Honest review mood realistic.",
        f"Winter shawl mood cozy.",
        f"Summer balcony light.",
        f"Monsoon perfect match collection.",
        f"Compliment roommate calmer.",
        f"Kid noticed mom happier—cute.",
        f"Premium self care respect.",
        f"Slow habit mood pairing.",
        f"Honest—not magic happiness.",
        f"Worth trying mood curious.",
        f"Travel homesick mood fix lite.",
        f"Honest 5 stars rainy specialist.",
        f"Office Friday mood dot.",
        f"Premium feel good quality.",
        f"Repeat monsoon loyal.",
        f"Sach bolu mood lift subtle.",
        f"Headache prone passed.",
        f"Gift friend new job—fit.",
        f"Honest drawback tag gimmicky scent good.",
        f"Repeat playlist pairing ritual.",
        f"Evening creative mood.",
        f"Premium worth self gift.",
        f"Honest review mood agnostic.",
        f"First bottle rain opened.",
        f"Mast cozy wrap feel.",
        f"Baarish WFH mood.",
        f"Subtle shift accurate.",
        f"Worth mood tag explore.",
        f"Honest 4 star summer note prefer rain.",
        f"Gift moody teen—accepted.",
        f"Sensitive skin ok.",
        f"Corporate wellness mood trendy.",
        f"Worth premium afternoon treat.",
        f"Travel rainy trip scent.",
        f"Honest review weather pairing.",
        f"First Anand Rasa—mood tag ordered.",
        f"Layer subtle best.",
        f"Premium mood gift self.",
        f"Repeat seasonal mood.",
        f"Honest 5 stars rain lover.",
        f"Evening journal mood.",
        f"Mast playlist pair fun.",
        f"Baarish creative spark.",
        f"Subtle feel good dry-down.",
        f"First mood scent success.",
        f"Sach bolu rainy calm.",
        f"Honest drawback naming vague.",
        f"Repeat customer mood line.",
        f"Sunlit morning different bottle—both good.",
        f"Premium worth mood experiment.",
        f"Honest review emotional realistic.",
    ]


def _festival_bodies():
    return [
        f"Diwali prep {SHORT}—diya pairing perfect festive warmth.",
        f"Eid gathering subtle—not overpower food.",
        f"Onam sadya morning—gentle festive note.",
        f"Pongal harvest mood—traditional warm.",
        f"Holi brunch—survived color madness scent ok.",
        f"Christmas eve family—holiday musk cozy.",
        f"Navratri night—dance garba fabric hold.",
        f"Ganesh visarjan emotional—scent memory.",
        f"Baisakhi fair—outdoor festive appropriate.",
        f"Durga puja pandal—gathering scent subtle.",
        f"Celebration glow marketing—guests noticed.",
        f"Family room festive air—incense plus attar.",
        f"4 stars—heavy sweets environment compete.",
        f"First festival season Anand Rasa—repeat.",
        f"Honest—not firecracker scent thank god.",
        f"Sensitive skin festival wear fine.",
        f"Gift sibling diwali—success.",
        f"Repeat annual festival bottle.",
        f"Travel home festival—one bottle.",
        f"Compliment relatives subtle.",
        f"Premium packaging gift diwali.",
        f"Instagram festive reel—ordered.",
        f"Honest drawback festival only niche daily less.",
        f"Worth festival collection timing.",
        f"Mast diya pairing.",
        f"Baarish diwali indoor cozy.",
        f"Subtle tradition note.",
        f"First festival attar—ritual.",
        f"Evening puja festive—combined.",
        f"Sensitive migraine ok.",
        f"Gift parents anniversary diwali—touched.",
        f"Repeat navratri nine nights.",
        f"Honest 5 stars diwali user.",
        f"Layer festive best solo.",
        f"Book festival hosting scent.",
        f"4 star delivery festival eve stress.",
        f"Worth joyful resin claim.",
        f"Gathering scent accurate.",
        f"Family festival collective bottles.",
        f"Subtle festive hold.",
        f"First attar festival entry.",
        f"Honest review festival realistic.",
        f"Winter christmas shawl scent.",
        f"Summer eid light enough.",
        f"Monsoon onam indoor perfect.",
        f"Compliment neighbor pandal.",
        f"Kid festival outfit scent—cute.",
        f"Premium festive wrap.",
        f"Slow annual ritual build.",
        f"Honest—not replace traditions.",
        f"Worth festival tag explore.",
        f"Travel festival home scent.",
        f"Honest 5 stars diwali prep.",
        f"Office diwali subtle dot.",
        f"Premium festival gift worthy.",
        f"Repeat corporate diwali gifts.",
        f"Sach bolu festive warmth.",
        f"Headache prone passed.",
        f"Gift in laws festival—win.",
        f"Honest drawback year round less use.",
        f"Repeat holi survivor scent.",
        f"Evening aarti festival week.",
        f"Premium worth celebration.",
        f"Honest review gathering tested.",
        f"First diwali Anand Rasa—loyal.",
        f"Layer incense festive complete.",
        f"Premium tradition respect.",
        f"Repeat festival stock up.",
        f"Honest 5 stars pandal air.",
        f"Wedding festival overlap guest.",
        f"Mast celebration glow.",
        f"Baarish navratri indoor.",
        f"Subtle festive ease.",
        f"First bottle diwali opened.",
        f"Sach bolu festival hold.",
        f"Honest 4 star holi chaos reapply.",
        f"Repeat annual must.",
        f"Gift set festival highlight.",
        f"Sensitive skin festival ok.",
        f"Corporate festive hampers.",
        f"Worth premium festival feel.",
        f"Travel festival flight scent.",
        f"Honest review multi festival.",
        f"First festival collection—more.",
        f"Mast family room scent.",
        f"Baarish festive cozy.",
        f"Subtle joyful resin.",
        f"Worth festival collection purpose.",
        f"Honest drawback storage year round.",
        f"Repeat customer festival line.",
        f"Evening guest hosting scent.",
        f"Premium festive presentation.",
        f"Honest review tradition match.",
    ]


def _daily_bodies():
    return [
        f"Office commute {SHORT}—metro safe subtle dot.",
        f"College campus daily—classmates curious not choke.",
        f"Market errands quick dab—fresh feel.",
        f"School pickup mom scent—kid approved.",
        f"Gym bag post workout—subtle fresh.",
        f"Lunch break walk—reset scent.",
        f"Metro ride crowded—personal bubble.",
        f"WFH desk uniform—no decision fatigue.",
        f"Evening walk routine—daily staple.",
        f"Weekday uniform scent confirmed.",
        f"4 stars—weekend want something bolder.",
        f"First daily wear attar—success.",
        f"Honest—not office perfume cloud.",
        f"Sensitive skin daily month fine.",
        f"Gift husband office—daily use.",
        f"Repeat monthly restock.",
        f"Travel daily one bottle.",
        f"Compliment colleague rare subtle.",
        f"Premium feel daily affordable use.",
        f"Instagram office reel—tried.",
        f"Honest drawback boring good way.",
        f"Worth daily tag accurate.",
        f"Mast commute calm.",
        f"Baarish office WFH cozy.",
        f"Subtle trail accurate.",
        f"First Anand Rasa daily—staple.",
        f"Evening transition same bottle.",
        f"Sensitive migraine passed.",
        f"Gift fresher graduate—professional.",
        f"Repeat third month bottle.",
        f"Honest 5 stars office safe.",
        f"Layer moisturizer standard.",
        f"Book commute audiobook scent.",
        f"4 star summer extra dab.",
        f"Worth daily driver label.",
        f"Desk friendly confirmed.",
        f"Family noticed consistent scent.",
        f"Subtle all day ease.",
        f"First attar daily—gateway.",
        f"Honest review office realistic.",
        f"Winter scarf daily hold.",
        f"Summer AC office ok.",
        f"Monsoon humidity one dab extra.",
        f"Compliment elevator rare.",
        f"Kid hug approval daily.",
        f"Premium bottle desk aesthetic.",
        f"Slow routine automatic.",
        f"Honest—not statement scent.",
        f"Worth daily wear explore.",
        f"Travel business weekly—one bottle.",
        f"Honest 5 stars uniform.",
        f"Presentation day same daily—works.",
        f"Premium cost per wear low.",
        f"Repeat subscription wish.",
        f"Sach bolu office safe.",
        f"Headache prone daily ok.",
        f"Gift father retirement daily walks.",
        f"Honest drawback wish rollerball office.",
        f"Repeat loyal daily only.",
        f"Evening gym daily transition.",
        f"Premium worth everyday.",
        f"Honest review commute tested.",
        f"First bottle six weeks daily.",
        f"Mast wrist dot enough.",
        f"Baarish commute calm.",
        f"Subtle desk friendly.",
        f"Worth daily collection.",
        f"Honest 4 star want slightly more projection.",
        f"Gift colleague welcome—subtle.",
        f"Sensitive skin daily passed.",
        f"Corporate daily not applicable but WFH yes.",
        f"Worth premium daily math.",
        f"Travel daily pouch.",
        f"Honest review weekday staple.",
        f"First Anand Rasa—daily hook.",
        f"Layer unnecessary solo fine.",
        f"Premium daily luxury lite.",
        f"Repeat restock automatic.",
        f"Honest 5 stars reliability.",
        f"Wedding office next day daily back.",
        f"Mast easy layer.",
        f"Baarish WFH uniform.",
        f"Subtle repeat uniform.",
        f"First daily attar year—loyal.",
        f"Sach bolu weekday staple.",
        f"Honest drawback unexciting reliable.",
        f"Repeat customer daily line.",
        f"Evening walk daily end.",
        f"Premium feel everyday justified.",
        f"Honest review daily role perfect.",
    ]


def _meditation_bodies():
    return [
        f"Vipassana day {SHORT}—silent depth no distraction.",
        f"Breathwork class anchor—cushion calm real.",
        f"Silent retreat allowed scent—quiet room approved.",
        f"Morning sit sunrise—breath anchor scent.",
        f"Zafu session dot—focus aid subtle.",
        f"Guided app before—ritual cue.",
        f"Temple garden sit—zen wood vibe.",
        f"Sunrise sit routine—still mind helper.",
        f"Mantra hour—scent rhythm companion.",
        f"Candle meditation—slow inhale accurate.",
        f"4 stars—scent noticeable day three silence prefer none—optional use.",
        f"First meditation attar—keeping.",
        f"Honest—not replace practice—support.",
        f"Sensitive skin meditation fine.",
        f"Gift teacher training—students ask.",
        f"Repeat retreat bottle.",
        f"Travel retreat center—familiar calm.",
        f"Compliment fellow meditator—niche bond.",
        f"Premium packaging respectful.",
        f"Instagram meditation reel—tried sceptical ok.",
        f"Honest drawback scent association risk if skip practice.",
        f"Worth meditation collection purpose.",
        f"Mast cushion calm.",
        f"Baarish indoor sit cozy.",
        f"Subtle silent depth.",
        f"First Anand Rasa meditation—chakra also.",
        f"Evening sit wind down.",
        f"Sensitive migraine no trigger critical.",
        f"Gift father retirement meditation—uses.",
        f"Repeat monthly retreat.",
        f"Honest 5 stars morning sit.",
        f"Layer coconut traditional.",
        f"Book meditation memoir scent.",
        f"4 star strong for absolute silence purists.",
        f"Worth focus aid claim lite.",
        f"Retreat staple confirmed.",
        f"Family meditation corner scent.",
        f"Subtle mantra support.",
        f"First attar meditation entry perfect.",
        f"Honest review meditator realistic.",
        f"Winter morning sit warm wood.",
        f"Summer open window light.",
        f"Monsoon indoor sit perfect.",
        f"Compliment teacher—subtle.",
        f"Kid meditation club mom—calm home.",
        f"Premium retreat gift.",
        f"Slow habit cue strong.",
        f"Honest—not enlightenment juice.",
        f"Worth trying sitters.",
        f"Travel cushion scent memory.",
        f"Honest 5 stars breath anchor.",
        f"Office lunch sit dot—micro practice.",
        f"Premium worth spiritual tool.",
        f"Repeat ketu crown types.",
        f"Sach bolu still mind helper.",
        f"Headache prone passed essential.",
        f"Gift sangha friend—appreciated.",
        f"Honest drawback daily sit scent habit dependency mild.",
        f"Repeat retreat must pack.",
        f"Evening yoga nidra scent.",
        f"Premium quiet room appropriate.",
        f"Honest review silence respect.",
        f"First vipassana scent—optional ok.",
        f"Mast zen wood vibe.",
        f"Baarish sit window rain.",
        f"Subtle focus aid.",
        f"Worth meditation tag.",
        f"Honest 4 star wish unscented option too.",
        f"Gift monastery visit host—touched.",
        f"Sensitive skin daily sit fine.",
        f"Corporate mindfulness workshop gift.",
        f"Worth premium sit tool.",
        f"Travel silent retreat—packed.",
        f"Honest review years sitter.",
        f"First Anand Rasa—meditation hook.",
        f"Layer incense sit before—transition.",
        f"Premium retreat staple.",
        f"Repeat loyal meditation line.",
        f"Honest 5 stars morning practice.",
        f"Mantra hour confirmed.",
        f"Mast breath anchor.",
        f"Baarish meditation cozy.",
        f"Subtle slow inhale.",
        f"First bottle retreat opened.",
        f"Sach bolu cushion calm.",
        f"Honest drawback not for all traditions.",
        f"Repeat annual retreat.",
        f"Evening candle sit scent.",
        f"Premium worth sit practice.",
        f"Honest review optional tool respectful.",
    ]


def _premium_bodies():
    return [
        f"Flagship visit {SHORT}—consult pick staff knowledgeable.",
        f"Limited batch numbered—collector excitement.",
        f"Connoisseur buy—top tier resin real.",
        f"Perfume cabinet centerpiece—display pride.",
        f"Luxury fair sample—bought full.",
        f"Five star spa parallel—spa level hold.",
        f"Heirloom gift father—generational gesture.",
        f"Collector edition—batch depth noticeable.",
        f"Master blender event—story worth price.",
        f"Private consultation—skin match worked.",
        f"4 stars—price premium justified mostly.",
        f"First premium tier—benchmark.",
        f"Honest—not daily budget—special.",
        f"Sensitive skin premium gentle.",
        f"Gift wealthy uncle—approved.",
        f"Repeat premium annual treat.",
        f"Travel special occasion only.",
        f"Compliment understated luxury.",
        f"Premium hold hours realistic.",
        f"Instagram premium reel—sceptical pleased.",
        f"Honest drawback small bottle big price.",
        f"Worth premium collection claim.",
        f"Mast batch depth.",
        f"Baarish indoor premium tea.",
        f"Subtle collector grade.",
        f"First Anand Rasa premium—trust peak.",
        f"Evening gala premium only.",
        f"Sensitive migraine no trigger.",
        f"Gift milestone promotion—fit.",
        f"Repeat collector third premium.",
        f"Honest 5 stars special events.",
        f"Layer moisturizer rich extended.",
        f"Book wine pairing premium—worked.",
        f"4 star wish larger size.",
        f"Worth consult pick story.",
        f"Rare bloom accurate description.",
        f"Family celebration premium—memorable.",
        f"Subtle flagship find quality.",
        f"First premium attar—eyes opened.",
        f"Honest review price conscious ok.",
        f"Winter wedding premium guest.",
        f"Summer gala survived elegant.",
        f"Monsoon indoor premium appropriate.",
        f"Compliment jeweler again funny.",
        f"Kid said fancy bottle—cute.",
        f"Premium packaging museum quality.",
        f"Slow special occasion savor.",
        f"Honest—not every week wear.",
        f"Worth premium splurge once.",
        f"Travel premium weekend—one bottle.",
        f"Honest 5 stars heirloom gift.",
        f"Office not—but Friday premium ok.",
        f"Premium house best accurate.",
        f"Repeat VIP club interest.",
        f"Sach bolu top tier resin.",
        f"Headache prone passed.",
        f"Gift parents golden anniversary—cried.",
        f"Honest drawback intimidation price.",
        f"Repeat festival premium open.",
        f"Evening premium dinner scent.",
        f"Premium worth consultation.",
        f"Honest review collector perspective.",
        f"First premium opened wedding.",
        f"Mast rare bloom.",
        f"Baarish reading premium nook.",
        f"Subtle spa level.",
        f"Worth premium label earned.",
        f"Honest 4 star projection discrete.",
        f"Gift CEO—appropriate.",
        f"Sensitive skin premium month fine.",
        f"Corporate VIP premium—success.",
        f"Worth price memorable wears.",
        f"Travel honeymoon premium—special.",
        f"Honest review premium realistic.",
        f"First premium—standard line also good.",
        f"Layer subtle solo premium best.",
        f"Premium memorable confirmed.",
        f"Repeat batch number hunt.",
        f"Honest 5 stars flagship.",
        f"Wedding premium gift—hit.",
        f"Mast collector grade.",
        f"Baarish premium cozy.",
        f"Subtle heirloom pour.",
        f"First bottle saved year—opened anniversary.",
        f"Sach bolu premium hold.",
        f"Honest drawback casual overspend guilt.",
        f"Repeat premium loyal niche.",
        f"Evening art preview scent.",
        f"Premium worth house best.",
        f"Honest review splurge justified.",
    ]


def _limited_bodies():
    return [
        f"Drop day purchase {SHORT}—waitlist win adrenaline.",
        f"Seasonal batch numbered—collect now urge real.",
        f"Collab release—exclusive dry-down different.",
        f"Anniversary edition gift—recipient framed box.",
        f"Sold out restock alert—finally got.",
        f"Launch party wore—conversation starter.",
        f"Early access VIP—worth membership.",
        f"One time blend—savoring slowly.",
        f"4 stars—FOMO pricing high quality ok.",
        f"First limited—collector mindset activated.",
        f"Honest—not mass daily—special shelf.",
        f"Sensitive skin limited fine.",
        f"Gift collector friend—screamed.",
        f"Repeat limited drops follow.",
        f"Travel not opening—display.",
        f"Compliment launch party—exclusive club.",
        f"Premium numbered gem packaging.",
        f"Instagram drop countdown—got it.",
        f"Honest drawback anxiety inducing marketing.",
        f"Worth limited pour quality.",
        f"Mast batch number pride.",
        f"Baarish unboxing limited—cozy excitement.",
        f"Subtle exclusive dry-down real.",
        f"First Anand Rasa limited—hooked drops.",
        f"Evening opened limited—special.",
        f"Sensitive migraine ok.",
        f"Gift husband birthday limited—won.",
        f"Repeat waitlist subscriber.",
        f"Honest 5 stars exclusive quality.",
        f"Layer not yet—saving.",
        f"Book collector fragrance—chapter added.",
        f"4 star wish bigger limited size.",
        f"Worth waitlist finally.",
        f"Rare resin noticeable vs standard.",
        f"Family knew drop day—supportive.",
        f"Subtle edition glow marketing ok.",
        f"First limited FOMO—survived.",
        f"Honest review collector joy.",
        f"Winter opened limited holiday.",
        f"Summer stored cool dark.",
        f"Monsoon unboxing dry—relief.",
        f"Compliment fellow buyer online forum.",
        f"Kid not allowed touch bottle—funny.",
        f"Premium numbered presentation.",
        f"Slow use preserve—special.",
        f"Honest—not resale flip—wear.",
        f"Worth limited anxiety once.",
        f"Travel carry limited risky—left home.",
        f"Honest 5 stars drop day win.",
        f"Office limited Friday—special.",
        f"Premium once yearly treat.",
        f"Repeat drop alerts on.",
        f"Sach bolu rare resin.",
        f"Headache prone passed.",
        f"Gift limited exchange—priceless reaction.",
        f"Honest drawback pressure marketing.",
        f"Repeat third limited—consistent exclusive.",
        f"Evening limited wear monthly.",
        f"Premium worth collect.",
        f"Honest review FOMO realistic.",
        f"First drop caught—lucky.",
        f"Mast numbered gem.",
        f"Baarish limited unbox.",
        f"Subtle exclusive character.",
        f"Worth limited edition promise.",
        f"Honest 4 star standard line also great—comparison.",
        f"Gift limited wedding—unique.",
        f"Sensitive skin limited ok.",
        f"Corporate limited gift rare—wow.",
        f"Worth premium limited price.",
        f"Travel display only.",
        f"Honest review collector satisfied.",
        f"First limited—standard also ordered.",
        f"Layer saving for special.",
        f"Premium exclusive confirmed.",
        f"Repeat waitlist ritual.",
        f"Honest 5 stars exclusive dry-down.",
        f"Wedding limited guest—unique.",
        f"Mast drop day story.",
        f"Baarish limited cozy open.",
        f"Subtle batch number flex.",
        f"First bottle sealed months—opened festival.",
        f"Sach bolu limited pour special.",
        f"Honest drawback hype stress.",
        f"Repeat collector community.",
        f"Evening limited ritual monthly.",
        f"Premium presentation collectable.",
        f"Honest review worth wait.",
    ]


def _seasonal_bodies():
    return [
        f"Monsoon terrace {SHORT}—hold surprising damp air.",
        f"Summer wedding guest—humidity wise behaved.",
        f"Winter shawl scent—depth beautiful cold.",
        f"Spring picnic—light bloom appropriate.",
        f"Autumn travel—season shift scent matched.",
        f"Mango season ghar—weird good combo.",
        f"Diwali week seasonal—festive overlap.",
        f"December wedding—winter depth perfect.",
        f"Hill station trip—cool air sharper projection.",
        f"Coastal monsoon—salt air resin nice.",
        f"4 stars—monsoon needed extra dab.",
        f"First seasonal tag—interesting concept.",
        f"Honest—weather smart marketing real.",
        f"Sensitive skin seasonal fine.",
        f"Gift sister monsoon birthday—fit.",
        f"Repeat monsoon bottle annual.",
        f"Travel seasonal vacation scent.",
        f"Compliment hill station hotel—funny.",
        f"Premium seasonal packaging subtle.",
        f"Instagram monsoon reel—ordered.",
        f"Honest drawback storage off season.",
        f"Worth seasonal collection experiment.",
        f"Mast monsoon hold.",
        f"Baarish terrace seasonal perfect.",
        f"Subtle weather smart.",
        f"First Anand Rasa seasonal—more tags.",
        f"Evening monsoon seasonal ritual.",
        f"Sensitive migraine ok.",
        f"Gift parents winter trip—appropriate.",
        f"Repeat summer winter pair bottles.",
        f"Honest 5 stars monsoon user.",
        f"Layer moisturizer monsoon longer.",
        f"Book rainy season read scent.",
        f"4 star summer prefer lighter tag.",
        f"Worth season shift claim.",
        f"Humidity wise accurate.",
        f"Family seasonal festival overlap.",
        f"Subtle coastal air note.",
        f"First attar seasonal—fun.",
        f"Honest review weather realistic.",
        f"Winter delhi pollution mask scent comfort.",
        f"Summer bangalore office ok.",
        f"Monsoon mumbai essential.",
        f"Compliment seasonal appropriate.",
        f"Kid monsoon cozy—home.",
        f"Premium seasonal gift.",
        f"Slow year rhythm bottles.",
        f"Honest—not four bottles necessary—nice.",
        f"Worth seasonal curious.",
        f"Travel hill station—packed.",
        f"Honest 5 stars monsoon terrace.",
        f"Office seasonal subtle.",
        f"Premium worth weather match.",
        f"Repeat monsoon loyal.",
        f"Sach bolu humidity wise.",
        f"Headache prone passed.",
        f"Gift friend relocation climate—thoughtful.",
        f"Honest drawback niche tags.",
        f"Repeat autumn travel bottle.",
        f"Evening seasonal walk.",
        f"Premium seasonal presentation.",
        f"Honest review climate tested.",
        f"First monsoon opened June.",
        f"Mast shawl winter scent.",
        f"Baarish seasonal obvious match.",
        f"Subtle hill cool.",
        f"Worth seasonal tag shop.",
        f"Honest 4 star spring light prefer floral more.",
        f"Gift seasonal diwali overlap.",
        f"Sensitive skin seasonal ok.",
        f"Corporate seasonal gift trendy.",
        f"Worth premium seasonal math.",
        f"Travel seasonal carry.",
        f"Honest review year round optional.",
        f"First seasonal set—monsoon fav.",
        f"Layer seasonal subtle.",
        f"Premium seasonal gift box.",
        f"Repeat climate moved cities—reorder seasonal.",
        f"Honest 5 stars monsoon hold.",
        f"Wedding seasonal guest—appropriate.",
        f"Mast coastal monsoon.",
        f"Baarish mango season.",
        f"Subtle season shift.",
        f"First bottle monsoon June.",
        f"Sach bolu weather smart.",
        f"Honest drawback marketing many seasons.",
        f"Repeat seasonal explorer.",
        f"Evening terrace monsoon.",
        f"Premium worth climate match.",
        f"Honest review seasonal role fun.",
    ]


def _generic_bodies():
    return [
        f"Pehli baar attar try {SHORT}—alcohol perfume se gentler.",
        f"Cousin wedding discovery—compliment mila.",
        f"Online order skeptical—pleasantly surprised.",
        f"Store discovery Mumbai—staff helpful sample.",
        f"Travel bottle purse—leak test passed.",
        f"Layering experiment coconut oil—worked.",
        f"Compliment day random—confidence up.",
        f"Quiet dinner date—subtle appropriate.",
        f"Bookstore afternoon—literary vibe scent?",
        f"Weekend market errands—daily dab.",
        f"4 stars—first attar learning curve application.",
        f"First Anand Rasa—gateway brand.",
        f"Honest—generic axis still quality.",
        f"Sensitive skin first attar month fine.",
        f"Gift unsure recipient—hit.",
        f"Repeat second bottle different line.",
        f"Travel first attar—converted.",
        f"Compliment friend noticed.",
        f"Premium packaging first impression.",
        f"Instagram discovery reel—ordered.",
        f"Honest drawback which collection next confusion.",
        f"Worth trying brand entry.",
        f"Mast warm balance.",
        f"Baarish first order cozy.",
        f"Subtle human craft.",
        f"First attar honestly—impressed.",
        f"Evening first wear nervous—ok.",
        f"Sensitive migraine passed first.",
        f"Gift mother first attar—she loves.",
        f"Repeat exploring collections.",
        f"Honest 5 stars introduction.",
        f"Layer moisturizer discovered forums.",
        f"Book mentioned attars—tried.",
        f"4 star wish clearer collection guide.",
        f"Worth long term use potential.",
        f"Feel myself cheesy but true.",
        f"Family first attar collective order.",
        f"Subtle elegant bottle.",
        f"First order festival timing.",
        f"Honest review newbie friendly.",
        f"Winter first attar shawl hold.",
        f"Summer first attar light surprise.",
        f"Monsoon first attar behaved.",
        f"Compliment wedding unexpected.",
        f"Kid noticed nice—cute.",
        f"Premium start marker.",
        f"Slow exploration ongoing.",
        f"Honest—not expert—happy customer.",
        f"Worth generic quality high.",
        f"Travel discovery trip purchase.",
        f"Honest 5 stars first bottle.",
        f"Office tried subtle ok.",
        f"Premium feel justified.",
        f"Repeat brand loyal starting.",
        f"Sach bolu worth it.",
        f"Headache prone first test ok.",
        f"Gift friend curious attar—converted.",
        f"Honest drawback navigation collections.",
        f"Repeat third product different axis.",
        f"Evening puja also works generic.",
        f"Premium worth first try.",
        f"Honest review unbiased entry.",
        f"First bottle month lasted light.",
        f"Mast coconut layer tip.",
        f"Baarish online order arrived dry.",
        f"Subtle fabric longevity.",
        f"Worth Anand Rasa introduction.",
        f"Honest 4 star projection learning.",
        f"Gift husband first attar—uses.",
        f"Sensitive skin encouraged continue.",
        f"Corporate gift first time brand—safe.",
        f"Worth premium entry price.",
        f"Travel home scent memory.",
        f"Honest review starter honest.",
        f"First order hooked explore planet.",
        f"Layer simple best generic.",
        f"Premium evening lift.",
        f"Repeat cart adds.",
        f"Honest 5 stars brand trust start.",
        f"Wedding guest generic still good.",
        f"Mast feel myself moment.",
        f"Baarish weekend market scent.",
        f"Subtle start marker.",
        f"First attar year ago—many since.",
        f"Sach bolu human craft.",
        f"Honest drawback collection overwhelm.",
        f"Repeat recommend friends.",
        f"Evening literary vibe confirmed.",
        f"Premium bottle kept.",
        f"Honest review generic high bar.",
    ]


GENERATORS = {
    "apsara": _apsara_bodies,
    "astrology": _astrology_bodies,
    "mood": _mood_bodies,
    "festival": _festival_bodies,
    "daily": _daily_bodies,
    "meditation": _meditation_bodies,
    "premium": _premium_bodies,
    "limited": _limited_bodies,
    "seasonal": _seasonal_bodies,
    "generic": _generic_bodies,
}
